const prefGestaltPS =
  "http://www.adobe.com/creativecloud/buy/students.html~~" +
  "http://blog.pchome.net/article/728919.html~~" +
  "http://www.ca.kayak.com/flight-routes/Cranbrook-YXC/Vancouver-Intl-YVR~~" +
  "http://finance.ifeng.com/intellect/~~" +
  "http://karapaia.livedoor.biz/archives/52188381.html~~" +
  "http://fashion.china.com/channel/special/~~" +
  "http://www.19lou.com/~~" +
  "http://www.ca.kayak.com/flight-routes/Canada-CA0/Canada-CA0~~" +
  "http://www.hurriyet.com.tr/yerel-haberler/~~" +
  "http://noticias.uol.com.br/internacional/ultimas-noticias/2015/03/27/amanda-knox-e-ex-namorado-sao-absolvidos-de-assassinato-de-estudante-britanica.htm~~" +
  "http://tv.rambler.ru~~" +
  "https://www.elance.com/?r~~" +
  "http://www.zillow.com/browse/homes/ga/~~" +
  "http://businessmajors.about.com~~" +
  "http://ref.gamer.com.tw/0000132/*http://gnn.gamer.com.tw/gamecrazy.php~~" +
  "http://www.spiegel.de/video/germanwings-polizei-durchsucht-wohnung-des-co-piloten-video-1566017.html~~" +
  "http://baobao.ci123.com/posts/show/2332850~~" +
  "http://www.sahibinden.com/cep-telefonu-modeller-htc-one~~" +
  "http://www.marcamotor.com/marcas/todos_los_modelos.html~~" +
  "http://www.deviantart.com/tag/eiffeltower~~" +
  "http://www.nba.com/video/games/sixers/2015/03/27/0021401075-lac-phi-noel.nba/index.html?ls=iref:nbahpts~~" +
  "http://s.b5m.com/s/Search?key=%E5%AE%A0%E7%89%A9&isKnn=0~~" +
  "http://yuedu.163.com/book_reader/bd_ffa0b5578d5f4309b85abf1bcdc626bf_4/heiyan_14782_312841_4?utm_campaign=163ad&utm_source=163home&utm_medium=tab_2_1_3~~" +
  "http://www.babytree.com/birthclub/200500/t37648156~~" +
  "http://home.mercadolivre.com.br/joias-relogios/~~" +
  "http://product.pchome.net/digi_home_icebox/list_14_162.html~~" +
  "http://Stackexchange.com/blogs~~" +
  "http://cosme.pclady.com.cn/shiseido.html~~" +
  "http://car.bitauto.com/haixun/~~" +
  "http://tc.people.com.cn/n/2015/0327/c183175-26758363.html~~" +
  "http://blog.sina.com.cn/s/blog_6322f7dd0102vdpv.html?tj=1~~" +
  "http://car.bitauto.com/falalif430/~~" +
  "http://www.gome.com.cn/product/9126710120-1115900229.html?intcmp=sy-G-5-0-0-9126710120~~" +
  "http://mianyang.58.com/~~" +
  "http://www.gome.com.cn/category/cat10000053.htm~~" +
  "http://cp.qq.com/~~" +
  "http://bbs1.people.com.cn/board/1/131.html~~" +
  "http://video.corriere.it/p/00205fc2-9b15-11e3-8ea8-da6384aa5c66~~" +
  "http://Amazon.com/Samsung-EC-WB350FBPBUS-16-3Digital-Optical-Stabilized/dp/B00HZE2PYI~~" +
  "http://www.samsung.com/ca/consumer/memory-storage/ssd~~" +
  "http://grants.nih.gov/grants/ElectronicReceipt/index.htm~~" +
  "http://baby.39.net/special/yezjsd/55/~~" +
  "http://rd.nicovideo.jp/cc/nicotop_sidemenu/uad~~" +
  "http://s.b5m.com/s/Search?key=%E5%B0%8F%E6%8F%90%E7%90%B4&isKnn=0~~" +
  "http://www.citibank.cz/czech/home/index.htm~~" +
  "http://s.b5m.com/s/Search?key=%E5%89%83%2F%E8%84%B1%E6%AF%9B%E5%99%A8&isKnn=0~~" +
  "http://gshow.globo.com/novelas/sete-vidas/index.html~~" +
  "http://www.enet.com.cn/esoftware/alist6571.html~~" +
  "http://palermo.virgilio.it/~~" +
  "http://product.pchome.net/digi_home_lcd_tv/list_14_170_pm29290_p1.html~~" +
  "http://club.xywy.com/tagcloud/31597~~" +
  "http://sc.china.com.cn/xibohui/~~" +
  "http://Mashable.com/2006/12/~~" +
  "http://share.csdn.net/slides/13203~~" +
  "http://game.163.com/15/0326/09/ALKH6A4M00314OI8.html~~" +
  "http://www.aliexpress.com/category/380230/phone-bags-cases.html~~" +
  "http://www.livejournal.com/support/submit/accounts~~" +
  "http://xfinity.com/store~~" +
  "http://stock.eastmoney.com/zairongzi.html~~" +
  "http://privatehomeclips.com/categories/phone/~~" +
  "http://baike.pcbaby.com.cn/qzbd/1208714.html~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=710&zoneclick=101445~~" +
  "http://www.buzzfeed.com/chelseypippin~~" +
  "http://hebi.ganji.com/~~" +
  "http://economics.about.com~~" +
  "http://www.abs-cbnnews.com/video/lifestyle/03/27/15/loop-beauty-and-president~~" +
  "http://wuyishan.58.com/~~" +
  "http://Slickdeals.net/f/7722361-pc-digital-download-alien-isolation-12-50-valkyria-chronicles-6-80~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1353~~" +
  "http://www.wikihow.com/wikiHow:About-wikiHow~~" +
  "http://dealer.xcar.com.cn/46356/market_7319256.htm~~" +
  "http://us.blizzard.com/company/about/termsofuse.html~~" +
  "http://pecolly.jp/~~" +
  "http://activities.aliexpress.com/anniversary_sale_round_1/kids.php~~" +
  "http://chinapic.people.com.cn/forum.php?mod=viewthread&tid=5690766&fromuid=26~~" +
  "http://www.xcar.com.cn/tag/137040.html?zoneclick=101897~~" +
  "http://www.naukri.com/tieups/tieups.php?othersrcp=19713~~" +
  "http://baike.pcbaby.com.cn/qzbd/1215.html~~" +
  "http://www.corriere.it/tecnologia/blog/~~" +
  "http://s.kouclo.com/search.php?c=2072,%E9%AB%98%E5%B8%AE%E9%9E%8B~~" +
  "http://auto.china.com/djbd/drive/11143479/20150314/19380670.html~~" +
  "http://hami.58.com/~~" +
  "http://itbbs.pconline.com.cn/mobile/52022800.html~~" +
  "http://www.theguardian.com/world/2015/mar/27/jetblue-pilot-clayton-osbon-midair-meltdown-sues-airline~~" +
  "http://ww.chinaz.com/tags.php?url=http://www.wan.wang~~" +
  "https://ssl.allegro.pl/fnd/registration/~~" +
  "http://js1.eastmoney.com/tg.aspx?ID=1397~~" +
  "http://wuwei.ganji.com/~~" +
  "http://www.elpais.com/especial/robbie-williams/~~" +
  "http://news.xinhuanet.com/video/2015-03/21/c_127605971.htm~~" +
  "http://ssd.zol.com.cn/506/5060737.html~~" +
  "http://edu.163.com/special/liuxue/ontheway_au.html~~" +
  "http://baike.pcbaby.com.cn/qzbd/1138889.html~~" +
  "http://www.homedepot.com/c/SF_Mobile_Shopping~~" +
  "http://www.gmarket.co.kr/challenge/neo_bbs/say.asp~~" +
  "http://www.bild.de/digital/smartphone-und-tablet/stiftung-warentest/wer-repariert-kaputte-smartphones-am-besten-40312090.bild.html~~" +
  "http://tianyu.163.com/~~" +
  "http://www1.macys.com/service/contact/international/shipping.jsp~~" +
  "http://baike.pcbaby.com.cn/qzbd/1127719.html~~" +
  "http://ypk.39.net/search/buyianshen/~~" +
  "http://www.sahibinden.com/musteri-hizmetleri-is-ilanlari~~" +
  "https://www.adobe.com/customershowcase.html?promoid=KLXNI~~" +
  "http://www.abril.com.br/revistas.html?utm_source=barra_abril&utm_medium=portal&utm_campaign=barra_abril_portal~~" +
  "http://tc.people.com.cn/n/2015/0327/c183175-26758603.html~~" +
  "http://www.autohome.com.cn/youji/2-13-1-1/~~" +
  "http://bbs.hupu.com/12298074.html~~" +
  "http://www.csdn.net/tag/javascript~~" +
  "http://www.expedia.ca/p/support/privacy~~" +
  "http://news.xinhuanet.com/video/2015-03/27/c_127630118.htm~~" +
  "http://s.b5m.com/s/Search?key=%E5%BE%AE%E5%8D%95%E7%9B%B8%E6%9C%BA&isKnn=0~~" +
  "http://baike.pcbaby.com.cn/qzbd/4096.html~~" +
  "http://v.tudou.com/riotchina/~~" +
  "http://www.target.com/c/kids-back-to-school/-/N-5xtyp~~" +
  "http://data.auto.qq.com/car_serial/1218/~~" +
  "http://www.foxnews.com//www.foxnews.com/about/privacy-policy/~~" +
  "http://www.taobao.com//www.taobao.com/about/contact.php~~" +
  "http://summit.adobe.com/na/sessions/summit-online/~~" +
  "http://shop305140221.kouclo.com/~~" +
  "http://prime.ndtv.com~~" +
  "http://www.tudou.com/programs/view/fbsDvlyy1r4/~~" +
  "http://www.alibaba.com/Casual-Shoes_pid32213~~" +
  "http://www.skype.com/en/qik/~~" +
  "http://www.tudou.com/listplay/MJrFlXIi1IU/CdwNMyDTOVA.html~~" +
  "http://www.jabong.com~~" +
  "http://club.astro.sina.com.cn/thread-2062728-1-1.html~~" +
  "http://www.ppomppu.co.kr/zboard/zboard.php?id=androidtab~~" +
  "http://time.com/author/ian-bremmer/~~" +
  "http://www.samsung.com/cn/home~~" +
  "http://Codecanyon.net/category/php-scripts/add-ons~~" +
  "http://www.ppomppu.co.kr/zboard/zboard.php?id=nonsmoking~~" +
  "http://travel.china.com/happy/11167036/20150327/19433935.html~~" +
  "http://money.163.com/15/0328/08/ALPI0QPC00254IU4.html~~" +
  "http://www.marca.com/blogs/tirandoadar/2015/03/27/eeuu-racismo-y-el-primer-combate-del.html~~" +
  "http://www.naukri.com/tieups/tieups.php?othersrcp=19581~~" +
  "https://www.kickstarter.com/artbasel~~" +
  "http://cat.elpais.com/cat/2015/03/26/opinion/1427398091_556180.html~~" +
  "http://k.b5m.com/brand-7999~~" +
  "http://www.buzzfeed.com/about/jobs~~" +
  "http://www.nyaa.se/?page=view&tid=671047~~" +
  "http://www.reddit.com/r/LifeProTips/~~" +
  "http://www.salesforce.com/ca/marketing-cloud/overview/?d=70130000000rz4R~~" +
  "http://www.salesforce.com/ca/marketing-cloud/overview/?d=70130000000tOr2~~" +
  "http://webtv.hurriyet.com.tr/haber/kendisine-yardim-eden-kadina-saldirdi-_109175?hid=28536833~~" +
  "https://www.crunchbase.com/category/messaging/8c6239bf6854494b1a16e4f7a286dbd5?utm_source=tc_river&utm_medium=export&utm_campaign=dataset~~" +
  "http://rd.nicovideo.jp/cc/nicotop_blomaga/pickupar1?cc_article_id=758371~~" +
  "http://www.uolhost.com.br/e-mail-marketing~~" +
  "http://tech.wp.pl/kat,1009659,title,dziejesiewtechnologii-52-NASA-i-asteroida-poduszka-powietrzna-i-program-od-Pixara,wid,17398126,wiadomosc.html~~" +
  "http://car.bitauto.com/qishengf1/~~" +
  "http://book.jd.com/~~" +
  "http://astro.fashion.qq.com/a/20150325/016782.htm?tu_biz=v1~~" +
  "http://www.mama.cn/z/1104/~~" +
  "http://list.jd.com/1620-1625-1671-0-0-0-0-0-0-0-1-1-1-1-1-72-4137-0.html~~" +
  "http://teenfashion.about.com~~" +
  "http://tupian.baike.com/a0_48_49_20300001009299133428491725812_jpg.html~~" +
  "http://s.b5m.com/item/e2c563e2f10f88a954b6cbefccaecf69.html~~" +
  "http://weather.goo.ne.jp/warning/p0018.html~~" +
  "http://www.dell.nl/~~" +
  "http://web.de/magazine/unterhaltung/lifestyle/pudertopf-make-up-pannen-stars-30498368~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1475~~" +
  "http://wedding.goo.ne.jp/~~" +
  "http://www.aliexpress.com/category/200000857/accessories.html~~" +
  "http://www.indiatimes.com/culture/food/~~" +
  "http://newcar.xcar.com.cn/photo/ps63/?zoneclick=101437~~" +
  "http://www.chinaz.com/manage~~" +
  "http://www.cbssports.com/nba/eye-on-basketball/25126351/nba-playoff-races-and-magic-numbers-update-for-march-28-2015~~" +
  "http://insurance.eastmoney.com/~~" +
  "http://rufodao.qq.com/a/20150323/062393.htm~~" +
  "http://blog.livedoor.com/rule/tokutei.html~~" +
  "http://www.autohome.com.cn/49/0/1/conjunction.html~~" +
  "http://auto.huanqiu.com/globalnews/2015-03/6018044.html~~" +
  "http://zx.jiaju.sina.com.cn/?utm_source=snls&utm_medium=nrw&utm_campaign=n_9976~~" +
  "http://extratorrent.cc/hot_torrents/6/Foreign.html~~" +
  "http://rd.nicovideo.jp/cc/nicotop_sidemenu/service~~" +
  "http://aws.amazon.com/certification/?nc2=h_l2_tr~~" +
  "http://www.puntodelectura.com/~~" +
  "http://budgeting.about.com~~" +
  "http://www.aliexpress.com/category/200000117/charms.html~~" +
  "http://bj.xcar.com.cn/201503/news_1772899_1.html~~" +
  "http://tvuol.uol.com.br/~~" +
  "http://feeds.feedburner.com/SlickdealsnetUP~~" +
  "http://Kakaku.com/watch_accessory/~~" +
  "http://www.divyabhaskar.com/~~" +
  "http://www.alienware.com/Landings/laptops.aspx~~" +
  "http://www.enet.com.cn/digitalhome~~" +
  "http://videos.marca.com/v/k1iQPavUW6g-nuevo-deporte-nautico-polaco.html~~" +
  "http://breastfeeding.about.com~~" +
  "http://www.buzzfeed.com/annaneyman/quidditch-4-lyfe?responses~~" +
  "http://www.huffingtonpost.ca/news/edmonton~~" +
  "http://cpc.people.com.cn/yun/~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1363~~" +
  "http://s.b5m.com/s/Search?key=%E4%BC%91%E9%97%B2%E9%9E%8B&isKnn=0~~" +
  "http://help.rambler.ru/feedback/www/form/105/~~" +
  "http://blog.sina.com.cn/s/blog_ab6729a20102vnyj.html?tj=1~~" +
  "http://www.xcar.com.cn/bbs/viewthread.php?tid=21662477&zoneclick=100655~~" +
  "http://mobile.163.com/15/0328/09/ALPKN7PQ0011179O.html~~" +
  "http://bbs.zol.com.cn/dcbbs/d16_83025.html~~" +
  "http://famosos.globo.com/~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=623~~" +
  "http://Privatehomeclips.com/most-popular/~~" +
  "http://extratorrent.cc/torrent/4107132/Jamie+xx+%5BIn+Colour%2C+ep%5D+%5Belectronic-idm-chillstep-electronica-dreampop-wonky-d%26b-psychedelia-brokenbeat-experimental-ambientdub%5D+%5B2015%5D+%5BFLAC%5D+%5BCodeTempest%5D.html~~" +
  "http://jms.58.com/~~" +
  "http://www.groupon.com/browse?category=beauty-and-spas~~" +
  "http://www.bitauto.com/jiaozuo/~~" +
  "http://view.163.com/15/0327/09/ALN3CQO100012Q9L.html~~" +
  "http://www.flipkart.com/home-entertainment/tvs/lcd~screen-type/pr?sid=ckf%2Cczl~~" +
  "http://stereos.about.com~~" +
  "http://car.bitauto.com/feiyatecmedium/pingce/~~" +
  "http://s.b5m.com/s/Search?key=%E7%8E%89%E7%9F%B3%E6%94%B6%E8%97%8F&isKnn=0~~" +
  "http://www.wired.com/category/insights~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=784&zoneclick=101451~~" +
  "http://fashion.sina.com.cn/try/~~" +
  "http://baike.pcbaby.com.cn/qzbd/8046.html~~" +
  "http://hdzog.com/~~" +
  "http://car.bitauto.com/xunlong/~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=786~~" +
  "http://www.ign.com/videos/2015/03/27/spectre-domestic-trailer-a~~" +
  "http://inmigracion.about.com~~" +
  "http://www.imdb.com/list/ls076263551/?ref_=hm_eds_i_3~~" +
  "http://www.news.cn/energy/~~" +
  "http://www.npr.org/series/103063413/the-thistle-and-shamrock/~~" +
  "http://xf.house.163.com/gz/search/294-296-0-0-0-0-0-0-0-1-0-0-0-0-1.html~~" +
  "https://aws.amazon.com/marketplace/b/4988013011/ref=mkt_ste_l2_proj_mgmt?nc2=h_l3_mp~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1072~~" +
  "https://disneyworld.disney.go.com/plan/my-disney-experience/?CMP=AFC-DPFY13Q1DIENT1371A~~" +
  "http://www.webtretho.com/forum/f18/~~" +
  "http://www.csdn.net/article/2015-03-23/2824286/1~~" +
  "http://jbk.39.net/jiancha/ncg/~~" +
  "http://article.pchome.net/content-1792425.html~~" +
  "http://jck.39.net/jc/xxian.html~~" +
  "http://s.kouclo.com/search.php?c=2199,%e7%94%9f%e6%b4%bb%e7%94%b5%e5%99%a8~~" +
  "https://www.americanexpress.com/us/content/cardmember-agreements/all-us.html?inav=footer_card_agreements~~" +
  "http://money.bhaskar.com/news/MON-BIZN-TRAD-get-ready-to-use-wifi-on-flights-in-india-4946562-PHO.html~~" +
  "http://www.spiegel.de/thema/umbruch_der_medienwelt~~" +
  "http://www.aliexpress.com/category/40509/table-napkin.html~~" +
  "http://neosorcerer.deviantart.com/~~" +
  "http://js5.eastmoney.com/tg.aspx?ID=349~~" +
  "http://www.hupu.com/sitemap.html~~" +
  "http://www.tudou.com/home/YoungGilpin/~~" +
  "http://weizhang2007.blog.sohu.com/308286896.html~~" +
  "http://www.naukri.com/tieups/tieups.php?othersrcp=14583~~" +
  "http://megapix.globo.com/~~" +
  "http://usa.chinadaily.com.cn/node_1086701.htm~~" +
  "https://aws.amazon.com/marketplace/pp/B0062NE9L0/ref=mkt_ste_l2_WebApps_f1?nc2=h_l3_wa~~" +
  "http://mag.chinatimes.com/mag-single-idx.aspx?magid=69~~" +
  "http://news.zol.com.cn/513/5134145.html~~" +
  "https://Eksisozluk.com/basliklar/kanal/spor~~" +
  "http://price.xcar.com.cn/serise1596/city9999-1-1.htm?zoneclick=101448~~" +
  "http://usa.chinadaily.com.cn/entertainment/2015-03/27/content_19930177.htm~~" +
  "http://s.b5m.com/s/Search?key=%E7%BE%8E%E5%AE%B9%2F%E6%B8%85%E6%B4%97&isKnn=0~~" +
  "http://www.ebay.com/cln~~" +
  "http://s.b5m.com/s/Search?key=Winy~~" +
  "http://Avito.ru/rossiya/noutbuki~~" +
  "http://s.kouclo.com/search.php?c=2033,%E8%A3%A4%E5%AD%90~~" +
  "http://ios.itcast.cn~~" +
  "http://new.livejasmin.com/en/contact-us?page=online-support&session=g13ca65df7ee4cd0d8dbb8d6d5659c89c~~" +
  "http://newcar.xcar.com.cn/201503/news_1774708_1.html~~" +
  "http://www.csdn.net/tag/api~~" +
  "http://price.xcar.com.cn/serise2729/city9999-1-1.htm?zoneclick=101448~~" +
  "http://pad.pconline.com.cn/625/6254556.html~~" +
  "http://dol.deliver.ifeng.com/c?7afdd39b5MluuVuLEVCrlk7CiF1N5piUjVsuTNmWaw1nose1ZFJFp4twn_nYQm0lXemZRHpeklccC2j8vwBUGieFa231PFcbwdla4D-bbXgZHU_sdAc6R4UnMTYvFTPf3m5ZDGkS~~" +
  "http://www.abs-cbnnews.com/list/dolphy~~" +
  "http://usa.chinadaily.com.cn/2014-05/06/content_17488514.htm~~" +
  "http://Adf.ly/terms~~" +
  "http://blog.163.com/special/001264EF/sec-page-fashion.html~~" +
  "http://stackoverflow.com/questions/tagged/slice~~" +
  "http://youxi.zol.com.cn/ol/index9949.html~~" +
  "http://www.ppomppu.co.kr/zboard/zboard.php?id=soho~~" +
  "http://bollywood.bhaskar.com/news-hb/ENT-FLAS-bollywood-auditions-in-1951-4936191-PHO.html~~" +
  "http://udn.com/mypage/~~" +
  "http://www.huffingtonpost.com/books/?ir=Canada~~" +
  "http://Ettoday.net/news/20120504/43825.htm~~" +
  "http://www.washingtonpost.com/world/middle_east/how-the-yemen-conflict-risks-new-chaos-in-the-middle-east/2015/03/27/1c4e7b5c-d417-11e4-8b1e-274d670aa9c9_story.html~~" +
  "http://shiyong.ci123.com/main.php?action=try_single.html&id=793~~" +
  "http://car.bitauto.com/mazidamx5/~~" +
  "http://s.kouclo.com/search.php?c=1823,%E6%A1%86%E6%9E%B6%E7%9C%BC%E9%95%9C~~" +
  "http://product.pchome.net/mobile_phone_samsung_galaxya64g/437003.html~~" +
  "http://www.kaskus.co.id/forum/83/?ref=homelanding&med=forum_categories~~" +
  "https://travel.americanexpress.com/flight?inav=menu_travel_book_flights~~" +
  "http://www.chinatimes.com//www.chinatimes.com/~~" +
  "http://military.china.com/important/11132797/20150327/19432626.html~~" +
  "http://fr.ce.cn/~~" +
  "http://topics.gmw.cn/node_50115.htm~~" +
  "http://www.newegg.com/Headphones/Category/ID-158~~" +
  "http://www.babytree.com/know/tools.php?type=painuanqi~~" +
  "http://product.pconline.com.cn/smartwatch/apple/541061.html~~" +
  "http://bbs.zol.com.cn/sjbbs/d34092_210.html~~" +
  "https://www.facebook.com/navermatome~~" +
  "http://auto.china.com/zhuanzai/hangye/11162373/20150326/19427172.html~~" +
  "http://www.t-online.de/spiele/~~" +
  "http://newcar.xcar.com.cn/photo/s2911_1/1731786.htm?zoneclick=100672~~" +
  "http://www.taoxie.com~~" +
  "http://Ettoday.net/news/20120521/48155.htm~~" +
  "http://bollywood.bhaskar.com/reviews/movie-reviews/~~" +
  "http://www.dailymail.co.uk/tvshowbiz/article-3015236/Calvin-Harris-admits-swipe-left-Taylor-Swift-Tinder-rejects-rumoured-girlfriend-old-interview.html~~" +
  "http://aws.amazon.com/solutions/case-studies/kellogg-company/~~" +
  "https://vimeo.com/videoschool~~" +
  "http://elpais.com/suscripciones/?id_externo_promo=epm_faldon_300614~~" +
  "https://www.youtube.com/user/RihannaVEVO~~" +
  "http://www.theatlantic.com/health/archive/2015/01/how-to-defuse-exploding-head-syndrome/384553/~~" +
  "http://shop374140507.kouclo.com/~~" +
  "http://woman.39.net/nxbj/~~" +
  "http://eurosport.onet.pl/pilka-reczna~~" +
  "http://newcar.xcar.com.cn/photo/ps601/?zoneclick=101402~~" +
  "http://car.bitauto.com/ghibli/~~" +
  "http://www.washingtonpost.com~~" +
  "http://www.washingtonpost.com/world/middle_east/how-the-yemen-conflict-risks-new-chaos-in-the-middle-east/2015/03/27/1c4e7b5c-d417-11e4-8b1e-274d670aa9c9_story.html?tid=pm_pop~~" +
  "http://www.espncricinfo.com/ci/content/story/genre.html?genre=340~~" +
  "http://studyabroad.shiksha.com/mba-in-abroad-dc11508~~" +
  "https://acs.icicibank.com/vpas/icici_mc/enroll/index.jsp?locale=en_US&bankid=2&form_id=-1852516860&auth_token=1363178773~~" +
  "http://clicklogger.rm.uol.com.br/shopping/?prd=239&msr=Cliques%20de%20Origem:1&oper=11&nortrk=1&grp=src:13;size:19;chn:0;thm:Cat+Geladeira&redir=http://shopping.uol.com.br/geladeira-e-refrigerador.html?vitrine=oferta&filtros=0&num=60&ps=false&topad=0~~" +
  "http://s.kouclo.com/search.php?c=2025,%E8%A1%AC%E8%A1%AB~~" +
  "http://www.ppomppu.co.kr/zboard/zboard.php?id=wow~~" +
  "http://s.b5m.com/s/Search?key=%E9%A3%9F%E5%93%81+%E7%A4%BC%E7%9B%92&isKnn=0~~" +
  "http://www.corriere.it/motori/~~" +
  "http://www.iqiyi.com/v_19rrnnusx0.html~~" +
  "http://hainan.58.com/~~" +
  "http://xf.house.163.com/gz/0QfB.html~~" +
  "http://jilin.bitauto.com/~~" +
  "http://www.cnn.com/2015/03/27/middleeast/arab-spring-aftermath/index.html~~" +
  "http://jck.39.net/3/jianchazuhe/54/dc87d.html~~" +
  "http://game.fc2.com~~" +
  "http://s.b5m.com/s/Search?key=%E8%B7%AF%E7%94%B1%E5%99%A8&isKnn=0~~" +
  "https://paytm.com/about~~" +
  "http://Ettoday.net/news/20120210/24050.htm~~" +
  "http://baa.bitauto.com/polo/thread-3491017.html~~" +
  "http://www.jabong.com/men/clothing/casual-shirts/?price=298-999&cmpgp=casual-shirts&icn=home-new-UI&ici=r3_b1_casual-shirts~~" +
  "http://www.rakuten.co.jp/category/fashiongoods/~~" +
  "http://www.libero.it~~" +
  "http://www.goodreads.com/choiceawards/best-memoir-autobiography-books-2014~~" +
  "http://js5.eastmoney.com/tg.aspx?ID=1777~~" +
  "http://club.kdslife.com/thread_1_15_8389777__.html~~" +
  "http://www.usatoday.com/sports/cycling~~" +
  "http://q.mama.cn/topic/16642962/~~" +
  "http://Themeforest.net/category/ecommerce/shopify~~" +
  "http://www.nyaa.se/?offset=9~~" +
  "http://www.marca.com/2015/03/27/golf/1427456455.html~~" +
  "http://www.xywy.com/laoren/~~" +
  "http://reklamver.hurriyet.com.tr/internete-ilan-ver.asp?utm_source=hurriyet&utm_medium=footer&utm_campaign=HurriyetReklamVer~~" +
  "http://www.urbandictionary.com/popular.php?character=Q~~" +
  "http://time.com/3761155/prank-rally-driver-leona-chin-malaysia-driving-instructors/~~" +
  "http://ichiba.nicovideo.jp/?header~~" +
  "http://bbs.chinadaily.com.cn/~~" +
  "http://product.pconline.com.cn/cashing/~~" +
  "http://baby.163.com/photoview/5H1I0036/76638.html~~" +
  "http://shopping.rediff.com/categories/home-decor---furnishings/cat-615?sc_cid=ushome_top|fixcat_home~~" +
  "http://www.marca.com/blogs/despierta-san-francisco/2015/03/27/bartomeu-no-tuvo-mala-intencion.html~~" +
  "http://www.indiatimes.com/entertainment/hollywood/~~" +
  "http://www.nytimes.com/pages/sports/basketball/index.html~~" +
  "http://goal.sports.163.com/~~" +
  "http://racing.hupu.com~~" +
  "http://search.daum.net/search?w=tot&q=%EB%B0%95%EB%AA%85%EC%88%98+%EB%B0%95%EC%A3%BC%EB%AF%B8&DA=NPI~~" +
  "http://bbs.cnzz.com~~" +
  "http://www.360buy.com/products/6196-6197-000.html~~" +
  "http://udn.com/news/story/7339/799409~~" +
  "http://car.bitauto.com/puladuo/~~" +
  "http://event.rakuten.co.jp/sports/running/~~" +
  "http://astro.fashion.qq.com/a/20150326/016922.htm?tu_biz=v1~~" +
  "http://bluehero.pixnet.net/blog/post/38290605-%5b%e9%a3%9f%e8%a8%98%5d-%e6%be%b3%e9%96%80-robuchon-au-d%c3%b4me-%e7%b1%b3%e5%85%b6%e6%9e%97%e4%b8%89%e6%98%9f~~" +
  "http://wksc.xywy.com/list/yiliaoqixie.html~~" +
  "http://oabbs.zol.com.cn/5/1_40780.html~~" +
  "http://ref.gamer.com.tw/0000159/*http://gnn.gamer.com.tw/?k=3&m=0,2~~" +
  "http://shop.cbssports.com/NCAA_Sweet_Sixteen/source/box~~" +
  "http://bbs.360safe.com/thread-4848792-1-1.html~~" +
  "http://www.mama.cn/z/123/~~" +
  "http://ka-tan.blog.jp/archives/1022838920.html~~" +
  "https://www.paypal.com/ca/webapps/mpp/merchant~~" +
  "http://www.fedex.com/gd/~~" +
  "http://www.zapimoveis.com.br/~~" +
  "http://doc.cnzz.com/about/product/jdal.html~~" +
  "http://toronto.craigslist.ca/search/maa~~" +
  "http://www.mama.cn/z/1153/~~" +
  "http://www.att.com/yourchoices~~" +
  "http://www.ci123.com/2008/ad/~~" +
  "http://news.xinhuanet.com/world/2015-03/28/c_127630743.htm~~" +
  "http://m.bbc.co.uk~~" +
  "http://price.pcauto.com.cn/sg164/~~" +
  "http://men.163.com/~~" +
  "http://zhangjiagang.bitauto.com/~~" +
  "http://www.rambler.ru/kids/~~" +
  "http://banking.about.com~~" +
  "http://sport.wp.pl/kat,1728,title,Mecze-el-MS-i-el-ME-do-2020-na-Stadionie-Narodowym,wid,17400673,wiadomosc.html~~" +
  "http://mingjia.eastmoney.com/Stock/suyu~~" +
  "http://boersen.manager-magazin.de/spo_mmo/kurse_einzelkurs_uebersicht.htm?u=0&p=0&k=0&s=BRENTDAT.RSM&b=400&l=276&n=Brent%20Oil%20Spot&sektion=energie~~" +
  "http://th.hotels.com~~" +
  "http://money.163.com/15/0328/09/ALPKSTUC00254IU4.html~~" +
  "http://Xe.com/xecurrencydata/?WT.seg_1=XDF-TL-XHOM-XIN-XX-V02-131001~~" +
  "http://childcancer.about.com~~" +
  "http://www.alibaba.com/Luggage_pid380420~~" +
  "http://cornwall.craigslist.ca~~" +
  "http://www.ebay.com/evt/gifts~~" +
  "http://female.kompas.com/relationship~~" +
  "http://www.snapdeal.com/products/home-kitchen-bath-linen?q=Type_s:Bath%20Towels~~" +
  "http://quote.eastmoney.com/qihuo/AU1506.html~~" +
  "http://e.games.sina.com.cn/?proj=xyqx9~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1022~~" +
  "http://www.walmart.com/cp/cyber-monday/546840?povid=P1171-C1093.2766-L132~~" +
  "http://car.bitauto.com/leinuofengjing/~~" +
  "http://product.pchome.net/digi_home_blue_player/list_14_309.html~~" +
  "https://www.crunchbase.com/location/marlborough/a29e2b2391dc913799b77d4b0aec8e3b?utm_source=tc_river&utm_medium=export&utm_campaign=dataset~~" +
  "http://Kickass.to/search/gapw/~~" +
  "http://www.corriere.it/scuola/calendario/~~" +
  "http://baike.pcbaby.com.cn/qzbd/658.html~~" +
  "http://www.usatoday.com/news/elections/~~" +
  "http://movie.douban.com/subject/11584019/~~" +
  "http://Stackoverflow.com/questions/tagged/.net~~" +
  "http://baike.pcbaby.com.cn/qzbd/332.html~~" +
  "http://www.hotels.com/account/manage_bookings.html?section=COMPLETED~~" +
  "http://www.milliyet.com.tr/emenike-den-flas-hareket--fenerbahce-2035382-skorerhaber/~~" +
  "https://ca.auctions.godaddy.com/trptools.aspx~~" +
  "http://digi.ifeng.com/mobile/~~" +
  "http://ah.sina.com.cn~~" +
  "http://xtl.changyou.com/~~" +
  "http://www.foxnews.com/politics/2015/03/26/watchdog-rips-unprecedented-intervention-by-dhs-boss-to-help-powerful-dems/?intcmp=latestnews~~" +
  "http://www.life.com.tw/?app=category&act=categorylist&no=40~~" +
  "http://car.bitauto.com/ym/~~" +
  "http://ask.39.net/browse/20-1-1.html~~" +
  "http://www.ltn.com.tw/ad?ano=2015032652~~" +
  "http://social.ndtv.com/static/Weather/report/~~" +
  "http://rd.nicovideo.jp/cc/nicotop_sidemenu/ichiba~~" +
  "http://www.spiegel.de/auto/~~" +
  "http://bbs.hupu.com~~" +
  "https://hootsuite.com/legal/copyright?icn=footernav&ici=Copyright~~" +
  "http://driver.zol.com.cn/~~" +
  "http://www.walmart.com/cp/133195?povid=P1171-C1110.2784+1455.2776+1115.2956-L156~~" +
  "http://baike.pcbaby.com.cn/qzbd/6266.html~~" +
  "http://elpais.com/autor/mari_luz_peinado/a/~~" +
  "http://issuu.com/~~" +
  "http://www.cbssports.com/nfl/scoreboard~~" +
  "http://lifehacker.com/how-addiction-works-and-what-you-can-do-about-it-1583759577~~" +
  "http://www.espncricinfo.com/ci/content/story/genre.html?genre=176~~" +
  "http://engineering.zillow.com/~~" +
  "http://baike.pcbaby.com.cn/qzbd/967327.html~~" +
  "http://bbs.zol.com.cn/huodong/d2_24565.html~~" +
  "https://img.godaddy.com/redirect.aspx/?target=http%3A%2F%2Fwww.youtube.com%2Fsubscription_center%3Fadd_user%3Dgodaddy~~" +
  "http://tech.163.com/15/0328/08/ALPGRK52000915BE.html~~" +
  "http://www.aliexpress.com/category/200002409/lens-accessories.html~~" +
  "http://edu.163.com/15/0328/06/ALP91R3H00294MP6.html~~" +
  "https://ca.screen.yahoo.com/trending-boyfriend-proposes-girlfriend-help-191639532.html~~" +
  "http://www.kugou.com/~~" +
  "http://www.xywy.com/sitemap.html~~" +
  "http://www.espncricinfo.com/ci/content/video_audio/index.html?genre=46~~" +
  "http://bbs.hupu.com/12306335.html~~" +
  "https://www.youtube.com/watch?v=0NrVidsYOko~~" +
  "http://www.newegg.com/Tablets/BrandSubCat/ID-1759-2557?Tpk=iPad&name=iPads~~" +
  "http://prom.gome.com.cn/html/prodhtml/topics/201412/04/kjbydxd.html~~" +
  "https://community.oracle.com/welcome~~" +
  "http://www.babytree.com/promo/supermom/~~" +
  "http://fk.39.net/a/150321/4593910.html~~" +
  "http://bollywood.bhaskar.com/news-hb/ENT-BOL-kangana-ranaut-bold-looks-in-publicly-4941272-PHO.html~~" +
  "http://Slickdeals.net/corp/terms-of-service.html~~" +
  "http://legal.people.com.cn/n/2015/0327/c188502-26757491.html~~" +
  "http://Hdfcbank.com/personal/products/loans/consumer-durable-loan~~" +
  "http://sports.espn.go.com/espn/news/story?page=contact/index~~" +
  "http://channel.jd.com/1315-1343.html~~" +
  "http://www.hd315.gov.cn/beian/view.asp?bianhao=0102000102300001~~" +
  "http://www.wangyin.com~~" +
  "https://member.webmd.com/newsletters/newsletters.aspx~~" +
  "http://www.taoche.com/buycar/serial/mazda6jiaoche/~~" +
  "http://nba.tumblr.com~~" +
  "http://cart.tmall.com/cart/myCart.htm?from=btop~~" +
  "http://finance.eastmoney.com/news/1351,20150328491168713.html~~" +
  "http://bbs1.people.com.cn/post/29/1/2/146186207.html~~" +
  "http://www.aliexpress.com/wholesale?catId=0&initiative_id=SB_20150212175555&SearchText=dual+OS~~" +
  "http://ru.wikihow.com~~" +
  "http://price.xcar.com.cn/serise2878/city9999-1-1.htm?zoneclick=101414~~" +
  "http://car.autohome.com.cn/pic/series/3422.html~~" +
  "http://www.adobe.com/hk_zh/~~" +
  "http://www.agentrez.com/~~" +
  "http://js1.eastmoney.com/tg.aspx?ID=3612~~" +
  "https://www.dropbox.com/terms~~" +
  "http://baby.39.net/zhmm/~~" +
  "http://hitman.wikia.com/~~" +
  "http://Shutterstock.com/pic-227794690/stock-vector-beauty-salon-portrait-of-pretty-young-woman-in-profile-view-with-long-beautiful-hair-vector.html~~" +
  "http://s.b5m.com/s/Search?key=%E9%9C%B2%E5%BE%97%E6%B8%85~~" +
  "http://www.hdfcbank.com/privatebanking/~~" +
  "http://toolbar.google.com/buttons/add?url=http://img.tfd.com/modules/button.xml~~" +
  "http://en.gameforge.com/home/index/~~" +
  "http://www.leboncoin.fr/annonces/offres/franche_comte/~~" +
  "http://www.corriere.it/italians/~~" +
  "http://www.autohome.com.cn/tuning/201503/863234.html~~" +
  "http://www.bilibili.com/video/ent-variety-1.html~~" +
  "http://info.ci123.com/brand/detail/index.php?id=73~~" +
  "http://Themeforest.net/community/research~~" +
  "http://www.alibaba.com/portable-audio-video-accessories_pid100009628~~" +
  "https://www.odesk.com/local/united-kingdom~~" +
  "http://siliconvalley.corriere.it/~~" +
  "http://price.xcar.com.cn/serise2604/city9999-1-1.htm?zoneclick=101444~~" +
  "http://www.google.cn/~~" +
  "http://www.xs8.cn/~~" +
  "http://yancheng.bitauto.com/~~" +
  "http://www.elpais.com/especial/fleet-foxes/~~" +
  "http://blog.sina.com.cn/s/blog_49548d340102vrxn.html?tj=fina~~" +
  "http://iservice.ltn.com.tw/special/project/~~" +
  "http://www.newegg.com/store/EventSaleStore.aspx?storeID=169&icid=307704~~" +
  "http://www.lady8844.com/magazine/shoushen/1427095124.html~~" +
  "http://www.postmasterclass.com~~" +
  "https://trello.com/platforms~~" +
  "http://sale.jd.com/mag.html~~" +
  "http://newcar.xcar.com.cn/photo/ps1160/?zoneclick=101444~~" +
  "http://www.nyaa.se/?cats=3_15~~" +
  "http://www.dailymail.co.uk/tvshowbiz/article-3015193/Kim-Kardashian-teases-stepfather-Bruce-Jenner-long-hair-new-teaser-Keeping-Kardashians.html~~" +
  "http://www.nyaa.se/?cats=1_11~~" +
  "http://www.softonic.com/pocketpc-os~~" +
  "http://www.huffingtonpost.ca/2015/03/25/plentyoffish-spam-fine_n_6939820.html?ir=Canada+Business~~" +
  "http://www.jobs.nih.gov/~~" +
  "http://club.city.sohu.com/zz1112/thread/31yps1048ao?pvid=252850f70ec59d4e~~" +
  "http://dictionary.reference.com/browse/Pneumonoultramicroscopicsilicovolcanoconiosis~~" +
  "http://www.zillow.com/memphis-tn/rent-houses/~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=750&zoneclick=101441~~" +
  "http://www.adobe.com/si/~~" +
  "http://finance.qq.com/a/20150328/021912.htm~~" +
  "http://www.privatehomeclips.com/videos/cute-large-marvelous-woman-asian-mother-i-d-like-to-fuck-lady-blows-my-ding-cock-like-a-sloppy-wench/?pqr=27:4172e1fadc7ff77a9069eccbb6c7e3f5:7:241700:1~~" +
  "http://www.naukri.com/tieups/tieups.php?othersrcp=19766~~" +
  "http://baike.pcbaby.com.cn/qzbd/1655.html~~" +
  "http://www.jabong.com/miaminx/~~" +
  "http://feedburner.google.com/fb/a/mailverify?uri=ettoday/photo&loc=zh_TW~~" +
  "http://px.gmw.cn/~~" +
  "http://baike.pcbaby.com.cn/qzbd/1110073.html~~" +
  "http://product.enet.com.cn/xdp245803.html~~" +
  "http://Wunderground.com/wundermap/?zoom=9&tl.play=0&tl.spd=2&viewportstart=now-3660&viewportend=now-60&groupSevere=0&groupHurricane=0&groupFire=0&groupCamsPhotos=1&groupRealEstate=0&eyedropper=0&extremes=0&fault=0&favs=0&femaflood=0&fire=0&firewfas=0&fissures=0&fronts=0&hurrevac=0&hur=0&labels=0&lightning=0&livesurge=0&mm=0&ndfd=0&rad=0&dir=1&dir.mode=driving&sst=0&sat=0&seismicrisk=0&svr=0&ski=0&snowfall=0&stateLines=0&stormreports=0&tor=0&tfk=0&tsunami=0&riv=0&wxsn=0&cams=1&pix=0&PrecipStart=0~~" +
  "http://yuedu.163.com/ycmm?utm_campaign=163ad&utm_source=163home&utm_medium=tab_0_2_1~~" +
  "http://marketing.hupu.com/matches~~" +
  "http://www.huffingtonpost.ca/british-columbia/~~" +
  "http://js1.eastmoney.com/tg.aspx?ID=346~~" +
  "http://rd.rakuten.co.jp/s/?R2=http%3A%2F%2Faffiliate.rakuten.co.jp%2Fkobo%2F&D2=3.8611.68708.790089.30492188&C3=6dc908c8cfb69819ef2463b8dff36d23a2ddbaa2~~" +
  "http://s.kouclo.com/search.php?c=2082,%E7%AE%B1%E5%8C%85%E9%85%8D%E4%BB%B6~~" +
  "http://www.walmart.com/cp/584291?povid=P1171-C1110.2784+1455.2776+1115.2956-L146~~" +
  "http://Amazon.com/Samsung-Galaxy-S6-Platinum-Sprint/dp/B00V7FWPVO~~" +
  "http://jp.bongacams.com~~" +
  "http://Stackoverflow.com/questions/tagged/codeigniter~~" +
  "http://www.gome.com.cn/category/cat10000230-00-0-36-0-0-0-0-1-0-0-1-0-0-0-0-0-0.html~~" +
  "http://hd.mama.cn/cq/detail/4108936~~" +
  "http://www.xfinity.com/sports/~~" +
  "http://www.bjjubao.org/~~" +
  "http://Slickdeals.net/coupons/newegg/?src=fsw~~" +
  "http://www.tudou.com/listplay/yxM8bGAPFtM/tD39qkbAkNo.html~~" +
  "http://www.newegg.com/Store/RecertifiedStore.aspx?RecertifiedStoreID=32&name=Refurbished-Electronics~~" +
  "http://zjj.58.com/~~" +
  "http://hz.house.ifeng.com/sale/~~" +
  "http://Stackoverflow.com/questions/29314911/ruby-on-rails-loads-yml-file-to-special-json/?lastactivity~~" +
  "https://www.wellsfargo.com/invest_relations/investor_relations/~~" +
  "http://www.alibaba.com/Key-Chains_pid1732~~" +
  "http://g.csdn.net/5282133~~" +
  "http://car.bitauto.com/meiyalucheng/~~" +
  "http://aws.amazon.com/codepipeline/?nc2=h_l3_dm~~" +
  "http://car.bitauto.com/tuan/~~" +
  "http://csm.macrochina.com.cn/~~" +
  "http://www.bitauto.com/zhuanti/bitautotest/yidongpkec7/~~" +
  "http://baike.pcbaby.com.cn/qzbd/1104293.html~~" +
  "http://ref.gamer.com.tw/0000210/*http://user.gamer.com.tw/active/~~" +
  "http://acc.pconline.com.cn/626/6264217.html~~" +
  "http://www.wikipedia.org//ia.wikipedia.org/~~" +
  "https://signmeup.att.com/~~" +
  "http://price.xcar.com.cn/serise1932/city9999-1-1.htm?zoneclick=101425~~" +
  "http://data.auto.qq.com/car_serial/103/~~" +
  "http://entretenimento.uol.com.br/album/2015/03/27/veja-o-ensaio-do-espetaculo-da-companhia-fuerza-bruta-para-o-lollapalooza.htm?abrefoto=21~~" +
  "http://www.mama.cn/ask/jingxuan/1286/~~" +
  "http://www.milliyet.com.tr/seki-den-klipteki-dostlara-tesekkur-magazin-2035273/?ref=OtherNews~~" +
  "http://Codecanyon.net/forums/topic/site-feedback/68~~" +
  "http://www.hxyjw.com/~~" +
  "http://www.vice.com/en_ca/tag/opinion~~" +
  "http://event.rakuten.co.jp/beauty/beasup/~~" +
  "http://weather.media.daum.net/~~" +
  "http://car.bitauto.com/baoshijieboxster/~~" +
  "http://car.bitauto.com/keleiao/~~" +
  "https://www.facebook.com/help/?ref=pf~~" +
  "http://www.goodreads.com/user/show/9184362-mair-ad-is-exploring-a-floating-city~~" +
  "http://s.kouclo.com/search.php?c=24989,%E9%BB%84%E9%85%92~~" +
  "http://s.b5m.com/s/Search?key=%E5%9B%AD%E8%89%BA&isKnn=0~~" +
  "http://bollywood.bhaskar.com/news/ENT-KZHK-viral-video-of-robot-restaurant-4944750-PHO.html~~" +
  "http://vhouse.163.com/photoview/5LTA0029/69271.html~~" +
  "http://spark.csdn.net~~" +
  "http://s.b5m.com/s/Search?key=%E6%89%AB%E6%8F%8F%E4%BB%AA&isKnn=0~~" +
  "http://secure.milliyet.com.tr/redirect/Default.aspx?l=http%3a%2f%2fhavadurumu.milliyet.com.tr&z=42~~" +
  "http://www.homedepot.com/c/Government_Customers~~" +
  "http://www.zillow.com/mortgage-rates/tx/~~" +
  "https://www.xfinitysweepstakes.com?mid=15000113~~" +
  "http://www.icc-cricket.com/cricket-world-cup/mobile-apps~~" +
  "http://www.tripadvisor.com/Hotels-g152515-Cabo_San_Lucas_Los_Cabos_Baja_California-Hotels.html~~" +
  "http://detail.zol.com.cn/cell_phone_index/subcate57_33080_list_1.html~~" +
  "http://mst.pconline.com.cn/616/6166416.html~~" +
  "http://man.39.net/nxsh/nxshyp/~~" +
  "http://ask.ci123.com/users/show/22380882~~" +
  "http://www.irs.gov/News-&-Events~~" +
  "http://news.xinhuanet.com/house/bj/2015-03-27/c_1114778659.htm~~" +
  "http://www1.pclady.com.cn/star/sweet62/index.html~~" +
  "http://www.aliexpress.com/category/200003604/backpacks-carriers.html~~" +
  "http://www.teepr.com/category/%e7%94%9f%e6%b4%bb/%e9%a3%9f%e7%89%a9/~~" +
  "http://newcar.xcar.com.cn/photo/ps10/?zoneclick=101441~~" +
  "http://prom.gome.com.cn/html/prodhtml/topics/201502/20150202031156_topics.html~~" +
  "http://www.buzzfeed.com/connordunlap/which-paper-mario-the-thousand-year-door-sideki-x669~~" +
  "http://www.shiksha.com/~~" +
  "http://voice.hupu.com/soccer/1895716.html~~" +
  "https://zhaocaibao.alipay.com~~" +
  "http://s.b5m.com/s/Search?key=%E7%9B%B8%E6%9C%BA%E7%94%B5%E6%B1%A0&isKnn=0~~" +
  "http://widowed.about.com~~" +
  "http://www.zol.com/detail/digital_camera/Samsung/8015881.html~~" +
  "http://brandbase.mama.cn/topfer.php?mod=home~~" +
  "http://www.tudou.com/programs/view/9s1IKXHBmZc/~~" +
  "http://dl.pconline.com.cn/download/118325.html~~" +
  "http://www.taoche.com/tiguan/~~" +
  "http://www.bild.de/bundesliga/1-liga/1-fc-koeln-30674938.bild.html~~" +
  "http://www.buzzfeed.com/kimberleydadds/zayn-malik-has-quit-one-direction~~" +
  "https://www.scribd.com/mobile?remobile=1~~" +
  "http://www.windowsphone.com/en-us/store/app/quikr-buy-sell/6d36aa77-19a0-4adc-af15-0496dcc05557~~" +
  "http://brasil.elpais.com/brasil/2015/03/26/internacional/1427361510_719172.html~~" +
  "http://auto.china.com/zhuanzai/daogou/11162371/20150327/19432524.html~~" +
  "http://www.bbc.com/autos/~~" +
  "http://bleacherreport.com/articles/2407974-winston-mariota-could-be-the-next-manning-leaf~~" +
  "http://www.wordreference.com/de/~~" +
  "http://Privatehomeclips.com/community/~~" +
  "http://torrentz.com~~" +
  "http://network.pconline.com.cn/625/6255496.html~~" +
  "https://plus.google.com/108349337900676782287~~" +
  "http://www.forbes.pl/~~" +
  "http://xfinitytv.comcast.net/live/network/History?cmpid=FCST_livemod_history~~" +
  "http://www.he.xinhuanet.com/zfwq/qinhuangdao/~~" +
  "http://www.nyaa.se/?page=download&tid=671020~~" +
  "http://taizhou.58.com/~~" +
  "http://baike.pcbaby.com.cn/qzbd/950917.html~~" +
  "http://Xe.com/ja/~~" +
  "http://forum.xda-developers.com/usertag.php?do=profilenotif&tab=mentions~~" +
  "http://www.enet.com.cn/edigi/atlist0_%C4%E1%BF%B5.html~~" +
  "http://product.pconline.com.cn/flash/~~" +
  "https://Eksisozluk.com/diego-armando-maradona-vs-lionel-messi--2364072?a=popular~~" +
  "http://car.bitauto.com/biaozhi508/~~" +
  "http://www.bitauto.com/quzhou/~~" +
  "https://archive.org/details/78rpm~~" +
  "http://baby.qq.com/xuexiao/index.htm~~" +
  "http://jr.naver.com~~" +
  "http://a.163.com/special/blzreview04/~~" +
  "http://baike.pcbaby.com.cn/qzbd/11949.html~~" +
  "http://pp.pcbaby.com.cn/photo/25655.html~~" +
  "http://www.newegg.com/Travel-Ticket/Category/ID-393~~" +
  "http://www.csdn.net/tag/html~~" +
  "http://www.csdn.net/tag/rackspace~~" +
  "http://korea.b5m.com/article-79841-1.html~~" +
  "http://homeloanhelp.bankofamerica.com/en/doj-settlement.html~~" +
  "http://www.dailymotion.com/PornWithoutThePorn~~" +
  "http://www.nba.com/spurs?ls=iref:nba:gnav~~" +
  "http://www.theverge.com/community-guidelines~~" +
  "http://www.indiatimes.com/news/india/beef-festivals-to-fight-against-beefban-hows-that-for-a-protest-231355.html~~" +
  "http://news.qq.com/a/20150328/005467.htm?tu_biz=v1~~" +
  "http://www.washingtonpost.com/gog/?nid=top_gog~~" +
  "http://Stackoverflow.com/questions/29314914/bash-pipe-output-into-a-table~~" +
  "http://www.douban.com/location/canada/events/week-1103~~" +
  "http://www.enet.com.cn/emobile/atlist0_%C1%AA%CF%EB.html~~" +
  "http://ad.doubleclick.net/ddm/clk/279015201;106198934;d?http://ad.doubleclick.net/clk;277169730;104577821;m?http://leaseweb.com/en?utm_source=XDA-developers.com&utm_medium=online&utm_content=various&utm_campaign=*Linkback~~" +
  "http://Ppomppu.co.kr/zboard/view.php?id=help&no=1046315~~" +
  "http://ok.ru/messages~~" +
  "http://ch.nicovideo.jp/anime-campaign~~" +
  "http://s.b5m.com/item/ab8f726d9c06c625ad4932951dd91bb9.html~~" +
  "http://fitness.39.net/jfsp/115/18/1235042.html~~" +
  "http://fitness.39.net/a/150328/4597977.html~~" +
  "http://Stackoverflow.com/questions/29314984/searching-for-subdocument-in-elastic-search~~" +
  "http://ent.163.com/photo/~~" +
  "http://www.telekom.com/karriere~~" +
  "http://www.fedex.com/bg/~~" +
  "http://open.spotify.com/user/spotify/playlist/7CQunpJEHecknIyABfS8pP~~" +
  "http://sn.ifeng.com/special/xijuri/~~" +
  "http://www.jabong.com/vero-moda/~~" +
  "http://www.naukri.com/tieups/tieups.php?othersrcp=15009~~" +
  "https://www.wellsfargo.com/the-private-bank/connect/~~" +
  "http://www.ekoktea.com/~~" +
  "http://car.bitauto.com/tianmayingxiong/~~" +
  "http://Ettoday.net/news/20120515/46700.htm?from=sidebar_mostlike~~" +
  "http://www.igeek.com.cn/video/~~" +
  "http://baike.pcbaby.com.cn/qzbd/953650.html~~" +
  "http://prom.gome.com.cn/html/prodhtml/topics/201503/24/xpclxd.html~~" +
  "http://cul.sina.com.cn/~~" +
  "http://elpais.com/economia/2015/03/27/actualidad/1427493628_853511.html~~" +
  "http://baike.pcbaby.com.cn/qzbd/1123337.html~~" +
  "http://cafe.daum.net/baseballsale~~" +
  "http://Moz.com/local~~" +
  "http://notebook.pconline.com.cn/626/6264417.html~~" +
  "http://newcar.xcar.com.cn/283/?zoneclick=101448~~" +
  "http://newcar.xcar.com.cn/2546/?zoneclick=101421~~" +
  "http://www.slideshare.net/featured/category/government-nonprofit~~" +
  "http://routenplaner.t-online.de/~~" +
  "http://ref.gamer.com.tw/0000161/*http://gnn.gamer.com.tw/1/112771.html~~" +
  "https://www.elance.com/ecommerce-programmers-jobs/714~~" +
  "http://sports.media.daum.net/sports/baseball/?selectedNewsId=20150328165909389~~" +
  "http://www.gome.com.cn/category/cat10000058-00-0-48-1-0-0-0-1-1avD-0-1-0-0-0-0-0-0.html~~" +
  "http://s.taobao.com/search?q=%E6%94%B6%E9%9F%B3%E6%A9%9F&js=1&stats_click=search_radio_all%253A1&initiative_id=staobaoz_20150126&cps=yes&cat=50019665~~" +
  "http://www.bitauto.com/ankang/~~" +
  "http://baike.pcbaby.com.cn/qzbd/607.html~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1214~~" +
  "http://Amazon.com/gp/seller-account/mm-summary-page.html?ie=UTF8&ld=AZFooterSelfPublish&topic=200260520~~" +
  "http://www.alibaba.com/Paper-Crafts_pid1715~~" +
  "http://www.wikipedia.org//arc.wikipedia.org/~~" +
  "https://coupon.rakuten.co.jp/myCoupon/%E6%A5%BD%E5%A4%A9%E5%B8%82%E5%A0%B4~~" +
  "https://img.godaddy.com/redirect.aspx/?target=https%3A%2F%2Fplus.google.com%2F108306343581548568740~~" +
  "http://www.pcauto.com.cn/nation/613/6132439.html~~" +
  "http://www.slideshare.net/PhilipPowers1/morgan-logic~~" +
  "http://www.cbssports.com/fantasy/baseball/games/commissioner?ttag=FBBC15_glbnav~~" +
  "https://www.odesk.com/o/freelancer-skills/~~" +
  "http://money.bhaskar.com/market/?Menu-Mar~~" +
  "http://servicios.elpais.com/dispositivos/tabletas/ipad/~~" +
  "http://fashion.huanqiu.com/news/2015-03/6024306.html~~" +
  "http://sociology.about.com~~" +
  "http://www.nytimes.com/2015/03/29/travel/searching-for-evan-connells-bohemian-sausalito.html~~" +
  "http://www.newegg.com/Store/StandaloneSNET.aspx?name=Warranty-Store~~" +
  "http://www.zillow.com/digs/~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1008~~" +
  "http://ranking.goo.ne.jp/column/article/955/~~" +
  "http://Ettoday.net/news/20120521/48143.htm~~" +
  "http://product.pconline.com.cn/mobile/c10647/~~" +
  "http://www.engadget.com/register/~~" +
  "http://fashion.pconline.com.cn/article_photo/14178.html~~" +
  "http://techgnotic.deviantart.com/journal/Project-Porkchop-Vol-380-519306370~~" +
  "http://bari.corriere.it~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=909~~" +
  "http://v.tudou.com/kpoplive/~~" +
  "http://Ppomppu.co.kr/zboard/view.php?id=hotissue&no=4653~~" +
  "https://office.live.com/start/Word.aspx?WT.mc_id=O16_BingHP~~" +
  "http://xyk.xywy.com/~~" +
  "http://www.ebay.be~~" +
  "http://ent.qq.com/a/20150327/073478.htm?tu_biz=1.33.1.0&tu_p=6&tu_b=0~~" +
  "http://detail.zol.com.cn/icebox/~~" +
  "http://Kouclo.com/usercenter_order/my_order/no_pay~~" +
  "http://www.npr.org/services/mobile/iphone-music.php~~" +
  "http://www.flipkart.com/s/terms~~" +
  "http://market.ltn.com.tw/news.php?no=150~~" +
  "http://time.com/3748244/viagra-history/~~" +
  "http://news.livedoor.com/topics/detail/9942640/~~" +
  "http://newcar.xcar.com.cn/2523/~~" +
  "http://bbs.hupu.com/12304419.html~~" +
  "http://bbs.zol.com.cn/huodong/d2_24631.html~~" +
  "http://www.goodreads.com/choiceawards/best-science-fiction-books-2014~~" +
  "http://www.walmart.com/cp/1094926?povid=P1171-C1086.5062-L8~~" +
  "http://ask.ci123.com/users/show/22457114~~" +
  "http://ent.ltn.com.tw/news/breakingnews/1270456~~" +
  "http://www.theguardian.com/guardian-masterclasses?INTCMP=NGW_TOPNAV_UK_GU_MASTERCLASSES~~" +
  "http://slide.news.sina.com.cn/c/slide_1_2841_82695.html~~" +
  "http://mashable.com/2015/03/25/us-airstrikes-target-tikrit/~~" +
  "http://bbs.hupu.com/game~~" +
  "http://www.cnn.com/2015/03/27/opinions/garrison-germanwings-crash/index.html~~" +
  "http://Php.net/contact.php~~" +
  "http://s.b5m.com/s/Search?key=%E8%BF%9B%E5%8F%A3&isKnn=0~~" +
  "http://udn.com/news/cate/6643~~" +
  "http://www.bitauto.com/shuangyashan/~~" +
  "http://www.ign.com/videos/2015/03/27/bloodborne-review~~" +
  "http://event.rakuten.co.jp/household/~~" +
  "http://www.nytimes.com/2015/03/29/travel/in-the-hills-of-sri-lankas-tea-country.html?hp&target=comments~~" +
  "http://stock.eastmoney.com/hangye/hy448.html~~" +
  "http://www.enet.com.cn/solution/aklist0_%CB%F3%D7%D3%D3%E3.html~~" +
  "http://renshi.people.com.cn/n/2015/0327/c368940-26761527.html~~" +
  "http://www.snapdeal.com/products/mens-footwear-formal-shoes?sort=plrty~~" +
  "http://Themeforest.net/item/geometry-interior-design-furniture-wordpress-theme/10895776~~" +
  "http://www.espncricinfo.com/ci/content/video_audio/index.html?genre=27~~" +
  "http://www.newegg.com/Gaming/Store~~" +
  "http://newcar.xcar.com.cn/387/?zoneclick=101413~~" +
  "http://shiyan.ganji.com/~~" +
  "http://braininitiative.nih.gov/~~" +
  "http://blog.hootsuite.com/?icn=primtopnav&ici=Blog~~" +
  "http://travel.163.com/special/privatesharing026/~~" +
  "http://www.iqiyi.com/dongman/bangumi.html~~" +
  "http://www.washingtonpost.com/james-wagner/2011/05/05/AFxWMwAG_page.html~~" +
  "http://www.chinabyte.com~~" +
  "http://net.it168.com/~~" +
  "http://brides.pclady.com.cn/~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1324~~" +
  "http://bollywood.bhaskar.com/news-ht/ENT-BNE-anushka-sharma-and-virat-kohli-return-from-sydney-together-4946415-NOR.html~~" +
  "http://free-youtube-download.uptodown.com~~" +
  "http://www.dailymail.co.uk/news/article-3014529/Wife-loses-2million-divorce-battle-business-tycoon-ex-husband-worth-38m-signed-post-nup-agreement.html~~" +
  "http://billiards.about.com~~" +
  "http://www.salesforce.com/communities/overview/~~" +
  "http://www.bhaskar.com/news-hf/RAJ-UDA-brave-man-story-of-rajasthan-4944958-PHO.html~~" +
  "http://bollywood.bhaskar.com/news/ENT-TV-famous-tv-actresses-caught-and-clicked-without-make-up-4934073-PHO.html~~" +
  "http://corp.bankofamerica.com/business/bi/home~~" +
  "http://www.snapdeal.com/brand/tupperware/home-kitchen~~" +
  "http://heavyrider.corriere.it/2015/03/26/motogp-la-sfida-arrogante-di-apriliatest-pazienza-e-lincognita-melandri/~~" +
  "http://lady.163.com/photoview/513O0026/81390.html~~" +
  "http://blog.eastmoney.com/cfm163163~~" +
  "http://www.dmm.com/rental/iroiro/~~" +
  "http://music.douban.com/programme/1373403~~" +
  "http://www.ci123.com/apps/?t=3~~" +
  "http://baike.pcbaby.com.cn/qzbd/1129954.html~~" +
  "http://baike.pcbaby.com.cn/qzbd/950898.html~~" +
  "http://swappa.com/sell/~~" +
  "http://www.marca.com/tag/Dani_Pedrosa/~~" +
  "http://yao.xywy.com/jibing/158.htm~~" +
  "http://price.xcar.com.cn/serise1611/city9999-1-1.htm?zoneclick=101433~~" +
  "http://www.dailymail.co.uk/travel/article-2972302/Big-brash-beautiful-captivating-water-world-middle-desert-one-Kim-Kardashian-s-favourite-luxury-hotels.html~~" +
  "http://iquantny.tumblr.com/~~" +
  "http://rs.ci123.com/video/item_2258.html~~" +
  "http://www.foxnews.com/travel/index.html~~" +
  "http://www.mobile.de/auto-verkaufen~~" +
  "http://www.theguardian.com/global-development~~" +
  "http://conference.caijing.com.cn/~~" +
  "http://www.china.com/zh_cn/licence/2.html~~" +
  "http://www.trulia.com/listings_quality_policy/~~" +
  "http://bbs.pcbaby.com.cn/topic-2275289.html~~" +
  "http://jbk.39.net/gxy/zztz/~~" +
  "http://baike.pcbaby.com.cn/qzbd/1105914.html~~" +
  "http://www.rakuten.co.uk/?scid=wi_jpn_topflag~~" +
  "http://www.imdb.com/news/movie?ref_=hm_nw_sm~~" +
  "http://voice.hupu.com/nba/1895718.html~~" +
  "http://www.forbes.com/sites/steveolenski/2015/03/27/5-tips-for-an-effective-mobile-content-marketing-strategy/~~" +
  "http://www.chinatimes.com/mainland/260514~~" +
  "http://www2.macleans.ca/category/opinion/barbara-amiel-opinion/~~" +
  "http://nj.house.ifeng.com/column/dujiacehua/loushitaodiandian~~" +
  "http://Themeforest.net/forums/topic/all-marketplaces/47~~" +
  "http://www.weather.com/science~~" +
  "http://www.marca.com/2015/03/27/baloncesto/nba/noticias/1427485660.html~~" +
  "http://product.pchome.net/digi_home_lcd_tv_lg_lg55ub8300cg/425922.html~~" +
  "http://detail.zol.com.cn/projector_stand/~~" +
  "http://www.gdis.cn/admin/newstext.asp?id=137~~" +
  "http://www.slideshare.net/directory/user/f~~" +
  "http://edm.it168.com/~~" +
  "http://v.17173.com/v_1_121/MjI2MjU1MTg.html?vid=sohusy_db~~" +
  "http://news.yandex.ru/yandsearch?cl4url=www.20khvylyn.com/news/politics/news_13674.html&lang=ru&lr=20806~~" +
  "http://www.avg.com/ca-en/for-mobile?icid=ws-nav-ios~~" +
  "http://eurosport.onet.pl/pilka-nozna/kadra/martin-o-neill-polacy-nabrali-pewnosci-siebie/vh63qq~~" +
  "http://s.taobao.com/search?q=%C6%BD%B0%E5%EB%8A%D2%95&commend=all&ssid=s5-e&search_type=item&sourceId=tb.index&spm=1.7274553.1997520841.1&initiative_id=tbindexz_20150126~~" +
  "http://club.china.com/data/thread/1011/2777/10/57/6_1.html~~" +
  "http://www.infusionsoft.com/extras~~" +
  "http://www.foxnews.com//foxnewsinsider.com/~~" +
  "http://www.china.com/zh_cn/general/legal.html~~" +
  "http://v.qq.com/p/tv/detail/highschool/index.html~~" +
  "http://product.pconline.com.cn/notebook/acer/~~" +
  "http://jbk.39.net/zhengzhuang/hbypz/~~" +
  "http://www.naukri.com/tieups/tieups.php?othersrcp=17670~~" +
  "http://www.washingtonpost.com/entertainment/music/emerson-quartet-inspires-affection-which-it-needed-thursday-night/2015/03/27/9d009940-d49b-11e4-a62f-ee745911a4ff_story.html?tid=hpModule_5fb4f58a-8a7a-11e2-98d9-3012c1cd8d1e~~" +
  "http://www.onpointradio.org/~~" +
  "http://Hdfcbank.com/personal/making-payments/tax-payment/online-payment-of-taxes-to-the-pune-municipal-corporation~~" +
  "http://www.tmz.com/2015/03/06/madonna-home-tel-aviv-penthouse-condo/~~" +
  "http://gz.house.163.com/15/0327/17/ALNSHQ0T00873CN0.html~~" +
  "http://www.aliexpress.com/category/200003482/dresses.html?g=y&pvId=326-200001280~~" +
  "http://www.about.com/gi/pages/printrequests.html~~" +
  "http://hanbo.ci123.com~~" +
  "http://pad.pconline.com.cn/620/6209981.html~~" +
  "http://baike.pcbaby.com.cn/qzbd/1110876.html~~" +
  "http://www.autohome.com.cn/youji/11-104-1-1/~~" +
  "http://money.bhaskar.com/news/MON-BIZN-TRAD-small-firms-shift-to-computer-for-accounting-work-4944804-NOR.html~~" +
  "http://kakaku.com/nisa/~~" +
  "http://encyclopedia2.thefreedictionary.com/~~" +
  "http://down.chinaz.com/soft/27227.htm~~" +
  "http://bola.liputan6.com/read/2198555/cetak-gol-perdana-harry-kane-masuk-buku-rekor~~" +
  "http://down.chinaz.com/class/101_1.htm~~" +
  "http://www.foxnews.com//www.foxnews.com/trending/~~" +
  "http://club.china.com/baijiaping/gundong/11141903/20150313/19376763.html~~" +
  "http://renwu.eastmoney.com/Renwu.aspx?r=langxianping~~" +
  "http://www.marca.com/2015/03/21/futbol/2adivision/1426970255.html~~" +
  "http://sk.bongacams.com~~" +
  "http://blog.csdn.net/guolin_blog/article/details/42238627~~" +
  "http://student.csdn.net~~" +
  "http://www.cbssports.com/fantasy/football/games/franchise/2014?ttag=FRFB14_on_cspt_glbnav_0001~~" +
  "http://s.kouclo.com/search.php?c=2017,%E5%B8%86%E5%B8%83%E9%9E%8B~~" +
  "http://www.woot.com/plus/source-green-heaters-via-lifesmart?ref=cnt_wp_10~~" +
  "http://t.people.com.cn/talksV3/0-33.html~~" +
  "http://Shutterstock.com/contactus~~" +
  "http://newcar.xcar.com.cn/152/?zoneclick=101425~~" +
  "http://home.woot.com/plus/bedding-for-the-boys-1?ref=gh_hm_4_wp_8~~" +
  "http://k.autohome.com.cn/spec/15308/~~" +
  "http://www.constantcontact.com/site/au.jsp?src=/index.jsp~~" +
  "https://aws.amazon.com/marketplace/search/results/ref=mkt_ste_l2_gaming?page=1&searchTerms=gaming&nc2=h_l3_g~~" +
  "http://www.aliexpress.com/category/5090301/mobile-phones.html?pvId=200000791-200003799~~" +
  "http://present.goo.ne.jp/~~" +
  "http://www.groupon.com//www.groupon.com/deals/gg-ca-creacore-creatine-powder~~" +
  "http://h17007.www1.hp.com/us/en/networking/products/switches/index.aspx~~" +
  "http://Kickass.to/grimm-s04e15-hdtv-x264-lol-ettv-t10417023.html~~" +
  "http://www.kaskus.co.id/forum/540/?ref=homelanding&med=forum_categories~~" +
  "http://ego.globo.com/biquini/noticia/2015/03/que-saude-fiorella-mattheis-filma-longa-de-biquini-na-orla-do-rio.html~~" +
  "http://news.sina.com.cn/pc/2014-10-30/326/3095.html~~" +
  "http://www.snapdeal.com/info/copyrightPolicy~~" +
  "http://car.bitauto.com/brillianceauto/~~" +
  "http://car.bitauto.com/linkenmkt-3614/~~" +
  "http://s.b5m.com/s/Search?key=%E7%83%9F%E6%9C%BA%E7%81%B6%E5%85%B7&isKnn=0~~" +
  "http://v.17173.com/v_4_40000008/MjI2NDI1MjA.html?vid=sohusy_db~~" +
  "http://yinchuan.bitauto.com/~~" +
  "http://zt.pchouse.com.cn/70/700091.html~~" +
  "http://www.kufar.by/~~" +
  "http://www.washingtonpost.com/blogs/federal-eye/wp/2015/03/27/does-the-u-s-postal-service-have-an-unfair-competitive-advantage/?tid=hpModule_308f7142-9199-11e2-bdea-e32ad90da239~~" +
  "http://www.washingtonpost.com/sports/othersports~~" +
  "https://my.eu.samsung.com/ca/product/register~~" +
  "http://www.businessinsider.com/life-plan~~" +
  "https://www.popads.net/publishers.html~~" +
  "http://www.wikipedia.org//sq.wikipedia.org/~~" +
  "http://bbs.pcauto.com.cn/~~" +
  "http://voice.hupu.com/china/1895514.html~~" +
  "http://www.tudou.com/albumplay/UO6nV_eXt4A.html~~" +
  "http://baby.tmall.com/?acm=tt-1141518-37003.1003.8.75997&uuid=75997&abtest=&scm=1003.8.tt-1141518-37003.OTHER_1417452215905_75997&pos=3~~" +
  "http://car.autohome.com.cn/price/brand-15.html~~" +
  "http://www.cbsfilms.com~~" +
  "http://Kickass.to/rick-wakeman-the-myths-and-legends-of-king-arthur-and-the-knights-of-the-round-table-cd-dvd-a-deluxe-2015-flac-t10406708.html~~" +
  "http://bbs.gmw.cn/thread-3291160-1-1.html~~" +
  "http://house.163.com/special/house_buy_ip_auto/~~" +
  "http://www.fedex.com/de/~~" +
  "http://detail.zol.com.cn/lcd/acer/~~" +
  "http://event.udn.com/line/~~" +
  "http://product.pchome.net/mobile_phone_samsung_galaxya94g/437006.html~~" +
  "https://www.odesk.com/o/profiles/browse/c1/it-networking/~~" +
  "http://www.teepr.com/category/%e8%a1%a8%e6%bc%94/%e9%9f%b3%e6%a8%82/~~" +
  "http://prom.gome.com.cn/html/prodhtml/topics/201410/weidazhuanti.html~~" +
  "http://www.baike.com/wiki/LG~~" +
  "http://car.bitauto.com/maserati/~~" +
  "http://v.17173.com/v_102_601/MjI0NzU5Mzk.html?vid=sohusy_db~~" +
  "http://Ettoday.net/news/20120521/48051.htm~~" +
  "http://www.tudou.com/listplay/_4ubSo04RRQ/g4z37p4W6Tc.html~~" +
  "http://prom.gome.com.cn/html/prodhtml/topics/201410/haman.html?cmpid=pro-jiadian-sjsm-TX110002~~" +
  "http://www.emagister.com/landing/main/?pfichas=6153&sid=27&utm_source=elpais&utm_medium=cpc&utm_content=mini_logo~~" +
  "http://mulher.uol.com.br/horoscopo/peixes/previsao-diaria/~~" +
  "http://www.bitauto.com/shuozhou/~~" +
  "http://bleacherreport.com/the-lineup~~" +
  "http://tejia.b5m.com/brand/detail/2001892~~" +
  "http://www.nascar.com/en_us/sprint-cup-series.html?cid=syn_cbs_referrers_navlinks_01112013&synid=syn_cbs_referrers_navlinks_01112013~~" +
  "http://headphone.zol.com.cn/513/5131681.html~~" +
  "http://www.salesforce.com/ca/crm/editions-pricing.jsp?d=70130000000ryrr~~" +
  "http://www.bild.de/lifestyle/mode-beauty/outfit-of-the-week/fruehlings-look-ootw-40317566.bild.html~~" +
  "http://www.buzzfeed.com/rachelzarrell~~" +
  "http://fi.yelp.fi/sf~~" +
  "http://guoqing.china.com.cn/node_7182589.htm~~" +
  "http://www.8684.cn~~" +
  "http://s.kouclo.com/search.php?c=63,%E5%85%89%E7%BA%A4%E8%AE%BE%E5%A4%87~~" +
  "http://www.ddh.gov.cn~~" +
  "http://www.sinasy.com.cn/~~" +
  "http://www.seznam.cz/jsTitleExecute?id=328&h=34759639~~" +
  "http://www.cnet.com/videos/samsung-galaxy-s6-and-s6-edge-whats-the-difference/~~" +
  "http://newcar.xcar.com.cn/photo/ps642/?zoneclick=101438~~" +
  "http://new.livejasmin.com/en/awards/periodic?utm_content=awardsModels&session=g13ca65df7ee4cd0d8dbb8d6d5659c89c~~" +
  "http://prom.gome.com.cn/html/prodhtml/topics/201406/20140605113310_topics.html~~" +
  "http://bola.kompas.com/ligalain~~" +
  "http://www.iqiyi.com/v_19rrnnp9jg.html~~" +
  "http://www.tripadvisor.com/Hotels-g1435792-Pensacola_Beach_Florida-Hotels.html~~" +
  "http://www.alibaba.com/Power-Distribution-Equipment_pid4105~~" +
  "http://club.xywy.com/askquestion.php?did=25532515~~" +
  "http://gift.rakuten.co.jp/~~" +
  "http://bbs1.people.com.cn/post/1/1/2/146160495.html~~" +
  "http://goodtimes.ndtv.com/video/videolist.aspx?vid=361261&CategoryKeyword=&page=1&id=0&pfrom=home-goodtimes~~" +
  "http://fuwu.sogou.com/?sohu=wangzhandenglu~~" +
  "http://newcar.xcar.com.cn/photo/ps1932/?zoneclick=101425~~" +
  "http://state.it168.com/~~" +
  "http://kakaku.com/reform/~~" +
  "http://news.xinhuanet.com/fortune/2015-03/28/c_127631262.htm~~" +
  "http://www.buzzfeed.com/juliegerstein~~" +
  "http://v.163.com/zixun/V8GAM8VMO/VAKP041SN.html~~" +
  "http://blog.caijing.com.cn/chenyongdong~~" +
  "http://dangjian.gmw.cn/node_60548.htm~~" +
  "http://news.xinhuanet.com/edu/2015-03/28/c_127630922.htm~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=349~~" +
  "http://sports.163.com/15/0328/10/ALPPD84F00051CA1.html~~" +
  "http://www.deviantart.com/tag/concerts~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1374~~" +
  "https://reps.mozilla.org/e/hackathon-miage-gi-firefox-club/~~" +
  "http://titan.babytree.com/delivery/ck.php?n=a2c9bd94&cb=8522~~" +
  "http://jx.ifeng.com~~" +
  "http://my.xcar.com.cn/space.php?uid=8776049~~" +
  "http://instagram.com/wired/~~" +
  "http://www.baike.com/shouye/zhuanjia/guwen.html~~" +
  "http://panicdisorder.about.com~~" +
  "http://www.cngba.com~~" +
  "http://energy.people.com.cn/~~" +
  "http://www.flipkart.com/home-entertainment/tvs/micromax~brand/pr?sid=ckf%2Cczl~~" +
  "http://www.mama.cn/z/18007/~~" +
  "http://www.cricbuzz.com/cricket-scorecard/14686/karnataka-vs-tn-south-zone-syed-mushtaq-ali-trophy-2015~~" +
  "http://comic.people.com.cn/n/2015/0327/c122366-26758103.html~~" +
  "http://www.ebay.com.au~~" +
  "http://ek.39.net/a/150328/4598045.html~~" +
  "http://Ppomppu.co.kr/zboard/view.php?id=shopping&no=6206&search_type=name&keyword=~~" +
  "http://s.b5m.com/s/Search?key=%E9%B8%BF%E6%98%9F%E5%B0%94%E5%85%8B~~" +
  "http://www.wikipedia.org//ne.wikipedia.org/~~" +
  "http://detail.zol.com.cn/server/sugon/~~" +
  "http://club.xywy.com/small_303.htm~~" +
  "http://www.theverge.com/video/reviews~~" +
  "http://www.controlledreleasesociety.org/Pages/default.aspx~~" +
  "http://prom.gome.com.cn/html/prodhtml/topics/201503/qczxxsgcjjj.html?intcmp=sy-C-3-2-4-yb~~" +
  "http://baike.pcbaby.com.cn/qzbd/1146339.html~~" +
  "http://car.bitauto.com/junjiecross/~~" +
  "http://www.babytree.com/ask/detail/14927586~~" +
  "http://bbs.zol.com.cn/diybbs/d540.html~~" +
  "http://www.zillow.com/jacksonville-fl/~~" +
  "http://shincomicbook.lofter.com/post/1d13b1d8_65ace4c?act=qbwysylofer_20150101_01~~" +
  "http://dl.pconline.com.cn/download/54091.html~~" +
  "http://www.snapdeal.com/products/lifestyle-watches?q=Occasion_s:Branded%20Watches&~~" +
  "http://Kickass.to/music/?rss=1~~" +
  "http://Hdfcbank.com/htdocs/common/generate_pin/create_pin.html~~" +
  "http://newcar.xcar.com.cn/photo/ps1932/?zoneclick=101430~~" +
  "http://www.cnet.com/products/xiaomi-yi/~~" +
  "http://www.wikipedia.org//pfl.wikipedia.org/~~" +
  "http://www.sahibinden.com/ozel-ders-verenler~~" +
  "https://www.chase.com/home-equity/home-equity-line-of-credit-calculator~~" +
  "http://www.mama.cn/z/126/~~" +
  "http://baike.pcbaby.com.cn/qzbd/952099.html~~" +
  "http://tv.people.com.cn/GB/387285/index1.html~~" +
  "http://espn.go.com/college-football/recruiting/~~" +
  "http://shipin.people.com.cn/n/2015/0327/c85914-26762266.html~~" +
  "http://www.nyaa.se/?page=download&tid=671041~~" +
  "http://special.goo.ne.jp/~~" +
  "http://accessories.us.dell.com/sna/category.aspx?c=us&category_id=5436&l=en&s=dhs&~ck=mn~~" +
  "http://www.tripadvisor.com/ShowUrl-a_partnerKey.1-a_url.http%253A__5F____5F__2F__5F____5F____5F____5F__2F__5F____5F__www__5F____5F__2E__5F____5F__facebook__5F____5F__2E__5F____5F__com__5F____5F__2F__5F____5F__TripAdvisor-a_urlKey.15090f72418302936-p15194.html~~" +
  "http://xiazai.zol.com.cn/~~" +
  "http://ftx2.hupu.com/~~" +
  "http://www.yelp.com/search?l=p%3ACA%3ASan_Francisco%3A%3ABayview-Hunters_Point~~" +
  "http://product.pchome.net/digi_home_lcd_tv_sharp_lcd50u1a/421062.html~~" +
  "http://www.washingtonpost.com/cars~~" +
  "https://www.wellsfargo.com/wfonline/~~" +
  "http://v.opahnet.com/nba/v741237.html~~" +
  "http://mail.163.com/index.htm~~" +
  "http://s.b5m.com/s/Search?key=%E5%B7%A6%E6%97%8B%E8%82%89%E7%A2%B1&isKnn=0~~" +
  "http://www.gome.com.cn/category/cat16035631.html~~" +
  "http://stackoverflow.com~~" +
  "http://s.b5m.com/s/Search?key=%E6%91%84%E5%83%8F%E6%9C%BA&isKnn=0~~" +
  "http://Kickass.to/user/The.Wolf/~~" +
  "http://www.bild.de/community/ugc/40323730~~" +
  "http://www.tmz.com/photos/2014/09/25/whod-you-rather-celebrity-photos/?adid=sidebar-promo-rather-get-hard~~" +
  "http://time.com/~~" +
  "http://hurarsiv.hurriyet.com.tr/~~" +
  "http://about.constantcontact.com/contact~~" +
  "http://www.uptodown.com/buscar/google-chrome~~" +
  "https://infinity.icicibank.com/corp/AuthenticationController?FORMSGROUP_ID__=AuthenticationFG&__START_TRAN_FLAG__=Y&__EVENT_ID__=LOAD&__CALL_MODE__=91&LOGIN_FLAG=1&BANK_ID=ICI~~" +
  "http://mil.qq.com/~~" +
  "http://www.telegraph.co.uk/news/uknews/crime/11500973/Fraudster-escapes-from-one-of-Britains-most-secure-prisons-by-forging-letter-granting-him-bail.html~~" +
  "http://www.milliyet.com.tr/dekorasyon/?ref=milliyet_anasayfa~~" +
  "http://www.goodreads.com/help~~" +
  "http://www.caijing.com.cn/subscription/~~" +
  "http://www.walmart.com/browse/Jewelry-Cases/_/N-3xo4Zaq90Zaqce/Ne-2p4k?amp%3Bic=48_0&amp%3Bref=125876.183604&amp%3Btab_value=10874_All&catNavId=3891&povid=P1171-C1110.2784+1455.2776+1115.2956-L179~~" +
  "http://www.google.ca/advanced_search?hl=en-CA&authuser=0~~" +
  "http://news.kakaku.com/prdnews/rss.asp~~" +
  "http://racing.hupu.com/~~" +
  "http://news.china.com.cn/hssczl/node_7219532.htm~~" +
  "http://www.yelp.com/sm/san-francisco-ca-us/k~~" +
  "http://encyclopedia2.thefreedictionary.com~~" +
  "http://hanjianbing.baike.com/article-1655369.html?prd=shouye_guancha~~" +
  "http://movies.ndtv.com/bollywood/anushka-sharma-virat-kohli-touch-down-in-mumbai-hand-in-hand-750317?utm_source=ndtv&utm_medium=top-stories-widget&utm_campaign=story-17-http%3a%2f%2fmovies.ndtv.com%2fbollywood%2fanushka-sharma-virat-kohli-touch-down-in-mumbai-hand-in-hand-750317~~" +
  "http://tag.lady8844.com/1262294/~~" +
  "http://money.163.com/15/0328/00/ALON5AF800253B0H.html~~" +
  "http://tv.liputan6.com/kategori/liputan6-siang~~" +
  "http://titan.babytree.com/delivery/ck.php?n=ad100e9c&cb=4644~~" +
  "http://Themeforest.net/page/top_new_sellers~~" +
  "http://news.china.com/~~" +
  "http://baike.pcbaby.com.cn/qzbd/950920.html~~" +
  "http://electronics.woot.com/?ref=cnt_ft_el_2~~" +
  "http://www.cnn.com/specials/opinion/opinion-social-issues~~" +
  "http://channel.jd.com/furniture.html~~" +
  "http://Ppomppu.co.kr/recent_main_article.php~~" +
  "http://info.xcar.com.cn/list/837/~~" +
  "http://view.news.qq.com/index/zhuanti/zt_more.htm~~" +
  "http://car.autohome.com.cn/price/series-528.html~~" +
  "http://jxfuzhou.ganji.com/~~" +
  "http://Xe.com/currencytransfers/?WT.seg_1=XTR-TL-XHOM-XIN-XX-V02-131001~~" +
  "http://sport.sptopf.de/tshp/RE?ID=73429096&CID=71562072&FID=rl13-C1_20&GID=64756648&URL=http%3A%2F%2Fad2.adfarm1.adition.com%2Fredi%3Fsid%3D2847643%26kid%3D1182531%26bid%3D4153115~~" +
  "http://www.buzzfeed.com/buzzfeednews~~" +
  "https://www.kickstarter.com/discover/categories/crafts~~" +
  "http://www.walmart.com/c/kp/nexus-tablets?povid=P1171-C1093.2766-L62~~" +
  "http://secure.milliyet.com.tr/redirect/Default.aspx?l=http%3a%2f%2fblog.milliyet.com.tr&z=42~~" +
  "http://Kickass.to/request/~~" +
  "http://elpais.com/tag/c/514e6c6d05d951ba9d88cc99647c9829~~" +
  "http://baike.pcbaby.com.cn/qzbd/1272575.html~~" +
  "http://acc.pconline.com.cn/626/6265638.html~~" +
  "http://bbs.360safe.com/forum-183-1.html~~" +
  "http://auction.rakuten.co.jp/~~" +
  "http://www.autohome.com.cn/657/~~" +
  "http://www.kaskus.co.id/classified/657/?ref=homelanding&med=fjb_categories~~" +
  "http://onas.wp.pl~~" +
  "http://www.telegraph.co.uk/archive/2015-3-28.html~~" +
  "http://price.pcauto.com.cn/~~" +
  "http://www.aliexpress.com/category/100001668/balloons.html~~" +
  "http://www.cbssports.com/nba/injuries~~" +
  "http://www.mercadolivre.com.br/servicos/~~" +
  "http://www.rambler.ru/sport/~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1218&zoneclick=101428~~" +
  "http://www.wikipedia.org//sg.wikipedia.org/~~" +
  "http://blog.sohu.com/chi/~~" +
  "https://paytm.com/bus-tickets/pune-to-hyderabad-booking~~" +
  "http://news.nicovideo.jp/watch/nw1246312?news_ref=nicotop_topics_rank~~" +
  "http://www.yelp.com.tr/~~" +
  "http://video.varzesh3.com/?p=75825~~" +
  "http://new.livejasmin.com/it/?showPreviousVersionLink=0&languageChange=1&session=g13ca65df7ee4cd0d8dbb8d6d5659c89c~~" +
  "http://car.bitauto.com/pika/~~" +
  "http://web.de/magazine/unterhaltung/tv-film/prof-dr-hans-hektisch-erklaert-germanys-next-topmodel-30527314~~" +
  "http://Ptt01.cc/post_16467~~" +
  "http://xfinitytv.comcast.net/live/network/tbs?cmpid=FCST_livemod_tbs~~" +
  "http://www.dailymail.co.uk/tvshowbiz/article-3015436/Masi-Oka-confirms-reprise-fan-favorite-role-Hiro-Nakamura-upcoming-NBC-reboot-Heroes-Reborn.html~~" +
  "http://blog.caijing.com.cn/earlzhang~~" +
  "http://www.baike.com/lunwen~~" +
  "http://about.mama.cn/about.html~~" +
  "http://en.gameforge.com/games/gamedetails/ikariam~~" +
  "http://Stackoverflow.com/questions/tagged/visualization~~" +
  "http://yp.xcar.com.cn/list/865/?zoneclick=101898~~" +
  "http://www.ppomppu.co.kr/recruit.php~~" +
  "http://www.nytimes.com/2015/03/27/automobiles/autoreviews/video-review-lincoln-navigator-a-behemoth-with-leather-and-attitude.html~~" +
  "http://www.deviantart.com/tag/defaced~~" +
  "https://itunes.apple.com/us/app/aliexpress/id436672029?mt=8&ls=1~~" +
  "http://tv.sohu.com/s2014/zghgqdej/~~" +
  "http://finance.eastmoney.com/news/1354,20150328491093370.html~~" +
  "http://legal.china.com.cn/2015-03/28/content_35179597.htm~~" +
  "http://gb.corp.163.com/gb/about/overview.html~~" +
  "http://biznes.onet.pl/waluty/notowania/waluty-online/notowania-online.html~~" +
  "http://ref.gamer.com.tw/0000144/*http://forum.gamer.com.tw/A.php?bsn=27299~~" +
  "http://art.ifeng.com/special/shmusic/index.html~~" +
  "http://product.pconline.com.cn/itbk/sjtx/sjjs/1502/6110181.html~~" +
  "http://www.yelp.de/~~" +
  "http://products.office.com/en-ca/business/enterprise-security-tools~~" +
  "http://www.mobile.de/modellverzeichnis/fiat/~~" +
  "http://open.tudou.com/~~" +
  "http://blog.sina.com.cn/s/blog_13c479d400102vgh8.html?tj=1~~" +
  "http://prairiehome.publicradio.org~~" +
  "http://s.kouclo.com/search.php?c=4394,DIYkouclo%E6%95%B0%E5%AD%97%E6%B2%B9%E7%94%BB~~" +
  "http://www.hurriyet.com.tr/kelebek/keyif/28572840.asp~~" +
  "http://www.lady8844.com/xiufa/diy/2015-03-25/1427271360d1557673.html~~" +
  "http://shopping.rediff.com~~" +
  "http://baike.pcbaby.com.cn/qzbd/940063.html~~" +
  "http://roll.dao.qq.com/?cata=minsu~~" +
  "http://tv.tudou.com/hanju/~~" +
  "http://www.babytree.com/community/club200700/~~" +
  "http://club.xywy.com/question/20150326/63737379.htm~~" +
  "http://cul.qq.com/shuzhai.htm~~" +
  "https://www.oracle.com/openworld/index.html~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=404&zoneclick=101450~~" +
  "http://Amazon.com/Panasonic-DMC-FZ70-Digital-Optical-Stabilized/dp/B00DY2Y28M~~" +
  "http://www.6pm.com/asics%7E1?s=isNew/desc/goLiveDate/desc/recentSalesStyle/desc/~~" +
  "http://car.bitauto.com/ruiqim5/~~" +
  "http://s.kouclo.com/search.php?c=2078,%E5%8C%85%E8%A2%8B~~" +
  "https://www.kickstarter.com/discover/places/atlanta-ga~~" +
  "http://mobile.zol.com.cn/513/5131069.html~~" +
  "https://www.mozilla.org/en-US/firefox/~~" +
  "http://www.theverge.com/users/AndrewRWebster~~" +
  "http://www.he.xinhuanet.com/zfwq/handan~~" +
  "http://www.tudou.com/albumplay/GPJO5cuV5Ms.html~~" +
  "http://article.pchome.net/content-1786372.html~~" +
  "http://www.babytree.com/ask/detail/18339785~~" +
  "http://www.zhihu.com/people/zliybst~~" +
  "http://blog.gmw.cn/blog-599018-732734.html~~" +
  "http://car.bitauto.com/tree_chexing/search/?p=5-8~~" +
  "http://wiadomosci.onet.pl/tylko-w-onecie/nowa-ksiazka-juergena-rotha-wg-niemieckich-sluzb-10-kwietnia-to-zamach/fgg23n~~" +
  "http://swimming.about.com~~" +
  "https://twitter.com/intent/retweet?tweet_id=581493399884201984~~" +
  "http://changsha.zol.com.cn/~~" +
  "http://zhangdiancheng.blog.sohu.com/308291795.html~~" +
  "http://lx.huanqiu.com/2015/lxnews_0328/34584.html~~" +
  "http://new.livejasmin.com/en/girl/big+tits?session=g13ca65df7ee4cd0d8dbb8d6d5659c89c?selectedFilters=35~~" +
  "http://video.corriere.it/spagna-l-immigrato-nascosto-dietro-paraurti-dell-auto/cbd7300a-d179-11e4-8608-3dead25e131d~~" +
  "http://price.xcar.com.cn/serise22/city9999-1-1.htm?zoneclick=101403~~" +
  "http://Ettoday.net/news/20120521/45149.htm~~" +
  "http://www.alibaba.com/Indoor-Lighting_pid100009161~~" +
  "http://s.taobao.com/search?q=%B1%F9%CF%E4&js=1&stats_click=search_radio_all%253A1&initiative_id=staobaoz_20150126~~" +
  "http://cpc.people.com.cn/GB/69112/113427/index.html~~" +
  "http://rd.nicovideo.jp/cc/nicotop_special/cho150325~~" +
  "http://Techcrunch.com/author/ryan-lawler/~~" +
  "http://www.starsports.com/storyteller/article=icc-cricket-world-cup-2015-india-australia-storyteller-report-aus-thrash-india-enter-final/index.html~~" +
  "http://cafe.daum.net/ok1221/9Zdf/140140?svc=livestory&q=%B9%CC%B1%B9+%BF%A9%B0%ED%BB%FD%B5%E9%C0%CC+%BF%AD%B1%A4%C7%DF%B4%F8+%C6%D0%BC%C7~~" +
  "http://clicklogger.rm.uol.com.br/?prd=16&grp=servico:Dominio;src:13;chn:0;creative:linkfixo_home2014_menu_hor;thm:uolhost_RegistrodeDominio&msr=Cliques%20de%20Origem:1&oper=11&redir=http://www.uolhost.com.br/registro-de-dominio.html~~" +
  "http://Kickass.to/game-of-thrones-telltale-pc-game-e1-e2-e3-nosteam-t10399188.html~~" +
  "http://m.gap.com~~" +
  "https://forums.craigslist.org/?areaID=25&forumID=34~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1199~~" +
  "http://weather.news.qq.com/~~" +
  "http://Kickass.to/zero-g-epica-incl-75-new-presets-kontakt-oddsox-t10413154.html~~" +
  "http://space.chinaz.com/wly~~" +
  "http://newcar.xcar.com.cn/2780/?zoneclick=101402~~" +
  "http://Php.net/manual/en/features.safe-mode.php~~" +
  "http://news.qq.com/a/20150328/024694.htm?tu_biz=1.114.1.0~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=723~~" +
  "http://s.b5m.com/s/Search?key=%E5%AE%B6%E5%85%B7&isKnn=0~~" +
  "http://baike.pcbaby.com.cn/qzbd/21.html~~" +
  "http://dl.pconline.com.cn/download/358212.html~~" +
  "http://s.b5m.com/s/Search?key=%E8%BF%90%E5%8A%A8%E6%9C%8D&isKnn=0~~" +
  "http://health.lady8844.com/549186/~~" +
  "http://www.facebook.com/varzesh3~~" +
  "http://www.tudou.com/albumplay/YcZLLllBfFk/kk2LUD8arjU.html~~" +
  "http://www.xda-developers.com/changelog/~~" +
  "http://www.washingtonpost.com/sports/capitals/curtis-glencross-surprises-himself-with-long-nhl-career/2015/03/27/dec10304-d47f-11e4-8fce-3941fc548f1c_story.html?tid=hpModule_c7c1f590-868f-11e2-9d71-f0feafdd1394~~" +
  "https://www.zendesk.de~~" +
  "https://www.wellsfargo.com/mobile-payments/apple-pay/~~" +
  "http://www.nomurafunds.com.tw/aries/AboutUs/chinese.aspx~~" +
  "http://Ettoday.net/news/20120521/48064.htm~~" +
  "http://www.marca.com/en/2015/03/28/en/football/barcelona/1427497373.html~~" +
  "http://eurosport.onet.pl/mma~~" +
  "http://musica.uol.com.br/noticias/efe/2015/03/27/lollapalooza-se-afasta-de-woodstock-e-tenta-desbancar-rock-in-rio.htm~~" +
  "http://www.ettoday.net/news/20120517/46959.htm~~" +
  "http://zt.mama.cn/x2/index.php?p=heinz&c=mamategongdui~~" +
  "http://www.avg.com/ca-en/ultimate?icid=ws-nav-zul~~" +
  "http://www.tmall.com/go/market/promotion-act/hualibianshen.php?abbucket=&acm=tt-1141523-37077.1003.8.225680&aldid=225680&abtest=&scm=1003.8.tt-1141523-37077.OTHER_1426539893459_225680&pos=1~~" +
  "http://video.liputan6.com/tv/bentrok-penambang-dan-polisi-di-maluku-hingga-orang-berdatangan-ke-rumah-olga-syahputra-2198445~~" +
  "http://s.taobao.com/search?spm=a213y.6633709.a214bug.28.IoIGfO&initiative_id=staobaoz_20140219&js=1&q=%D0%C2%C4%EF%C5%FB%BC%E7&stats_click=search_radio_all%3A1~~" +
  "http://prom.gome.com.cn/html/prodhtml/topics/201503/26/wrkxqcd.html?intcmp=sy-C-2-1-2-ds~~" +
  "http://car.autohome.com.cn/price/brand-33.html~~" +
  "http://bbs.zol.com.cn/sjbbs/d34066_1102.html~~" +
  "http://z.zol.com.cn/5133871.html~~" +
  "http://www.hurlist.com/etiket/1245/medya.htm~~" +
  "http://Ppomppu.co.kr/zboard/view.php?id=house&no=30547~~" +
  "http://bbs.zol.com.cn/sjbbs/d613_27604.html~~" +
  "http://www.zhihu.com/people/aullik5~~" +
  "http://www.snapdeal.com/products/health~~" +
  "http://tup.csdn.net~~" +
  "http://car.autohome.com.cn/photo/21373/1/2844415.html?pvareaid=100579~~" +
  "http://www.infusionsoft.com/news/awards~~" +
  "http://Ettoday.net/social/push.htm~~" +
  "http://cixi.xcar.com.cn/~~" +
  "http://down.chinaz.com/soft/7322.htm~~" +
  "http://baike.pcbaby.com.cn/qzbd/940294.html~~" +
  "http://www.tudou.com/home/beautycate/~~" +
  "http://www.quikr.com//www.youtube.com/subscription_center?add_user_id=pLtpHTmLXwgNMA_OXvOQew&feature=creators_cornier-//s.ytimg.com/yt/img/creators_corner/Subscribe_to_my_videos/YT_Subscribe_61x23_red.png~~" +
  "http://haixi.xcar.com.cn/~~" +
  "http://plus.google.com/+milliyet/~~" +
  "http://www.foxnews.com~~" +
  "http://diy.pconline.com.cn/625/6258157.html~~" +
  "http://baike.pcbaby.com.cn/qzbd/9026.html~~" +
  "http://biztaxlaw.about.com~~" +
  "http://Themeforest.net/category/ecommerce/prestashop~~" +
  "http://imgur.com/gallery/koGtdsV~~" +
  "http://newcar.xcar.com.cn/auto/index.php?r=dealerPopw/order&pserid=160&did=0&city_id=475&type=1&is_cms=92~~" +
  "http://www.pinterest.com/wixcom/~~" +
  "http://www.lady8844.com/shoushen/app/bmr/~~" +
  "http://yuedu.163.com/book_reader/bd_80d9b7f8a30f4902903c6ade37af746d_4/heiyan_8641_168116_4?utm_campaign=163ad&utm_source=163home&utm_medium=tab_1_1_1~~" +
  "http://jiaju.sina.com.cn/";

exports.prefGestaltPS = prefGestaltPS;
