const prefGestaltPS =
  "http://video.corriere.it/crozza-landini-la-mia-coalizione-non-partito/d7a019a8-d4c9-11e4-831f-650093316b0e~~" +
  "http://Ettoday.net/news/20120521/48029.htm?from=index_pets~~" +
  "http://detail.zol.com.cn/massage_equipment/~~" +
  "http://car.bitauto.com/v8vantage/~~" +
  "https://www.elance.com/q/sites/default/files/docs/AIR/AnnualImpactReport.pdf.html~~" +
  "http://louisville.about.com~~" +
  "http://www.nba.com/playerfile/james_harden/~~" +
  "http://www.sahibinden.com/destek~~" +
  "http://jieyang.ganji.com/~~" +
  "http://www.ign.com/wikis~~" +
  "http://constructionmgmt.about.com~~" +
  "http://entertainment.rakuten.co.jp/~~" +
  "http://Wunderground.com/MAR/~~" +
  "http://jsb.xywy.com/~~" +
  "http://www.huffingtonpost.ca/news/alberta-politics~~" +
  "https://www.crunchbase.com/category/mass-customization/00935010bf48c1de55f07cfca1812391?utm_source=tc_river&utm_medium=export&utm_campaign=dataset~~" +
  "http://baike.pcbaby.com.cn/qzbd/9191.html~~" +
  "http://yuedu.163.com/source/6c11cadde04f478cb92d837bfeef1853_4?utm_campaign=163ad&utm_source=163home&utm_medium=tab_1_2_3~~" +
  "http://www.milliyet.com.tr/Milliyet.aspx?aType=gundemYazarTumYazilarV4&AuthorID=59~~" +
  "http://datong.ganji.com/~~" +
  "http://www.newegg.com/Safes/SubCategory/ID-3337~~" +
  "http://www.addthis.com/bookmark.php?v=300&winname=addthis&pub=ra-50dc926d011f6845&source=tbx-300&lng=en-US&s=facebook&url=http%3A%2F%2Funrequieted-love.urbanup.com%2F4952263&title=Urban%20Dictionary%3A%20unrequieted%20love~~" +
  "http://www.foxnews.com/entertainment/2015/03/27/sopranos-star-drea-de-matteo-apartment-destroyed-in-nyc-east-village-fire/~~" +
  "http://s.b5m.com/item/c4cf5b266774fbdb6c04987d68169b3f.html?mps=____.1016.0.0.0~~" +
  "http://ent.huanqiu.com/star/mingxing-gangtai/2015-03/6023502.html~~" +
  "http://www.pchouse.com.cn/baike/~~" +
  "http://bbs.hupu.com/12054270.html~~" +
  "http://tw.mall.yahoo.com/store/10arts~~" +
  "http://time.com/entertainment/~~" +
  "http://www.cnet.com/topics/mobile-apps/how-to/~~" +
  "http://detail.zol.com.cn/price_cate_1.html~~" +
  "http://js1.eastmoney.com/tg.aspx?ID=3628~~" +
  "http://www.buzzfeed.com/about/useragreement~~" +
  "http://cancer.about.com~~" +
  "http://www.goal.com/de/~~" +
  "http://chifeng.xcar.com.cn/~~" +
  "https://ssl.naver.jp/join?fromUrl=http%3A%2F%2Fmatome.naver.jp%2F~~" +
  "http://www.cbssports.com/info/closed-caption~~" +
  "http://www.milliyet.com.tr/manchester-united-dan-ronaldo-ya---2035426-skorerhaber/?ref=OtherNews~~" +
  "http://www.nyaa.se/?page=download&tid=671089~~" +
  "http://cosme.pclady.com.cn/esteelauder.html~~" +
  "http://www.telegraph.co.uk/motoring/picturegalleries/11498509/The-history-of-the-black-cab.html~~" +
  "http://rs.ci123.com/video/item_41195.html~~" +
  "http://shoptalk.lifehacker.com~~" +
  "http://www.teepr.com/category/%e9%a9%9a%e5%a5%87/%e5%9c%b0%e7%90%83/~~" +
  "http://www.aliexpress.com/category/3710/home-decor.html~~" +
  "http://www.bild.de/bild-plus/unterhaltung/tv/ferdinand-von-schirach/diese-szene-von-folge-sechs-haben-sie-nicht-im-tv-gesehen-40311876.bild.html~~" +
  "http://matome.naver.jp/odai/2142249774828952301~~" +
  "http://caipiao.163.com/game_center/index.jsp~~" +
  "http://www.hotels.com/account/manage_bookings.html~~" +
  "http://guba.eastmoney.com/list,601766.html~~" +
  "http://magazine.foxnews.com/celebrity/breakfast-wrap-lindsay-lohans-unfettered-chest-taylor-swifts-secret-bold-lips-and-more~~" +
  "http://www.snapdeal.com/products/home-kitchen-curtains-blinds?q=Store_s:Buy1%20Get1&sort=bstslr~~" +
  "http://bbs1.people.com.cn/post/2/1/2/146199132.html~~" +
  "http://wuhu.ganji.com/~~" +
  "http://religion.bhaskar.com/news/JM-SEHE-life-management-tips-about-happiness-and-peace-of-mind-4933776-NOR.html~~" +
  "http://www.abs-cbnnews.com/business~~" +
  "http://car.bitauto.com/xinjunyue/~~" +
  "http://food.lady8844.com/80/~~" +
  "http://www.washingtonpost.com/news/digger/~~" +
  "http://product.pconline.com.cn/hl/~~" +
  "http://lady.163.com/15/0324/11/ALFHB2O300264N2N.html~~" +
  "http://book.ce.cn/~~" +
  "http://Ettoday.net/news/20120518/47488.htm~~" +
  "http://baike.pcbaby.com.cn/qzbd/1113157.html~~" +
  "http://www.naukri.com/tieups/tieups.php?othersrcp=15014~~" +
  "http://www.engadget.com/reviews/scanners/~~" +
  "http://www.enet.com.cn/cio/aklist0_%CE%EF%C1%AA%CD%F8.html~~" +
  "http://www.cricbuzz.com/cricket-news/71356/michael-clarke-to-quit-odis-after-world-cup-final~~" +
  "http://zdm.b5m.com/shihui/24542.html~~" +
  "http://rd.nicovideo.jp/cc/nicotop_blomaga/pickupar1?cc_article_id=140857~~" +
  "http://Clien.net/cs2/bbs/board.php?bo_table=news~~" +
  "http://forum.thefreedictionary.com/postst75546_Andrew-Wyeth.aspx~~" +
  "http://www.alibaba.com/Sports&LeisureBags_pid3806~~" +
  "http://www.chinaz.com/mobile/evaluate/~~" +
  "http://www.imdb.com/title/tt2179136/trivia?item=tr2354418&ref_=hm_trv_hd~~" +
  "http://baike.pcbaby.com.cn/qzbd/957374.html~~" +
  "http://www.milliyet.com.tr/fotogaleri/47611-kafasi-gitgide-buyuyor/~~" +
  "http://www.espncricinfo.com/west-indies-v-england-2015/content/story/856137.html~~" +
  "http://politics.gmw.cn/2015-03/28/content_15227457.htm~~" +
  "http://www.mama.cn/ask/jingxuan/1383/~~" +
  "http://www.gome.com.cn/category/cat10000188-00-0-48-1-0-0-0-1-0-0-1-0-0-0-0-0-0.html~~" +
  "http://hechi.xcar.com.cn/~~" +
  "http://Ppomppu.co.kr/zboard/view.php?id=fifaonline&no=50470~~" +
  "http://www.bilibili.com/video/douga.html~~" +
  "http://www.att.com/shop/wireless/devices/cellphones.html~~" +
  "http://www.slideshare.net/GuyKawasaki/how-to-pack-a-punch-with-social-media~~" +
  "http://Stackoverflow.com/users/4723340/qitao-li~~" +
  "https://hootsuite.com/services/partner-programs?icn=footernav&ici=Partner+Programs~~" +
  "http://www.woot.com/?ref=gh_w_1~~" +
  "http://montreal.craigslist.ca/~~" +
  "http://Adf.ly/~~" +
  "http://www.iqiyi.com/v_19rrno6e6c.html?src=focustext_0_20130527_7~~" +
  "http://Stackoverflow.com/users/4216782/mortiz-chen~~" +
  "http://edu.qq.com/a/20150328/011250.htm?tu_biz=v1~~" +
  "http://Themeforest.net/sign_up~~" +
  "http://www.cbssports.com/video/player/videos/419458115590/0/5-utah-vs-2-duke-highlights~~" +
  "http://newcar.xcar.com.cn/1367/?zoneclick=101403~~" +
  "http://xfinitytv.comcast.net/live/network/msnbc?cmpid=FCST_livemod_featured_MSNBC_lockup~~" +
  "http://mediaset.vitv.it/veconomia/legge-di-stabilita-via-libera-della-ue-alla-manovra-dell-italia/517790?ref=%20veconomia~~" +
  "http://guoqing.china.com.cn/node_7140023.htm~~" +
  "http://Coccoc.com/win/en/thanks.html~~" +
  "http://www.cnet.com/the-fix/~~" +
  "http://www.newegg.com/Receipt-Printer/SubCategory/ID-3032~~" +
  "http://erlianhaote.xcar.com.cn/~~" +
  "http://bbs.hupu.com/12298074.html~~" +
  "http://rd.nicovideo.jp/cc/nicotop_blomaga/pickupar1?cc_article_id=757993~~" +
  "http://www.att.com//att.com/gen/landing-pages?pid=9214~~" +
  "http://www.tripadvisor.com/Hotels-g60745-Boston_Massachusetts-Hotels.html~~" +
  "http://Coccoc.com/addtone.html~~" +
  "http://prom.gome.com.cn/html/prodhtml/topics/201503/ice-150323ktyr.html?intcmp=sy-A-5-3-1-gd~~" +
  "http://ask.39.net/browse/1019-2-1.html~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=986&zoneclick=101425~~" +
  "http://cluster.alibaba.com/Construction-Machinery-Shandong-China_100002024_supplier.html~~" +
  "http://go.microsoft.com/fwlink/p/?LinkId=403936~~" +
  "http://www.wikipedia.org//te.wikipedia.org/~~" +
  "http://wiki.answers.com/Q/FAQ/4031~~" +
  "http://car.bitauto.com/feiyatecmedium/~~" +
  "http://investor.shutterstock.com/~~" +
  "http://kakaku.com/hobby/~~" +
  "http://xfinity.comcast.net/video/Terrific-tips-for-tax-deductions-like-your-kids-day-camp/419107907962/Comcast/TODAY_new/?cid=todaymod_sf_TaxDeductions~~" +
  "http://zx.39.net/fcs/~~" +
  "http://s.kouclo.com/search.php?c=1901,%E6%91%86%E4%BB%B6~~" +
  "http://www.flipkart.com/q/lenovo-tablets~~" +
  "http://www.hotels.com/customer_care/pillar/welcomerewards.html~~" +
  "http://Wunderground.com/maps/catalog/~~" +
  "http://jbk.39.net/byby/~~" +
  "http://yyk.39.net/search/t2/ltfuke/penqiangyan.html~~" +
  "http://jbk.39.net/jiancha/search/chaosheng2~~" +
  "https://aws.amazon.com/marketplace/search/results/ref=mkt_ste_l2_gaming?page=1&searchTerms=gaming&nc2=h_mo~~" +
  "http://news.china.com/finance/11155042/20140916/18788513.html~~" +
  "http://udn.com/news/cate/6640~~" +
  "http://club2011.auto.163.com/post/100013606153.html~~" +
  "http://www.nytimes.com/pages/science/index.html~~" +
  "http://product.pconline.com.cn/mobile/coolpad/~~" +
  "http://www.kouclo.com/item/index/118647~~" +
  "http://www.huffingtonpost.ca/news/bc-politics~~" +
  "http://allegro.pl/myaccount/bid.php~~" +
  "http://www.nyaa.se/?page=view&tid=671045~~" +
  "http://www.huffingtonpost.com/marc-hershon/podcast-reviews-we-got-th_b_6960062.html?utm_hp_ref=entertainment&ir=Entertainment~~" +
  "http://www.4shared.com/remindPassword.jsp~~" +
  "http://www.buzzfeed.com/jamiejones~~" +
  "http://baike.pcbaby.com.cn/qzbd/702.html~~" +
  "http://finance.ce.cn/bank/lccp/~~" +
  "http://kakaku.com/tv/channel=12/~~" +
  "http://Slickdeals.net/newsearch.php?mode=popdeals&searcharea=deals&searchin=first&rss=1~~" +
  "http://www.pcauto.com.cn/nation/613/6133643.html~~" +
  "http://www.washingtonpost.com/entertainment/theater-dance~~" +
  "http://books.rakuten.co.jp/event/e-book/application/desktop/?scid=wi_ich_lnk_top_genremenu_kobo~~" +
  "http://www.symama.com/portal.php~~" +
  "http://extratorrent.cc/view/popular/Anime.html~~" +
  "http://www.tudou.com/list/ach4a-2b123c-2d-2e-2f-2g-2h-2i-2j-2k-2l-2m-2n-2sort2cla-2hot-2.html~~" +
  "http://price.pcauto.com.cn/sg4437/~~" +
  "http://www.babytree.com/rd/rd.php?refcode=al0917al&sid=al0917al&url=http%3A%2F%2Fwww.babytree.com%2Fuser%2Fshowuser.php%3Fuid%3Du13399626244%26tab%3Dcenter~~" +
  "http://www.lady8844.com/aboutus/sitemap.html~~" +
  "http://www.marca.com/en/2015/03/27/en/football/national_teams/1427493839.html~~" +
  "http://www.rakuten.co.jp/category/watch/~~" +
  "http://Slickdeals.net/deals/tv/~~" +
  "http://baike.pcbaby.com.cn/qzbd/939476.html~~" +
  "http://udn.com/news/story/1/798803~~" +
  "http://Amazon.com/Samsung-Galaxy-S6-Edge-Platinum/dp/B00V5M0VV0~~" +
  "http://elpais.com/tag/critica_literaria/a/~~" +
  "http://www.tripadvisor.com/smartdeals?geo=60763&m=21194~~" +
  "http://www.expedia.ca//www.expedia.ca/Hotels~~" +
  "http://fantasynews.cbssports.com/fantasybasketball/~~" +
  "http://product.pconline.com.cn/tabletpc/series/411386.html~~" +
  "http://zt.pchouse.com.cn/gelou/~~" +
  "http://slide.history.sina.com.cn/r/slide_61_40602_44369.html~~" +
  "http://guba.eastmoney.com/list,000157.html~~" +
  "http://detail.zol.com.cn/refrigeratorcar/~~" +
  "http://www.ci123.com/baike/nbnc/~~" +
  "http://www.naukri.com/tieups/tieups.php?othersrcp=18108~~" +
  "http://bleacherreport.com/articles/2412235-is-masterful-michigan-st-run-the-greatest-coaching-job-of-tom-izzos-career~~" +
  "http://www.telegraph.co.uk/sponsored/sport/golfing-breaks-liverpool/?WT.mc_id=tmgspk_td_605966_8563&utm_source=tmgspk&utm_medium=td&utm_content=605966&utm_campaign=tmgspk_td_605966_8563~~" +
  "http://baike.pcbaby.com.cn/qzbd/1122005.html~~" +
  "http://v.opahnet.com/soccer/v475436.html~~" +
  "http://news.china.com/finance/11155042/20150225/19318693.html~~" +
  "http://jiuquan.xcar.com.cn/~~" +
  "http://web.de/magazine/unterhaltung/adel/royal-baby-2/daily-kate-augen-royalen-baby-bauch-30205922~~" +
  "http://www.pchouse.com.cn/shchuwei/~~" +
  "http://otomotif.kompas.com~~" +
  "https://www.evernote.com/market~~" +
  "http://newcar.xcar.com.cn/car/0-0-0-0-30-0-0-0-0-0-0-0/&zoneclick=101570~~" +
  "http://www.nx.xinhuanet.com/~~" +
  "http://www.spiegel.de/gesundheit/diagnose/wechseljahresbeschwerden-mehr-als-nur-hitzewallungen-a-1025383.html~~" +
  "http://www.t-online.de/ratgeber/auto/autoreparatur-pflege/id_48540684/autowaschen-im-freien-erlaubt-oder-verboten-.html~~" +
  "http://slide.ent.sina.com.cn/star/slide_4_704_105327.html~~" +
  "http://news.liputan6.com/kategori/liputankhusus~~" +
  "http://www.360.cn/qudongdashi/index.html?src=navi~~" +
  "http://baike.pcbaby.com.cn/qzbd/1105211.html~~" +
  "http://www.capitalone.com/private-client-group/?Log=1&EventType=Link&ComponentType=T&LOB=MTS%3A%3AL0RT6ME8Z&PageName=Home+Page+C&PortletLocation=2&ComponentName=primary_nav&ContentElement=IN-L-5%3BWealth+and+Asset+Management&TargetLob=MTS%3A%3ALCTMNE8UU&TargetPageName=Wealth+and+Asset+Management&referer=https%3A%2F%2Fwww.capitalone.com%2Fhomepage~~" +
  "http://www.czxiu.com/~~" +
  "http://www.marca.com/tag//Marc_Marquez/~~" +
  "http://no.thefreedictionary.com/~~" +
  "http://www.oracle.com/ocom/groups/systemobject/@mktg_admin/documents/webcontent/videoplayer-ocom.html?bctid=4005693691001&playerType=single-social&size=events&shareURL-http://www.oracle.com~~" +
  "http://car.bitauto.com/zhongtai2008/~~" +
  "http://www.marca.com/2015/03/27/motor/mundial_motos/gp-qatar/1427481953.html~~" +
  "http://www.huffingtonpost.ca/2015/03/26/awkward-family-photos-bab_0_n_6948120.html~~" +
  "http://www.taoche.com/buycar/serial/xinaodia6l/~~" +
  "http://liuzhou.ganji.com/~~" +
  "http://techcrunch.com/column/~~" +
  "http://www.ganji.com/shoujipinpai/bird/~~" +
  "http://baby.ce.cn~~" +
  "http://Amazon.com/Diver-Waterproof-Player-Includes-Earphones/dp/B00GYIC8AW~~" +
  "http://hao.360.cn/xinwenmeiti.html~~" +
  "http://diet.goo.ne.jp/~~" +
  "http://mgod.webtretho.com/forum~~" +
  "http://www.bobo.com/?f=163.homeGuess~~" +
  "http://www.telegraph.co.uk/men/the-filter/11498913/Zayn-Malik-10-tips-on-how-to-live-like-a-normal-22-year-old.html~~" +
  "http://c.nfa.jd.com/adclick?keyStr=z5AXFoIimt1jiDK32+w4mY2B9TVUsepgbhEVVeBcfyyxUfshuvVYKjsjmqu16ptrqfVeOdQIrA7CG7jMsOEB2x6VullrmZs1SOp6XJ1SRqda4eG9P+LQ+i7XDdn0nvJz8CPLbhZfRoIKuGKVdxImsXM8S9XfpOHswn906TWu53Nsu5n0wC4ckcx894yhrY7lYz8ddh/GbNfIuDAiJ4gYKt4X/q+Z8U55m5KtuyGo30ndx+esPeiui5d2e7/61yXMEGCZSv23KzLEJ7iIcELU9Hh3ogyOSAmBubHByDZy7kg=&cv=2.0&url=http://jdarrow.jd.com/~~" +
  "http://www.theverge.com/users/NathanIngraham~~" +
  "http://www.cma.org.cn/~~" +
  "http://www.walmart.com/browse/clothing/baby-kids/5438_1045804_1045805/?_refineresult=true&povid=P1171-C1110.2784+1455.2776+1115.2956-L165~~" +
  "http://js5.eastmoney.com/tg.aspx?ID=468~~" +
  "https://www.odesk.com/o/jobs/browse/c/customer-service/~~" +
  "http://blog.39.net/doctor.html~~" +
  "http://haikou.bitauto.com/~~" +
  "https://twitter.com/hashtag/PowerOfTheLink?src=hash~~" +
  "http://cnrdn.com/3uyD~~" +
  "http://home.163.com/15/0327/07/ALMPNVOQ00104J5U.html~~" +
  "http://www.bhaskar.com/news/SPO-WC-NWC-world-cup-2015-team-indias-studs-and-duds-of-the-tournament-4946544-PHO.html~~" +
  "http://feedproxy.google.com/~r/foxnews/partner/tmz/general/~3/fEIusmJBBtc/~~" +
  "http://www.flipkart.com/promotion/pr?offer=DOTDOnPrimuzUniversal_Mar28.&sid=ckf&icmpid=hp_dotd_4_DOTDOnPrimuzUniversal_Mar28~~" +
  "http://www.bbc.co.uk/sport/cricket/32098251~~" +
  "http://www.businessinsider.com/warroom~~" +
  "http://edu.pcbaby.com.cn/zuowen/jrzw/qmjzw/~~" +
  "http://religion.bhaskar.com/news/JM-GN-HAIR-home-remedies-for-fair-skin-4943666-PHO.html~~" +
  "http://www.ettoday.net/news/20120521/47964.htm~~" +
  "http://www.target.com/c/clinic-health/-/N-54x94~~" +
  "http://www.spiegel.de/thema/umbruch_der_medienwelt~~" +
  "https://hi-tech.mail.ru/bytovaya/five-vitamine-dishes-for-good-health.html~~" +
  "http://neosorcerer.deviantart.com/~~" +
  "http://123.sogou.com/xyx/~~" +
  "http://www.theverge.com/gaming~~" +
  "http://adequateman.deadspin.com/how-to-not-get-shot-to-death-by-a-police-officer-1682546554~~" +
  "http://geek.360.cn/~~" +
  "http://www.ci123.com/~~" +
  "http://fun.kid.qq.com/funshop/index.php?app=ebook_detail&elid=163490~~" +
  "http://en.gameforge.com/news/airrivals/AirRivals.%20The%20Valentine.s%20event%20with%20gifts%20ready%20to%20collect./62~~" +
  "http://baike.pcbaby.com.cn/qzbd/1271972.html~~" +
  "http://photo.hupu.com/ent/p12868.html~~" +
  "http://g.163.com/a?CID=20480&Values=190879569&Redirect=http://chunji.xdf.cn/?utm_source=163&utm_medium=menhu&utm_campaign=jituan_chunji_163_wenzi~~" +
  "http://www.t-online.de/nachrichten/ausland/id_73448636/kriminalitaet-erleichterung-bei-knox-und-sollecito-nach-freispruch.html~~" +
  "http://brandbase.mama.cn/hinsang.php?mod=home~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1200~~" +
  "http://yingkou.ganji.com/~~" +
  "http://www.ebay.com/cln~~" +
  "http://aws.amazon.com/about-aws/whats-new/2015/03/aws-console-resource-groups-and-tag-editor-now-support-tag-substring-resource-search/~~" +
  "http://www.webmd.com/mental-health/eating-disorders/binge-eating-disorder/ss/slideshow-binge-eating-disorder~~" +
  "http://Kakaku.com/research/?lid=research_top_title2~~" +
  "http://jobsearch.naukri.com/jobs-by-location~~" +
  "http://love.rambler.ru/~~" +
  "http://www.bitauto.com/aletai/~~" +
  "http://xfinitytv.comcast.net/live/network/amc?cmpid=FCST_livemod_amc~~" +
  "http://www.enet.com.cn/security/alist7834.html~~" +
  "http://article.pchome.net/n308/s1/1.html~~" +
  "http://bollywood.bhaskar.com/news-hb/ENT-BNE-sidharth-malhotra-spotted-first-time-with-parents-4945560-PHO.html~~" +
  "http://fund.eastmoney.com/dingtou/~~" +
  "http://www.nba.com/summerleague/?ls=iref:nba:gfooter~~" +
  "http://xfinitytv.comcast.net/mytv/dvr?cmpid=xf_dash_dvr~~" +
  "http://jbk.39.net/ydy/~~" +
  "http://www.booking.com/index.zh-cn.html~~" +
  "http://www.wikipedia.org//lmo.wikipedia.org/~~" +
  "http://www.yelp.com/topic/san-francisco-san-francisco-restaurants-date-night~~" +
  "http://www.youm7.com/story/2015/3/28/%d8%a7%d8%b3%d8%aa%d8%b4%d9%87%d8%a7%d8%af-%d9%85%d9%84%d8%a7%d8%b2%d9%85-%d8%a3%d9%88%d9%84-%d9%88%d8%a5%d8%b5%d8%a7%d8%a8%d8%a9-%d9%85%d8%ae%d8%a8%d8%b1-%d8%b3%d8%b1%d9%89-%d8%a8%d8%b1%d8%b5%d8%a7%d8%b5-%d9%85%d8%ac%d9%87%d9%88%d9%84%d9%8a%d9%86-%d9%81%d9%89-%d8%a7%d9%84%d9%85%d9%86%d9%88%d9%81%d9%8a%d8%a9/2120105~~" +
  "http://www.ebay.com/sch/Boats-/26429/i.html?_momoc=1&_rdc=1~~" +
  "https://bitly.com/pages/tour~~" +
  "http://yyk.39.net/search/t2/naojishui.html~~" +
  "http://www.autohome.com.cn/tuning/201502/861767.html~~" +
  "http://www.dailymail.co.uk/video/news/video-1168377/Meet-Patrick-oldest-biggest-wombat-world.html~~" +
  "http://list.taobao.com/itemlist/default.htm?cat=50038537&isprepay=1&as=0&viewIndex=1&atype=b&style=grid&md=5221&same_info=1&olu=yes&isnew=2&scm=1220.8.6.5&tid=0&_input_charset=utf-8~~" +
  "http://Codecanyon.net/category/php-scripts/project-management-tools~~" +
  "http://edu.pcbaby.com.cn/resource/yey/dbja/~~" +
  "https://www.kickstarter.com/discover/curated-pages?ref=home_curated~~" +
  "http://lady.people.com.cn/n/2015/0327/c1014-26759094.html~~" +
  "http://www.4shared.com/servlet/signin/google?fp=http%3A%2F%2Fwww.4shared.com%2Faccount%2Fhome.jsp~~" +
  "http://Ppomppu.co.kr/zboard/view.php?id=baseball&no=431700~~" +
  "http://s.b5m.com/s/Search?key=%E6%96%87%E5%85%B7%E7%94%A8%E5%93%81&isKnn=0~~" +
  "http://www.bild.de/bild-plus/sport/fussball/juergen-klopp/das-ist-seine-wackelliste-40304506.bild.html~~" +
  "http://review.kakaku.com/review/K0000705892/ReviewCD=809591/?lid=top_topics_proreview~~" +
  "http://www.nba.com/global?ls=iref:nba:gnav~~" +
  "http://veggoanchio.corriere.it/2015/03/26/a-pasqua-scegli-veg-le-campagne-animaliste-contro-la-strage-degli-agnelli/~~" +
  "http://www.santillana.com.do/~~" +
  "https://www.facebook.com/navermatome~~" +
  "http://www.snapdeal.com/launchpad~~" +
  "http://www.bhaskar.com/news/JOK-DJOK-jok-djok-jok-djok-latest-hindi-sms-comedy-jokes-4946405-NOR.html~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1421~~" +
  "http://money.bhaskar.com/news/MON-MARK-COMM-GOL-changes-in-price-fix-methodology-of-gold-4944338-PHO.html~~" +
  "https://hootsuite.com/webinars?icn=footernav&ici=Webinars~~" +
  "http://s.b5m.com/s/Search?key=%E8%A1%A5%E7%9B%8A%E5%AE%89%E7%A5%9E&isKnn=0~~" +
  "http://www.dailymail.co.uk/tvshowbiz/article-3015236/Calvin-Harris-admits-swipe-left-Taylor-Swift-Tinder-rejects-rumoured-girlfriend-old-interview.html~~" +
  "http://www.reddit.com/r/AskReddit/comments/30kzi5/hey_reddit_whats_in_your_heaven/~~" +
  "http://s.b5m.com/s/Search?key=%E4%BA%BA%E5%81%B6&isKnn=0~~" +
  "http://military.china.com/news2/569/20150327/19434937.html~~" +
  "http://s.kouclo.com/search.php?c=6941,%E5%9C%B0%E5%9E%AB~~" +
  "http://world.gmw.cn/node_67693.htm~~" +
  "http://product.enet.com.cn/xdp267125.html~~" +
  "http://jbk.39.net/gja/ysbj/~~" +
  "http://www.linkedin.com/company/linkedin/careers?trk=hb_ft_work~~" +
  "http://www.lady8844.com/zhuanti/xf/hfyf/2006-11-29/1164793618d13869.html~~" +
  "http://detail.zol.com.cn/digital_tv/samsung/~~" +
  "http://vipmail.163.com/~~" +
  "http://www.sbilife.co.in~~" +
  "http://www.life.com.tw/?app=category&act=categorylist&no=19~~" +
  "http://www.360.cn/cert.html~~" +
  "http://wearemadeinny.com/~~" +
  "http://www.aliexpress.com/category/200004117/men-watches.html?shipCountry=all&shipFromCountry=&shipCompanies=&SearchText=&minPrice=&maxPrice=&minQuantity=&maxQuantity=&isFreeShip=n&isFavorite=n&isRtl=n&isOnSale=n&isBigSale=n&similar_style=n&similar_style_id=&isAtmOnline=n&CatId=200004117&g=y~~" +
  "http://www.sahibinden.com/kategori/is-ilanlari~~" +
  "http://kinoprogramm.bild.de/desktop~~" +
  "http://www.aliexpress.com/category/200002253/flats.html~~" +
  "http://www.ettoday.net/news/20120510/45301.htm~~" +
  "http://mathematica.stackexchange.com/questions/tagged/education~~" +
  "http://corp.rakuten.co.jp/csr/activities/sports-culture/musicpower/~~" +
  "http://www.kaskus.co.id/classified/593/?ref=homelanding&med=fjb_categories~~" +
  "http://religion.bhaskar.com/news/JM-GN-GAC-home-remedies-of-mango-4945808-NOR.html~~" +
  "http://product.pchome.net/network_enterprise_storage/list_9_234_101.html~~" +
  "http://best.pconline.com.cn/youhui/126368.html~~" +
  "http://dsl-vergleich.bild.de/promo/~~" +
  "http://welcome.deviantart.com/~~" +
  "http://xingtai.ganji.com/~~" +
  "http://www.naukri.com/tieups/tieups.php?othersrcp=17941~~" +
  "http://elpais.com/ccaa/madrid.html~~" +
  "http://www.cnbc.com/id/102541324?__source=xfinity|mod&par=xfinity~~" +
  "http://dl.pconline.com.cn/download/90841.html~~" +
  "http://www.hurriyetemlak.com/?utm_source=grp&utm_medium=cpv&utm_campaign=hurriyet|header_tab|statik~~" +
  "http://car.bitauto.com/xiaoke/~~" +
  "http://wake.hiapk.com~~" +
  "http://zhuzhou.xcar.com.cn/~~" +
  "http://dietadvice.about.com~~" +
  "http://www.mama.cn/special/mmhkt/baojie/~~" +
  "https://plus.google.com/share?url=http%3A%2F%2Fspicyfood.about.com%2Fod%2FSpicy-Desserts-and-Sweets%2Fr%2FCinnamon-Sugar-and-Chocolate-Muffins-with-a-Touch-of-Chile.htm%3Futm_source%3Dgoogle%26utm_medium%3Dsocial%26utm_campaign%3Dshareurlbuttons~~" +
  "http://s.kouclo.com/search.php?c=19611,%E6%91%A9%E6%89%98%E8%BD%A6kouclo%E8%A3%85%E5%A4%87~~" +
  "http://www.imdb.com/list/watchlist?ref_=nv_wl_all_0~~" +
  "http://www.woot.com/plus/pyle-metal-detectors-4?ref=cnt_wp_25~~" +
  "http://edtech.about.com~~" +
  "http://www.foxnews.com/world/2015/03/28/amanda-knox-murder-conviction-overturned-by-italy-highest-court/?intcmp=trending~~" +
  "http://www.urbandictionary.com/popular.php?character=T~~" +
  "http://go.microsoft.com/fwlink/p/?LinkID=403449~~" +
  "http://smb.pchome.net/~~" +
  "http://baike.pcbaby.com.cn/qzbd/1057475.html~~" +
  "http://baike.pcbaby.com.cn/qzbd/1208717.html~~" +
  "http://baike.pcbaby.com.cn/qzbd/45.html~~" +
  "http://www.dell.com/learn/us/en/uscorp1/policies-privacy~~" +
  "http://www.pcbaby.com.cn/home/219/2197366.html~~" +
  "https://hootsuite.com/help?icn=sectopnav&ici=Help~~" +
  "http://s.kouclo.com/search.php?c=2019,%E5%87%89%E9%9E%8B~~" +
  "http://groupgifts.ebay.com/~~" +
  "http://s.b5m.com/s/Search?key=%E8%A1%AC%E8%A1%AB&isKnn=0~~" +
  "http://www.wikipedia.org//diq.wikipedia.org/~~" +
  "http://xfinity.comcast.net/articles/entertainment-eonline/20150327/b640352/~~" +
  "http://www.360buy.com/products/6196-6197-000.html~~" +
  "http://bnqt.com~~" +
  "http://www.milliyet.com.tr/olay-gunu-raporluymus--gundem-2035310/?ref=OtherNews~~" +
  "http://www.6pm.com/brands-x~~" +
  "http://jbk.39.net/cc/~~" +
  "https://paytm.com/bus-tickets/chennai-to-hyderabad-booking~~" +
  "http://Codecanyon.net/item/cinema-4d-abstract-material-kit-10-materials/10190293~~" +
  "http://jck.39.net/jiancha/huaxue/neifenmi/4da23.html~~" +
  "https://www.facebook.com/groupon~~" +
  "http://www.aliexpress.com/w/wholesale-Mizuno.html?SearchText=Mizuno&CatId=18~~" +
  "http://baike.pcbaby.com.cn/qzbd/1246.html~~" +
  "http://womenshair.about.com/od/healthyhairmaintenance/fl/Refresh-Dull-Lifeless-Limp-Hair-with-Beer.htm~~" +
  "http://wenku.it168.com/wenji/2452~~" +
  "http://www.reuters.com/news/technology~~" +
  "http://www.t-online.de/tv/tv-highlights/myspass/id_73421914/-tv-total-schweizerinnen-brechen-weltrekord-im-kleiderwechseln.html~~" +
  "http://www.chinaz.com/start/model/~~" +
  "http://tech.163.com/15/0328/03/ALOUAQIG00094ODV.html~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=679~~" +
  "http://guoqing.china.com.cn/node_7217430.htm~~" +
  "http://commonfund.nih.gov/diversity/index~~" +
  "http://price.pcauto.com.cn/sg9604/~~" +
  "http://chat.fc2.com/~~" +
  "http://www.macys.com/shop/mens-clothing/shop-all-mens-footwear/Occasion,Sortby,Productsperpage/Casual%20Shoe,ORIGINAL,40?id=55822&cm_sp=intl_hdr-_-flytrackingbreadcrumb-_-casual-shoes~~" +
  "http://www.mama.cn/special/fangguai/~~" +
  "http://www.wikipedia.org//wa.wikipedia.org/~~" +
  "http://www.bild.de/reise/startseite/reise/reise-15478744.bild.html~~" +
  "http://www.espncricinfo.com/icc-cricket-world-cup-2015/content/story/856099.html~~" +
  "http://m.163.com/android/software/32pk7e.html~~" +
  "http://s.kouclo.com/search.php?c=4319,%E5%B8%90%E7%AF%B7~~" +
  "http://Kakaku.com/hobby/~~" +
  "http://newcar.xcar.com.cn/photo/ps2515/?zoneclick=101447~~" +
  "http://pf.39.net/pfbzt/rwph~~" +
  "http://Ppomppu.co.kr/zboard/view.php?id=faq&no=29~~" +
  "http://bbs.zol.com.cn/sjbbs/d613_27609.html~~" +
  "http://tag.lady8844.com/1319893/~~" +
  "http://se.360.cn/?src=navi~~" +
  "http://game.zol.com.cn/512/5127584.html~~" +
  "http://dealer.xcar.com.cn/99743/market_7322703.htm~~" +
  "https://Eksisozluk.com/28-mart-2015-hollanda-turkiye-maci--4267659?a=popular~~" +
  "http://stock.eastmoney.com/news/1405,20150328491166850.html~~" +
  "http://www.tistory.com/~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1362&zoneclick=101432~~" +
  "http://shopping1.hp.com/is-bin/INTERSHOP.enfinity/WFS/WW-USSMBPublicStore-Site/en_US/-/USD/ViewApplication-DisplayCachedWelcomePage~~" +
  "http://product.pconline.com.cn/fj/~~" +
  "http://www.abs-cbnnews.com/nation/metro-manila/03/28/15/naia-enforces-da-ban-arkansas-fowl~~" +
  "http://www.autohome.com.cn/news/201503/847068.html~~" +
  "http://v.qq.com/cover/y/yyl715m1smhdi48/d0130y02cpb.html~~" +
  "http://s.kouclo.com/search.php?c=1803,%E9%BB%84%E9%87%91~~" +
  "http://ent.lady8844.com/~~" +
  "http://so.iqiyi.com/so/q_%E7%86%8A%E5%87%BA%E6%B2%A1~~" +
  "http://extratorrent.cc/hot_torrents/~~" +
  "http://car.bitauto.com/hafeidanshuangpai/~~" +
  "http://www.reuters.com/places/italy~~" +
  "http://dongxi.douban.com/show/3328371/?dcm=douban&dcs=anonymous-home-title~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=47~~" +
  "http://download.csdn.net/detail/a332324956/8456633~~" +
  "http://soccer.hupu.com/italy/~~" +
  "http://fashion.ifeng.com/body/~~" +
  "http://xfinity.comcast.net/siteindex/~~" +
  "http://shortstories.about.com~~" +
  "http://www.autohome.com.cn/news/201503/865761.html~~" +
  "https://www.americanexpress.com/us/credit-cards/benefits/view-all/?inav=ExploreYourCardsRewardsProgram~~" +
  "http://tuku.ent.china.com/fun/~~" +
  "http://www.pchouse.com.cn/baike/shenghuo/1996/~~" +
  "http://www.ltn.com.tw/ad?ano=2015032652~~" +
  "http://tech.china.com.cn/~~" +
  "http://photo.liputan6.com/showbiz/ribuan-orang-padati-pemakaman-olga-syahputra-2198641~~" +
  "http://finance.gmw.cn/~~" +
  "http://www.prisaradio.com~~" +
  "http://gshow.globo.com/programas/domingao-do-faustao/~~" +
  "https://vimeo.com/help/guidelines~~" +
  "http://z.xywy.com/zhuanye-zhengxingke.htm~~" +
  "http://Ettoday.net/bbc/~~" +
  "http://weekend.rambler.ru~~" +
  "http://help.dmm.com/-/detail/=/qid=10105/~~" +
  "http://s.b5m.com/s/Search?key=1%E5%8F%B7%E5%BA%97%E5%AE%98%E7%BD%91~~" +
  "https://google.com/+dainikbhaskar~~" +
  "http://my.xfinity.com/articles/sports-cbk/20150327/St.John_s-Lavin.Out/~~" +
  "http://life.pcbaby.com.cn/shzt/jiayunxin/~~" +
  "https://id.yahoo.com/?p=dnr~~" +
  "http://bbs.zol.com.cn/huodong/d2_24565.html~~" +
  "http://news.xinhuanet.com/info/2015-03/28/c_134103300.htm~~" +
  "http://imgur.com/user/bendetta227~~" +
  "http://www.citi.com/uae/homepage/index.htm~~" +
  "http://list.jd.com/670-686-690-0-0-0-0-0-0-0-1-1-1-1-1-2800-2850-0.html~~" +
  "http://s.taobao.com/search?q=%C7%AE%B0%FC+%C5%AE+&js=1&stats_click=search_radio_all%253A1&initiative_id=staobaoz_20150126~~" +
  "http://www.forbes.com/business/~~" +
  "http://eurosport.onet.pl/pilka-nozna/polacy-za-granica/media-wloski-gigant-chce-wojciecha-szczesnego/j73bt7~~" +
  "http://www.foxnews.com/science/2015/03/27/astronaut-scott-kelly-blasts-off-on-yearlong-space-station-mission/?intcmp=latestnews~~" +
  "http://www.expedia.ca~~" +
  "http://Amazon.com/Tyler-Perrys-Single-Moms-Club/dp/B00LFE43QC~~" +
  "http://www.yelp.ca/sf~~" +
  "http://prom.gome.com.cn/html/prodhtml/topics/201412/04/kjbydxd.html~~" +
  "http://www.nba.com/photos/index.html?ls=nbahppg3~~" +
  "http://speakingtree.in~~" +
  "http://sports.qq.com/a/20150328/006580.htm~~" +
  "http://www.theverge.com/2015/3/26/8292213/olio-smartwatch-hands-on~~" +
  "http://www.enet.com.cn/notebook/alist7423.html~~" +
  "http://Codecanyon.net/category/wordpress/ecommerce/woocommerce~~" +
  "http://www.aliexpress.com/category/200002015/motorcycle-auto-racing.html~~" +
  "http://baike.pcbaby.com.cn/qzbd/8266.html~~" +
  "http://ydk.39.net/dealerhtm/shlysyp/index.html~~" +
  "http://dl.pconline.com.cn/download/359379.html~~" +
  "https://aws.amazon.com/blogs/aws/amazon-rds-update-postgresql-9-4-1-now-available/~~" +
  "http://open.163.com/movie/2011/7/C/M/M7G9OSRDP_M7G9P2DCM.html~~" +
  "http://www.hq.xinhuanet.com/2015-03/28/c_127631642.htm~~" +
  "http://www.libero.it/servizi~~" +
  "http://baike.pcbaby.com.cn/qzbd/12457.html~~" +
  "http://extratorrent.cc/search_cloud/~~" +
  "http://down.chinaz.com/soft/29878.htm~~" +
  "http://www.telegraph.co.uk/education/~~" +
  "http://jiaxing.ci123.com~~" +
  "http://resolutioncenter.ebay.com/~~" +
  "https://www.elance.com/q/api2~~" +
  "http://www.ltn.com.tw/news/politics/breakingnews/1270834~~" +
  "http://www.engadget.com/reviews/misc/~~" +
  "http://gongyi.sina.com.cn/gyzx/2015-03-26/092652168.html~~" +
  "http://s.b5m.com/s/Search?key=U%E7%9B%98&isKnn=0~~" +
  "http://kakaku.com/itemnavi/?pdi_name=%8e%e8%97%a0%8c%95%90%ed%91%e0%83j%83%93%83j%83%93%83W%83%83%81%5b&pdi_id=0065~~" +
  "http://search.daum.net/search?w=tot&rtupcate=issue&q=%EB%82%A8%EC%A3%BC%ED%98%81&rtupcoll=DQP,NNS&guide=rissue&DA=ATG&nil_profile=rtupkwd~~" +
  "http://ameblo.jp/kuwabata0324/~~" +
  "http://culture.china.com/zt/zonghe/gay/~~" +
  "http://cluster.alibaba.com/Apparel-Home-Textiles-Jaipur-India_100002106_supplier.html~~" +
  "http://ad8.adfarm1.adition.com/redi?sid=3076399&kid=1212962&bid=3961622~~" +
  "http://huhehaote.bitauto.com/cheshi/~~" +
  "http://products.office.com/en-ca/business/explore-office-delve~~" +
  "http://dongxi.douban.com/app?dcm=anonymous-home-app&dcs=douban&referer=anony~~" +
  "http://bleacherreport.com/articles/2411691-ncaa-tournament-2015-everything-you-need-to-know-about-the-elite-eight~~" +
  "http://www.elpais.com/especial/mario-vargas-llosa/~~" +
  "http://Codecanyon.net/author/top_authors~~" +
  "http://en.gameforge.com/buddies/ask/19066~~" +
  "http://woman.39.net/baike/nxyj/yjls/~~" +
  "http://space.chinaz.com/zhanglinqiang~~" +
  "http://tj.pconline.com.cn/~~" +
  "http://car.autohome.com.cn/price/brand-75.html~~" +
  "http://greekfood.about.com~~" +
  "http://www.kayak.com.mx/~~" +
  "http://computers.woot.com/?ref=cnt_ft_cp_3~~" +
  "http://www.buzzfeed.com/claudiakoerner~~" +
  "http://bbs.zol.com.cn/diybbs/d231_788031.html~~" +
  "http://zdrowie.wp.pl/zdrowie/metody-naturalne/art386,mieta-pieprzowa-bogate-zrodlo-olejkow-eterycznych.html~~" +
  "http://www.mama.cn/z/462/~~" +
  "http://newsblog.chinatimes.com/list/8/new~~" +
  "http://hnnews.zjol.com.cn/~~" +
  "http://photo.pclady.com.cn/pic/70373.html~~" +
  "http://photos.walmart.com/walmart/storepage/storePageId=Wall+Art?povid=P1171-C1110.2784+1455.2776+1115.2956-L343~~" +
  "http://video.sina.com.cn/vlist/ent/idolbb/~~" +
  "http://xfinitytv.comcast.net/apps?CMP=ILC:MA:MA:ALL:COM:GEN:INT5491af4714d68~~" +
  "https://trade.1234567.com.cn/login?direct_url=/FundtradePage/redemption~~" +
  "http://news.lady8844.com/info/2013-08-14/1376465626d1301430.html~~" +
  "http://powerboat.about.com~~" +
  "http://www.newegg.com/Computer-Cases/Category/ID-9~~" +
  "http://www.aliexpress.com/category/32212/children-shoes.html~~" +
  "http://toronto.craigslist.ca//geo.craigslist.org/iso/tn~~" +
  "http://bbs.hupu.com/12304178.html~~" +
  "http://v.tudou.com/shiyuehehu/~~" +
  "http://car.bitauto.com/fushida/~~" +
  "http://h.163.com/~~" +
  "http://s.taobao.com/search?q=%C6%FB%B3%B5%D3%C3%C6%B7&commend=all&ssid=s5-e&search_type=item&sourceId=tb.index&spm=1.7274553.1997520841.1&initiative_id=tbindexz_20150126~~" +
  "http://product.enet.com.cn/list-522.html~~" +
  "http://www.trulia.com/home_prices/~~" +
  "http://espn.go.com/video/clip?id=12571224&categoryid=2378529~~" +
  "http://www.pcbaby.com.cn/shipu/zt/yangsheng/zenggao/~~" +
  "http://www.indiatimes.com/lifestyle/style/~~" +
  "http://www.kouclo.com/item/index/126632~~" +
  "http://www.woot.com/plus/toshiba-satellite-laptops?ref=cnt_wp_7~~" +
  "http://baike.pcbaby.com.cn/qzbd/4219.html~~" +
  "http://www.tudou.com/home/_453606308/~~" +
  "http://www.buzzfeed.com/jessicamisener/what-kind-of-sense-of-humor-do-you-have~~" +
  "http://webdesign.about.com~~" +
  "http://cms.mobile.de/de/haendler_informationen/index.html~~" +
  "http://blog.eastmoney.com/dhs5588/blog_121526224.html~~" +
  "http://www.bild.de/unterhaltung/leute/harry-potter/schwuler-dumbledore-sieht-aus-wie-mensch-40297004.bild.html~~" +
  "http://www.salesforce.com/industries/index.jsp~~" +
  "http://www.huffingtonpost.ca/2015/03/26/canada-vs-united-states-tug-of-war-video_n_6949296.html~~" +
  "http://Mashable.com/2009/11/~~" +
  "http://baike.pcbaby.com.cn/qzbd/1447.html~~" +
  "http://www.babytree.com/rd/rd.php?refcode=al0917al&sid=al0917al&url=http%3A%2F%2Fwww.babytree.com%2Fuser%2Fshowuser.php%3Fuid%3Du1472789326%26tab%3Dcenter~~" +
  "http://lcd.it168.com/~~" +
  "http://Themeforest.net/item/balloon-personal-vcard-template/9374637~~" +
  "http://bbs.hupu.com/12268107.html~~" +
  "http://www.autohome.com.cn/culture/201502/862815.html~~" +
  "http://advertising.gawker.com/~~" +
  "https://ssl.allegro.pl/fnd/authentication/~~" +
  "http://topics.gmw.cn/node_67612.htm~~" +
  "http://beauty.pclady.com.cn/makeup/part/lip/~~" +
  "http://www.bild.de/bild-plus/news/ausland/flug-4u9525/was-steht-in-der-geheimen-kranken-akte-des-amok-piloten-40320230.bild.html~~" +
  "http://www.nba.com/games/20150327/LALTOR/gameinfo.html?ls=iref:nbahpts~~" +
  "http://Themeforest.net/item/-punjify-corporate-muse-template/10869789~~" +
  "http://newcar.xcar.com.cn/1932/?zoneclick=101425~~" +
  "http://www.360.cn/mac/~~" +
  "http://www.telegraph.co.uk/finance/alex~~" +
  "http://www.spiegel.de/panorama/germanwings-flugzeugabsturz-die-letzten-minuten-von-flug-4u9525-a-1025910.html~~" +
  "http://fivethirtyeight.com/datalab/march-madness-crib-notes-sweet-16-games/~~" +
  "http://app.autohome.com.cn/apps/~~" +
  "http://guoqing.china.com.cn/node_7127917.htm~~" +
  "http://hea.china.com/jiadian/news/11025684/20150130/19264879.html~~" +
  "http://Codecanyon.net/item/woocommerce-extra-product-options/7908619~~" +
  "http://vod.pl/programy-tv/sa-wardega-cardog-for-animals-w4rdoge/6l51sq~~" +
  "http://article.pchome.net/content-1793630.html~~" +
  "http://ultrabook.pchome.net/convertible/~~" +
  "https://secure.photobucket.com/print/photogifts~~" +
  "http://g.csdn.net/5272731~~" +
  "http://insider.espn.go.com/insider/espn-the-magazine/~~" +
  "http://www.webmd.com/click?url=http://www.medicinenet.com/~~" +
  "http://help.sogou.com/~~" +
  "http://news.china.com/social/1007/20150327/19432009.html~~" +
  "http://www.washingtonpost.com/politics/federal-government~~" +
  "http://badoo.com/privacy/~~" +
  "http://video.sina.com.cn/m/txqkl_63444063.html~~" +
  "http://animalcareers.about.com~~" +
  "http://berita-bca.liputan6.com~~" +
  "http://www.bitauto.com/yanan/~~" +
  "http://Adf.ly/abuse~~" +
  "http://azeizle.tistory.com/2250~~" +
  "http://www.deviantart.com/tag/waterdragon~~" +
  "http://love.163.com/home?vendor=163.home.rightadtitle&utm_source=home.163.com&utm_campaign=163~~" +
  "http://superwifi.rakuten.co.jp/?scid=wi_0_00461_~~" +
  "http://cancer.39.net/zxywq/~~" +
  "http://www.dnspod.cn~~" +
  "http://www.tudou.com/list/ach8a-2b-2c1760d-2e-2f-2g-2h-2i-2j-2k-2l-2m-2n-2sort2.html~~" +
  "http://diy.pconline.com.cn/display/~~" +
  "http://www.gome.com.cn/product/A0005186756-pop8005555317.html?intcmp=sy-C-5-2-4-j~~" +
  "http://car.autohome.com.cn/price/brand-47.html~~" +
  "http://newcar.xcar.com.cn/162/?zoneclick=101402~~" +
  "http://stock.eastmoney.com/news/1406,20150328491159240.html~~" +
  "http://club.xywy.com/askquestion.php?fromurl=xywyshouye1~~" +
  "http://www.engadget.com/gallery/windows-10-technical-preview-for-phones~~" +
  "http://wholesale.alibaba.com/HotDeals?tracelog=wc_hp15~~" +
  "http://Avito.ru//www.avito.ru/bryanskaya_oblast~~" +
  "https://www.mediafire.com/software/desktop/~~" +
  "http://www.irs.gov/News-&-Events~~" +
  "http://xiangtan.ganji.com/~~" +
  "http://www.oracle.com/us/products/index.html~~" +
  "http://s.b5m.com/s/Search?key=%E5%8C%BB%E8%8D%AF&isKnn=0~~" +
  "http://car.bitauto.com/haixing/~~" +
  "http://product.pchome.net/notebook_thinkpad_thinkpadnewx1carbon20a7s00900/414221.html~~" +
  "http://Stackoverflow.com/questions/tagged/csv~~" +
  "http://good.ci123.com/tudou/detail.php?id=980~~" +
  "http://info.xcar.com.cn/201503/news_1774860_1.html~~" +
  "http://www.forbes.com/sites/jmaureenhenderson/~~" +
  "http://www.linkedin.com/directory/people-q~~" +
  "http://www.linkedin.com/directory/people-m~~" +
  "http://www.tripadvisor.com/Hotels-g34636-Siesta_Key_Florida-Hotels.html~~" +
  "http://electronics.woot.com/?ref=gh_el_2_s_txt~~" +
  "http://detail.zol.com.cn/vga/s2139/~~" +
  "http://Amazon.com/b?ie=UTF8&node=13786411~~" +
  "http://price.xcar.com.cn/serise1270/city9999-1-1.htm?zoneclick=101413~~" +
  "http://tabelog.com/kyoto/~~" +
  "http://www.39.net~~" +
  "http://pages.samsung.com/ca/thesamsungstore/English/~~" +
  "http://www.washingtonpost.com/realestate~~" +
  "http://www.zillow.com/blog/pro/~~" +
  "http://www.microsoft.com/en-us/default.aspx?NavToggle=True&navitemid=navflyout5&navsubitemid=navflyout5-child2~~" +
  "http://v.opahnet.com/nba/v741222.html~~" +
  "http://q.mama.cn/~~" +
  "http://lady.163.com/photo/~~" +
  "http://dvsend.china.com/cc/WZL00http://culture.china.com/zt/zonghe/tonghua/~~" +
  "http://bola.kompas.com/ligainggris~~" +
  "http://site.douban.com/huazhou/~~" +
  "http://network.pconline.com.cn/625/6255496.html~~" +
  "https://Eksisozluk.com/basliklar/gundem~~" +
  "http://www.enet.com.cn/ilife/~~" +
  "http://www.reuters.com/article/2015/03/28/us-france-crash-idUSKBN0MN11N20150328~~" +
  "http://www.autohome.com.cn/drive/201503/864948.html~~" +
  "http://s.b5m.com/s/Search?key=%E7%94%9F%E6%B4%BB%E6%9D%82%E8%B4%A7&isKnn=0~~" +
  "http://home.babytree.com/u/u3466575119/j/13266890~~" +
  "http://rd.nicovideo.jp/cc/nicotop_blomaga/mediaarlist~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1343~~" +
  "http://www.theguardian.com/australia-news/live/2015/mar/28/nsw-state-election-2015-mike-baird-and-luke-foley-prepare-for-first-results-live~~" +
  "http://mashable.com/2015/03/27/amanda-knox-conviction-overturned/~~" +
  "http://wangzhan.360.cn/?p=360cn~~" +
  "http://twitter.com/jabongindia~~" +
  "http://www.lady8844.com/zhuanti/ss/ccmt/2009-04-24/1240538681d241149.html~~" +
  "http://www.gome.com.cn/category/cat10000181-00-0-48-1-0-0-0-1-0-0-1-0-0-0-0-0-0.html~~" +
  "http://www.ign.com/videos/2015/03/28/zombie-survival-tips-from-dead-rising-watchtowers-cast~~" +
  "http://italianfood.about.com~~" +
  "http://newcar.xcar.com.cn/auto/index.php?r=dealerPopw/order&pserid=1168&did=0&city_id=&type=1&is_cms=91~~" +
  "http://article.pchome.net/content-1793473.html~~" +
  "http://chinapic.people.com.cn/forum.php?mod=viewthread&tid=5690789&fromuid=492160~~" +
  "http://product.pchome.net/digital_dc/list_1_103_pm16445_p1.html~~" +
  "http://www.spiegel.de/thema/ernaehrung~~" +
  "http://baike.pcbaby.com.cn/qzbd/1018836.html~~" +
  "http://www.aliexpress.com/category/200010207/smart-wristbands.html?shipCountry=all&shipFromCountry=&shipCompanies=&SearchText=&minPrice=&maxPrice=&minQuantity=&maxQuantity=&isFreeShip=n&isFavorite=n&isRtl=n&isOnSale=n&isBigSale=n&similar_style=n&similar_style_id=&isAtmOnline=n&CatId=200010207&isrefine=y~~" +
  "http://eatingdisorders.about.com~~" +
  "http://politics.people.com.cn/GB/8198/394884/index.html~~" +
  "http://Codecanyon.net/make_money/become_an_author~~" +
  "https://itunes.apple.com/us/app/techcrunch/id526058642?mt=8~~" +
  "http://detail.b5m.com/item.html?docid=17cd2479869e080cfdbf0fb11e5437f2~~" +
  "http://games.xfinity.comcast.net/games/dethtris/~~" +
  "http://photo.xuite.net/oldkuang/19460691~~" +
  "https://plus.google.com/share?url=http://forum.xda-developers.com/android/themes/theme-tazzed-1-0-t3065768~~" +
  "http://taiyuan.bitauto.com/cheshi/~~" +
  "http://s.b5m.com/s/Search?key=%E7%B2%AE%E6%B2%B9%E9%80%9F%E9%A3%9F&isKnn=0~~" +
  "http://inhealth.cnn.com/coping-with-an-hiv-diagnosis/7-tips-for-taking-anti-hiv-drugs/?did=t1_rss1d~~" +
  "http://video.eastmoney.com/gsbb/play_9752.html~~" +
  "http://feedburner.google.com/fb/a/mailverify?uri=ettoday/global&loc=zh_TW~~" +
  "http://blog.eastmoney.com/neimuxiaoxi~~" +
  "http://www.cbssports.com/golf/blog/eye-on-golf/tag/1960756/eye-on-golf-equipment~~" +
  "http://news.xinhuanet.com/edu/2015-03/28/c_127631002.htm~~" +
  "https://twitter.com/paytm~~" +
  "http://www.lady8844.com/zhuanti/ss/ccmt/2007-04-17/1176795029d68777.html~~" +
  "http://Stackoverflow.com/questions/29314984/searching-for-subdocument-in-elastic-search~~" +
  "http://www.woot.com/?ref=gh_w_1_s_txt~~" +
  "http://www.huffingtonpost.ca/tv/~~" +
  "http://Wunderground.com/climate/extremes.asp~~" +
  "http://yyk.39.net/search/st2/abeijing/c_3~~" +
  "http://news.163.com/air/15/0328/12/ALPVC65700014P42.html~~" +
  "http://www.mama.cn/ask/?g=Gift~~" +
  "http://baike.pcbaby.com.cn/qzbd/948937.html~~" +
  "http://chuangxin.china.com.cn/~~" +
  "https://www.capitalone.com/redirect/?dest=http%3A%2F%2Fad.doubleclick.net%2Fclk%3B279376911%3B106491180%3Bk%3Fhttp%3A%2F%2Fwww.sharebuilder.com%2Faffiliates%2F%3FPC%3Dsb%2526SID%253D320052930019367%2526ANYURL%253Dhttps%253A%252F%252Fresearch.sharebuilder.com%252Fsharebuilder%252Ffindinvestments%252Foverview%2526cmpid%253DCOF_S_InvTab_OutLinkL2%2526mcid%253DCOF_W_NAV0514&Log=1&EventType=Link&ComponentType=T&LOB=MTS%3A%3AL0RT6ME8Z&PageName=Home+Page+C&PortletLocation=2&ComponentName=primary_nav&ContentElement=IN-L-2%3BFind+Investments&TargetPageName=http%3A%2F%2Fad.doubleclick.net%2Fclk%3B279376911%3B106491180%3Bk%3Fhttp%3A%2F%2Fwww.sharebuilder.com%2Faffiliates%2F%3FPC%3Dsb%2526SID%253D320052930019367%2526ANYURL%253Dhttps%253A%252F%252Fresearch.sharebuilder.com%252Fsharebuilder%252Ffindinvestments%252Foverview%2526cmpid%253DCOF_S_InvTab_OutLinkL2%2526mcid%253DCOF_W_NAV0514&Log=1&EventType=Link&ComponentType=T&LOB=MTS%3A%3AL0RT6ME8Z&PageName=Home+Page+C&PortletLocation=2&ComponentName=primary_nav&ContentElement=IN-L-3%3BFind+Investments&TargetPageName=%2Fredirect%2F%3Fdest%3Dhttp%253A%252F%252Fad.doubleclick.net%252Fclk%253B279376911%253B106491180%253Bk%253Fhttp%253A%252F%252Fwww.sharebuilder.com%252Faffiliates%252F%253FPC%253Dsb%252526SID%25253D320052930019367%252526ANYURL%25253Dhttps%25253A%25252F%25252Fresearch.sharebuilder.com%25252Fsharebuilder%25252Ffindinvestments%25252Foverview%252526cmpid%25253DCOF_S_InvTab_OutLinkL2%252526mcid%25253DCOF_W_NAV0514%26Log%3D1%26EventType%3DLink%26ComponentType%3DT%26LOB%3DMTS%253A%253AL0RT6ME8Z%26PageName%3DHome%2BPage%2BC%26PortletLocation%3D2%26ComponentName%3Dprimary_nav%26ContentElement%3DIN-L-2%253BFind%2BInvestments%26TargetPageName%3Dhttp%253A%252F%252Fad.doubleclick.net%252Fclk%253B279376911%253B106491180%253Bk%253Fhttp%253A%252F%252Fwww.sharebuilder.com%252Faffiliates%252F%253FPC%253Dsb%252526SID%25253D320052930019367%252526ANYURL%25253Dhttps%25253A%25252F%25252Fresearch.sharebuilder.com%25252Fsharebuilder%25252Ffindinvestments%25252Foverview%252526cmpid%25253DCOF_S_InvTab_OutLinkL2%252526mcid%25253DCOF_W_NAV0514~~" +
  "http://bbs1.people.com.cn/board/60.html~~" +
  "http://Stackoverflow.com/questions/tagged/phonegap-plugins~~" +
  "http://ent.sina.com.cn/f/CCTVDLLDQ/video/?opsubject_id=enttopnews~~" +
  "http://womeninbusiness.about.com~~" +
  "http://star.lady8844.com/~~" +
  "http://www.6pm.com/girls-shoes~eU~~" +
  "http://s.kouclo.com/search.php?c=2329,%E9%A5%AE%E6%B0%B4%E6%9C%BA~~" +
  "http://baike.pcbaby.com.cn/qzbd/1118448.html~~" +
  "http://special.pcbaby.com.cn/zhufu/yurenjie/xiaohua/~~" +
  "http://videos.marca.com/v/COc8ZJkIWiA-godin-se-sincera-en-marca.html~~" +
  "http://www.aliexpress.com/category/200004504/ndsi-ndsl.html~~" +
  "http://www.enet.com.cn/cpu/alist0_3_2.html~~" +
  "http://article.pchome.net/content-1793351.html~~" +
  "http://guba.eastmoney.com/list,601628.html~~" +
  "http://carnaval.uol.com.br/~~" +
  "http://www.dell.com/~~" +
  "http://xyq.163.com/~~" +
  "http://city.bitauto.com~~" +
  "http://www.walmart.com/cp/Games-Game-Room/4191?povid=P1171-C1110.2784+1455.2776+1115.2956-L227~~" +
  "http://www.xywy.com/about/mtbd.html~~" +
  "http://moz.com/community/recommended~~" +
  "http://www.mama.cn/baby/fenmian/shengchanji/~~" +
  "http://www.xcar.com.cn/tag/20.html~~" +
  "http://wenku.it168.com/huiyi/~~" +
  "http://yyk.39.net/search/t2/ltyanke~~" +
  "http://product.pconline.com.cn/nbbag/~~" +
  "http://www.cnet.com/profiles/cnet+news+staff/~~" +
  "http://Slickdeals.net/deals/apparel/~~" +
  "http://www.telegraph.co.uk/sponsored/motoring/subaru-outback-test-drive/?WT.mc_id=tmgspk_td_605981_8596&utm_source=tmgspk&utm_medium=td&utm_content=605981&utm_campaign=tmgspk_td_605981_8596~~" +
  "http://titan.babytree.com/delivery/ck.php?n=aa97a7d5&cb=5898~~" +
  "http://fuquan.xcar.com.cn/~~" +
  "http://www.yelp.co.uk/sf~~" +
  "http://guoqing.china.com.cn/node_7129582.htm~~" +
  "http://photo.china.com.cn~~" +
  "http://bbs1.people.com.cn/post/2/1/2/146209465.html~~" +
  "http://movie.douban.com/subject/4154632/~~" +
  "http://dingzhou.58.com/~~" +
  "http://www.alibaba.com/Security-Protection_p30~~" +
  "http://www.telegraph.co.uk/sport/football/teams/england/11500533/England-vs-Lithuania-five-things-we-learned-Michael-Carrick-is-Englands-best-holding-midfielder.html~~" +
  "http://www.tudou.com/albumplay/9YboLaK8G78/-sEtmFLysdk.html~~" +
  "http://www.sina.com.cn/license/map2011.html~~" +
  "http://ent.china.com/star/news/11052670/20150324/19415023.html~~" +
  "http://www.privatehomeclips.com/videos/i-am-intend-to-show-my-floozy-what-real-anguish-is-all-about/?pqr=19:ca02e299655209f5097abfd1528e3e5b:0:241851:1~~" +
  "http://auto.huanqiu.com/globalnews/2015-03/6015866.html~~" +
  "http://news.163.com/photoview/00AP0001/87284.html~~" +
  "http://facebook.com/alexiatsotsis~~" +
  "http://www.santillana.com.br/~~" +
  "http://opinion.people.com.cn/n/2015/0328/c1003-26764786.html~~" +
  "http://club.autohome.com.cn/bbs/forum-c-528-1.html~~" +
  "http://news.qq.com/a/20150328/005951.htm?tu_biz=v1~~" +
  "http://Ettoday.net/news/20120521/47941.htm~~" +
  "http://zx.39.net/lx/~~" +
  "http://onet.tv/p/tokrecimy/kaja-paschalska-jako-beyonce-w-twoja-twarz-brzmi-znajomo-bramkarz-fb-barcelona/x279fp~~" +
  "http://baike.pcbaby.com.cn/qzbd/1019260.html~~" +
  "http://Stackoverflow.com/questions/tagged/angularjs~~" +
  "http://www.slideshare.net/create?via=navbar_foundation~~" +
  "http://www.rakuten.co.jp/category/medicine/~~" +
  "http://hangzhou.zol.com.cn/~~" +
  "http://news.livedoor.com/topics/detail/9942640/~~" +
  "http://www.kaskus.co.id/forum/475/?ref=homelanding&med=forum_categories~~" +
  "http://homecooking.about.com/~~" +
  "http://product.pconline.com.cn/mobile/meizu/545708_comment.html~~" +
  "http://Ok.ru/help?st.cmd=helpFaq&st._aid=FatFooter_helpFaqAnonym~~" +
  "https://www.kickstarter.com/discover/categories/food~~" +
  "http://gmsx.gmw.cn/~~" +
  "http://www.kaskus.co.id/forum/79/?ref=homelanding&med=forum_categories~~" +
  "http://beauty.pclady.com.cn/~~" +
  "http://corporate.gameforge.com/en/partner_en/~~" +
  "http://www.flipkart.com/home-decor/clocks-wall-decor/clocks~~" +
  "http://bbs.ce.cn/bbs/viewthread.php?tid=1766085~~" +
  "http://finance.eastmoney.com/news/1365,20150328491196423.html~~" +
  "http://jbk.39.net/xjgs/~~" +
  "http://tennis.hupu.com/~~" +
  "http://buscartrabajo.empleo.monster.es/trabajos/?wt.mc_n=SP_NPCsearch&wt.mc_n=hjnpsearch&wt.mc_n=hjnpsearch&ch=ELPAIS&q=&re=130&cy=es&brd=1&rad=5~~" +
  "http://www.ppomppu.co.kr/guide/privacy.html~~" +
  "http://www.ebay.com/rpp/sporting-goods~~" +
  "http://www.fedex.com/cf/~~" +
  "http://www.usatoday.com/story/life/people/2015/03/27/two-more-cosby-accusers-come-forward/70563040/~~" +
  "http://activities.aliexpress.com/sport_shoes.php~~" +
  "https://Eksisozluk.com/abdde-evsizlerin-akil-sagliginin-yerinde-olmamasi--4737488?a=popular~~" +
  "https://www.citibank.co.id/portal/bahasa_home/index.htm~~" +
  "http://www.buzzfeed.com/kimberleydadds~~" +
  "http://www.rambler.ru/moscow_city/~~" +
  "https://www.kickstarter.com/signup?ref=nav~~" +
  "http://Avito.ru//www.avito.ru/chechenskaya_respublika~~" +
  "http://Amazon.com/Samsung-Galaxy-S6-Gold-Platinum/dp/B00V5M04OE~~" +
  "http://imgur.com/topic/Design_&_Art~~" +
  "http://toronto.craigslist.ca/search/cpg~~" +
  "http://www.lady8844.com/shoushen/ydss/2012-01-11/1326276625d956774.html~~" +
  "http://on.aol.com/show/517887470-city-ballet/518489860?icid=aolhomepage_rightrail~~" +
  "http://news.china.com.cn/shehui/node_7185032.htm~~" +
  "http://www.theguardian.com/business/2015/mar/27/helena-morrissey-30-percent-club-women-in-ftse100-boardroom~~" +
  "http://christianmusic.about.com~~" +
  "http://v.qq.com/cover/b/bo64ctd5rtyc2fi.html~~" +
  "http://www.gome.com.cn/category/cat16035545.html~~" +
  "http://mrbetsey.deviantart.com/art/When-the-working-day-is-done-424996545~~" +
  "http://bbs.hupu.com/12304020.html~~" +
  "http://home.woot.com/plus/abra-ca-barware?ref=gh_hm_4_wp_7~~" +
  "http://news.xinhuanet.com/video/2015-03/24/c_127612069.htm~~" +
  "http://weekend.rambler.ru/events~~" +
  "http://elpais.com/hemeroteca/elpais-america/portadas/2015/03/28/~~" +
  "http://baike.pcbaby.com.cn/qzbd/3433.html~~" +
  "http://diy.pconline.com.cn/621/6214736.html~~" +
  "http://funduszeue.wp.pl?utm_source=WP_SG&utm_medium=WP_SG_logo&utm_content=promo&utm_campaign=wp_support~~" +
  "http://travel.china.com/classroom/theme/PhotographicTravel/11119734/20150107/19182062.html~~" +
  "http://pad.pconline.com.cn/~~" +
  "http://store.steampowered.com/tag/en/Simulation/?snr=1_4_4__12~~" +
  "http://desktopvideo.about.com~~" +
  "http://www.webmd.com/news/breaking-news/future-of-health/advances-in-obesity-treatment~~" +
  "http://detail.zol.com.cn/price_cate_52.html~~" +
  "http://fashion.163.com/~~" +
  "http://www.washingtonpost.com/md~~" +
  "https://Eksisozluk.com/patric-young--2639504?a=popular~~" +
  "http://Themeforest.net/category/wordpress/ecommerce/jigoshop~~" +
  "http://article.pchome.net/content-1793701.html~~" +
  "http://www.tudou.com/programs/view/LyDs5BhdZlY/~~" +
  "http://astro.pclady.com.cn/horoscopes/sagittarius/~~" +
  "http://Ppomppu.co.kr/zboard/zboard.php?id=baseball~~" +
  "http://www.mama.cn/z/1100/~~" +
  "http://Addthis.com/~~" +
  "http://fund.eastmoney.com/company/80045188.html~~" +
  "https://aws.amazon.com/marketplace/pp/B00IO6H6KE/ref=mkt_ste_l2_analytics_f3?nc2=h_l3_al~~" +
  "http://techcrunch.com/2015/03/27/the-jury-has-reached-a-verdict-in-ellen-pao-vs-kleiner-perkins/~~" +
  "http://conference.caijing.com.cn/~~" +
  "http://noticias.uol.com.br/tabloide/~~" +
  "http://slide.book.sina.com.cn/slide_14_651_26909.html~~" +
  "http://tech.wp.pl/kat,1009659,title,dziejesiewtechnologii-51-Marsjanskie-odkrycie-smartfon-w-samochodzie-i-nowosc-Facebooka,wid,17393362,wiadomosc.html~~" +
  "http://libros.about.com~~" +
  "http://www.newegg.com/Store/PromotionStore/ID-2125004?name=Business-Desktop-Computers~~" +
  "http://www.spiegel.de/video/kevin-volland-deutschland-u21-spielt-em-in-tschechien-video-1566164.html~~" +
  "http://woman.39.net/nxspecial/sms083/~~" +
  "http://product.pconline.com.cn/mobile/smartisan/~~" +
  "http://www.naukri.com/tieups/tieups.php?othersrcp=14996~~" +
  "http://www.craigslistjoe.com/~~" +
  "http://www.hd315.gov.cn/beian/view.asp?bianhao=010202010031500016~~" +
  "http://www.6pm.com/~~" +
  "http://www.reddit.com/r/tifu/comments/30iplc/tifu_by_eating_gummy_bears_on_a_plane/~~" +
  "https://vimeo.com/dmca~~" +
  "http://my.xcar.com.cn/space.php?uid=8566452~~" +
  "http://yuedu.163.com/book_reader/c38fb2b319654e89b7d2bf9cd6cdf55c_4/c59642c47cf94bce9938749f5c31f153_4?utm_campaign=163ad&utm_source=163home&utm_medium=tab_0_3_3~~" +
  "http://info.xcar.com.cn/201503/news_1774165_1.html~~" +
  "http://www.dailymail.co.uk/tvshowbiz/article-3015011/I-night-Mario-cheated-Patti-Stanger-reveals-witnessed-RHONY-star-Ramona-Singer-s-ex-woman-Hamptons-party.html~~" +
  "http://www.slideshare.net/directory/user/o~~" +
  "https://customerservice.macys.com/app/answers/detail/a_id/137~~" +
  "http://car.autohome.com.cn/price/brand-46.html~~" +
  "http://roll.foxue.qq.com/?cata=jiangjing,shuofa,cathedra~~" +
  "http://udn.com/news/story/7489/793653~~" +
  "http://www.naukri.com/tieups/tieups.php?othersrcp=15020~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=661~~" +
  "http://Slickdeals.net/f/7757761-jbl-j55i-on-ear-headphones-with-mic-22-95-fs-on-neweggflash~~" +
  "http://fashion.gome.com.cn/?intcmp=fzc-sy-ad-8888~~" +
  "http://baike.pcbaby.com.cn/qzbd/1111081.html~~" +
  "http://event.rakuten.co.jp/sns/~~" +
  "http://baike.pcbaby.com.cn/qzbd/1129.html~~" +
  "http://product.pconline.com.cn/notebook/acer/~~" +
  "http://voice.hupu.com/cba/1895652.html~~" +
  "https://forums.craigslist.org/?areaID=25&forumID=15~~" +
  "http://www.tudou.com/listplay/pJE5Gzrb6js/vC0RQTcSiyM.html~~" +
  "http://fms.news.cn/swf/dqyxsdt2015/~~" +
  "http://xuzhou.bitauto.com/~~" +
  "http://products.office.com/en-ca/office-system-requirements~~" +
  "http://www.fedex.com/fr/~~" +
  "http://usa.chinadaily.com.cn/world/latinamerica.html~~" +
  "http://www.theverge.com/2015/3/26/8295177/microsoft-windows-apps-universal-apps~~" +
  "http://www.spiegel.de/einestages/the-cure-durchbruch-mit-a-forest-1980-a-1012274.html~~" +
  "http://baa.bitauto.com/sagitar/thread-3476597.html~~" +
  "http://wiadomosci.onet.pl/~~" +
  "http://www.chinatimes.com/newspapers/20150328001138-260603~~" +
  "http://yuedu.163.com/book_reader/bd_d81c7c69928b46fc980e457b911f0151_4/xiaoxiang_419822_4652208_4?utm_campaign=163ad&utm_source=163home&utm_medium=tab_0_1_2~~" +
  "http://life.china.com.cn/node_7219079.htm~~" +
  "http://music.douban.com/programme/438944~~" +
  "http://www.daqi.com/~~" +
  "http://www.babytree.com/tweet/topic.php?id=27023~~" +
  "http://down.chinaz.com/class/101_1.htm~~" +
  "http://food.tmall.com/?acm=tt-1141518-37004.1003.8.112964&uuid=112964&abtest=&act=4,2&scm=1003.8.tt-1141518-37004.OTHER_1412140607173_112964&pos=3~~" +
  "http://baike.pcbaby.com.cn/qzbd/1114279.html~~" +
  "http://baike.pcbaby.com.cn/qzbd/1276312.html~~" +
  "http://about.americanexpress.com/cr/?intlink=US-Homepage-FinancialEducation-NOJS~~" +
  "http://baike.pcbaby.com.cn/qzbd/7093.html~~" +
  "http://bola.kompas.com/foto~~" +
  "http://www.t-online.de/nachrichten/id_73448248/neun-tote-tote-bei-unwettern-in-chiles-wuestenregion.html~~" +
  "http://aws.amazon.com/mobileanalytics/?nc2=h_mo~~" +
  "http://www.urbandictionary.com/static.poweredby.php~~" +
  "http://emotion.lady8844.com/1178158/~~" +
  "http://kid.qq.com/fashionchildren/~~" +
  "http://price.xcar.com.cn/serise2781/city9999-1-1.htm?zoneclick=101412~~" +
  "http://www.theverge.com/2015/3/24/8281977/ellen-pao-kleiner-perkins-arguments-jury~~" +
  "http://ref.gamer.com.tw/0000216/*http://guild.gamer.com.tw/wikimenu.php?sn=9822~~" +
  "http://Ettoday.net/news/20120515/44438.htm?from=sidebar_mostlike~~" +
  "http://sj.zol.com.cn/ttqz/~~" +
  "http://pinterest.com/photobucket~~" +
  "http://bbs.lady8844.com/thread-1279594-1-2.html~~" +
  "http://chinajoy.pchome.net/~~" +
  "http://www.xe.com/currencyconverter/cobrand.php~~" +
  "http://www.primelocation.com~~" +
  "http://economia.uol.com.br/~~" +
  "http://subject.tmall.com/subject/subject.htm?id=1559030&abbucket=&acm=tt-1202890-40516.1003.8.225651&aldid=225651&gccpm=2137464.101.3.subject-13&abtest=&scm=1003.8.tt-1202890-40516.OTHER_1425840352370_225651&pos=1~~" +
  "http://bleacherreport.com/articles/2393843-2015-nba-mock-draft-full-two-round-projections-entering-ncaa-tournament~~" +
  "http://cosplaylove.lofter.com/?act=qbwysylofer_20150101_01~~" +
  "http://www.gome.com.cn/category/cat15046069-00-0-36-0-0-0-0-1-14br-0-0-0-0-0-0-0-0.html~~" +
  "http://money.163.com/15/0328/07/ALPEEHFU00251LIE.html~~" +
  "http://job.goo.ne.jp/search/all/cs-callcenter?rf=gtr195-35~~" +
  "http://experience.usatoday.com/food-and-wine/story/chicago/2015/02/23/chicago-ethnic-restaurants/23800577/~~" +
  "http://v.tudou.com/neonanmedia/~~" +
  "http://bollywood.bhaskar.com/news-hb/ENT-BNE-anushka-sharma-and-virat-kohli-return-from-sydney-together-4946415-NOR.html~~" +
  "http://Codecanyon.net/item/arabic-language-for-socialkit/10889590~~" +
  "http://blog.livedoor.com/blogneta/entry/227380~~" +
  "http://www.bankrate.com/credit-cards/airline-miles-cards.aspx?pid=p:cnbcx&ec_id=cmct_03_comm_PF_mtgcclink~~" +
  "http://www.wix.com/jobs/home~~" +
  "http://www.marca.com/2015/01/19/mas_deportes/nieve/1421670865.html~~" +
  "http://sale.kouclo.com~~" +
  "http://matome.naver.jp/odai/2141595383072664201~~" +
  "http://pages.samsung.com/ca/green/English/~~" +
  "http://www.athleta.com/products/womens-accessories.jsp~~" +
  "http://club.xywy.com/doc_card/9227757~~" +
  "http://imgur.com/gallery/b3E1sBq~~" +
  "http://kb.newegg.com/Policies/Article/1166~~" +
  "http://car.bitauto.com/dongnankelaisile/~~" +
  "http://edu.pcbaby.com.cn/resource/scb/yuwen/~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=662~~" +
  "http://www.softonic.com/descargar-programas-gratis/8~~" +
  "http://www.aliexpress.com/category/100006741/body-jewelry.html~~" +
  "http://www.nyaa.se/?page=download&tid=671088~~" +
  "http://newcar.xcar.com.cn/photo/ps2496/?zoneclick=101428~~" +
  "http://www.twitch.tv/p/developers~~" +
  "http://www.csdn.net/company/layer.html~~" +
  "http://www.indeed.com/how-the-world-works~~" +
  "http://corp.huanqiu.com/jobs/~~" +
  "http://s.taobao.com/search?initiative_id=staobaoz_20150126&tab=all&cps=yes&stats_click=search_radio_all%253A1&cat=50103029~~" +
  "http://www.wikipedia.org//fa.wikipedia.org/~~" +
  "http://www.icc-cricket.com/cricket-world-cup/teams/australia~~" +
  "https://www.iccquiz.com/~~" +
  "http://extratorrent.cc/torrent/4106380/XnSketch+Pro+v1.50+APK.html~~" +
  "http://sumaity.com/sell/~~" +
  "http://city.ifeng.com/~~" +
  "http://ypk.39.net/yaopin/kgm/79ad4.html~~" +
  "http://dvsend.china.com/cc/WZL00http://travel.china.com/~~" +
  "http://zx.39.net/anli/~~" +
  "http://www.alibaba.com/Soft-Drinks_pid202~~" +
  "http://www.walmart.com/cp/halloween-costumes/615760?povid=P1171-C1093.2766-L127~~" +
  "http://www.lazada.co.id/fashion-aksesoris/?child~~" +
  "http://newcar.xcar.com.cn/photo/ps1611/?zoneclick=101433~~" +
  "http://www.softonic.fr/~~" +
  "http://travel.163.com/15/0323/11/ALCVG7FK00063JSA.html~~" +
  "http://www.bitauto.com/youjia/~~" +
  "http://www.hotels.com/de1497539/hotels-chicago-illinois/~~" +
  "https://m2inet.icicibank.co.in/m2iNet/m2iNetLoginForm.jsp~~" +
  "http://s.taobao.com/search?initiative_id=staobaoz_20150126&tab=all&q=%CA%D6%C4%C3%B0%FC&cps=yes&stats_click=search_radio_all%253A1&cat=50006842~~" +
  "http://my.xcar.com.cn/space.php?uid=8776274~~" +
  "http://sports.china.com.cn/node_7214920.htm~~" +
  "http://ima.goo.ne.jp/word/%E7%9B%B8%E6%AC%A1%E3%81%90%E8%A1%9D%E6%92%83%E7%9A%84%E3%81%AA%E5%A0%B1%E9%81%93%E3%81%AB%E6%B3%A2%E7%B4%8B?from=gootop_side~~" +
  "http://weibo.com/1274469185/CaamIrIBS~~" +
  "http://www.chinaequip.gov.cn/index.htm~~" +
  "http://advertising.yandex.ru/?from=main_bottom~~" +
  "http://www.reimageplus.com/pc-tips-maintenance/~~" +
  "http://finance.huanqiu.com/roll/2015-03/6035221.html~~" +
  "https://www.wellsfargo.com/investing/retirement/ira/select~~" +
  "http://mp.weixin.qq.com/s?__biz=MjM5NDczMzQ0MQ==&mid=201829750&idx=3&sn=da498ddc646fa07a98e8f039741eca31&scene=1&key=2f5eb01238e84f7e391b16554635a25f179109c490f443e6ad4d16208f4ef30cb16fc100900cf926700d702b291f8032&ascene=1&uin=MTA5ODQ5MjY4MA==&devicetype=webwx&version=70000001&pass_ticket=bOus0WO3EnPF%2FE%2B2a3G1qOSwqxMlNmsWjFCYy9REOZD3w7QRW9y6Vt%2BnHlcY5nHz~~" +
  "http://www.espncricinfo.com/ci/content/video_audio/856501.html~~" +
  "http://cq.sina.com.cn/~~" +
  "http://bleacherreport.com/articles/2410031-ranking-the-nbas-best-former-2nd-round-picks-this-season~~" +
  "http://Amazon.com/Samsung-Galaxy-S6-White-Sprint/dp/B00V7FW8D4~~" +
  "http://help.jd.com/help/question-68.html~~" +
  "http://bbs1.people.com.cn/board/2.html~~" +
  "http://jd.zol.com.cn/511/5113272.html~~" +
  "http://dress.pclady.com.cn/zxzq/shipin/wanshi/~~" +
  "http://baby.iqiyi.com~~" +
  "http://detail.zol.com.cn/server/zhengrui/~~" +
  "http://Hdfcbank.com/personal/products/demat/demat-account?src=hp~~" +
  "http://properti.kompas.com/beranda~~" +
  "http://news.china.com.cn/2015-03/28/content_35180388.htm~~" +
  "http://www.sahibinden.com/arama/detayli~~" +
  "http://club.xywy.com/askquestion.php?did=48614858~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=344~~" +
  "http://www.indiatimes.com/news/india/when-he-refused-to-sell-his-700-year-old-quran-they-just-went-ahead-and-stole-it-231332.html~~" +
  "http://game.china.com/onlinegame/jiong/11083938/20150327/19436324.html~~" +
  "http://snowboarding.about.com~~" +
  "http://www.fedex.com/vu/~~" +
  "http://www.lofter.com/music163/?act=qbwysylofer_20150101_01~~" +
  "http://www.autohome.com.cn/3582/~~" +
  "http://www.ci123.com/index1.html~~" +
  "http://suihua.ganji.com/~~" +
  "http://www.thefreedictionary.com/about.htm~~" +
  "http://aol.it/facebook~~" +
  "http://www.woot.com/plus/projectors-accessories-8?ref=cnt_wp_4~~" +
  "http://www.imdb.com/title/tt2179136/trivia?item=tr2354418&ref_=hm_trv_sm~~" +
  "http://jianfei.39.net/thread-3587943-1.html~~" +
  "http://www.cricbuzz.com/cricket-scorecard/14686/karnataka-vs-tn-south-zone-syed-mushtaq-ali-trophy-2015~~" +
  "http://h10088.www1.hp.com/cda/gap/display/main/index.jsp?zn=gap&cp=20000-13698-16021_4041_100~~" +
  "http://www.yelp-ir.com/~~" +
  "http://bbs.gmw.cn/thread-3291356-1-1.html~~" +
  "https://wordpress.org//wordpress.org/showcase/tag/new-york-times/~~" +
  "http://wiki.jd.com/cate/122-0-1.html~~" +
  "http://tech.wp.pl/kat,130036,title,Tim-Cook-odda-caly-swoj-majatek,wid,17400089,wiadomosc.html~~" +
  "http://privatehomeclips.com/albums/categories/mature/~~" +
  "http://www.autohome.com.cn/news/201503/864140.html~~" +
  "http://beauty.pclady.com.cn/zxzq/luozhuang/hslz/~~" +
  "http://magazine.kakaku.com/mag/pc/id=2019/~~" +
  "http://pp.pcbaby.com.cn/photo/26594.html~~" +
  "http://www.tudou.com/albumplay/A4WsWRnVG2Q.html~~" +
  "http://kids.163.com/15/0327/06/ALMNEO0O00294MO6.html~~" +
  "http://yqk.39.net/bj/yaochang/69af7.html~~" +
  "http://lacittanuova.milano.corriere.it~~" +
  "http://www.kaskus.co.id/forum/108/?ref=homelanding&med=forum_categories~~" +
  "http://yyk.39.net/doctor/255488.html~~" +
  "http://s.b5m.com/s/Search?key=%E8%B0%83%E5%91%B3%E5%93%81&isKnn=0~~" +
  "http://www.woot.com/plus/canari-and-serfas-bike-apparel-shoes-3?ref=cnt_wp_19~~" +
  "http://Xe.com/currencytransfers/?WT.seg_1=XTR-340x38-XHOM-XIN-XX-V04-130301~~" +
  "http://www.autohome.com.cn/11079/0/1/conjunction.html~~" +
  "http://www.espncricinfo.com/ci/content/story/author.html?author=315~~" +
  "http://photo.auto.sina.com.cn/highindex.php?HDid=17589~~" +
  "http://www.nytimes.com/2015/03/22/opinion/sunday/brazils-dim-voice-on-the-world-stage.html~~" +
  "http://baobao.ci123.com/shiminlu~~" +
  "http://www.tudou.com/programs/view/3kx0dC5DoDI~~" +
  "https://joinexpedia.com/~~" +
  "http://www.theverge.com/2015/3/16/8219967/sxsws-gaming-expo-a-fan-convention-inside-a-brand-convention~~" +
  "http://product.enet.com.cn/list-34.html~~" +
  "http://www.ltn.com.tw/news/opinion/paper/866873~~" +
  "http://stock.eastmoney.com/news/1423,20150328491170667.html~~" +
  "http://www.slideshare.net/login?from=download&from_source=%2Fsavedfiles%3Fs_title%3Dhow20to20-write20a20cover20letter20that20gets20read3compressed%26user_login%3DOpportunityInsiders&download_id=46330378-7363542de7138c86d0596f5d96a02c687def81d3-slideshow~~" +
  "http://shiyong.ci123.com/main.php?action=try_single.html&id=724~~" +
  "http://baike.pcbaby.com.cn/qzbd/1105789.html~~" +
  "http://www.flipkart.com/q/kurtas-kurtis~~" +
  "http://event.rakuten.co.jp/disney/~~" +
  "http://jbk.39.net/dzhpx/~~" +
  "http://gretawire.foxnewsinsider.com~~" +
  "http://s.taobao.com/search?initiative_id=staobaoz_20150126&stats_click=search_radio_all%253A1&js=1&q=%E4%BC%91%E9%97%B2%E9%9E%8B&cat=50016853&suggest=cat_1&_input_charset=utf-8&wq=%E4%BC%91%E9%96%92%E9%9E%8B&suggest_query=%E4%BC%91%E9%96%92%E9%9E%8B&source=suggest&fs=1&olu=yes~~" +
  "http://newcar.xcar.com.cn/auto/index.php?r=dealerPopw/order&pserid=162&did=0&city_id=463&type=1&is_cms=92~~" +
  "http://diy.pconline.com.cn/623/6239717.html~~" +
  "http://www.forbes.com/newsletters/forbes-investor/~~" +
  "http://www.spiegel.de/karriere/berufsstart/polizei-kleine-bewerber-duerfen-nicht-ausgeschlossen-werden-a-1025896.html~~" +
  "http://go.microsoft.com/fwlink/?LinkID=246338&CLCID=1009~~" +
  "http://anyang.xcar.com.cn/~~" +
  "http://s.kouclo.com/search.php?c=4424,%E6%8C%82%E5%8E%86kouclo%E5%8F%B0%E5%8E%86~~" +
  "http://suihua.58.com/~~" +
  "http://www.t-online.de/digital/fotografie/id_18045204/tid_embedded/sid_43385764/si_0/fotografie-bilder-des-tages-jeden-tag-aktuelle-impressionen.html~~" +
  "http://Ask.fm/~~" +
  "http://www.funweek.it/people/cecilia-rodriguez-lite-con-francesco-monte-post-i.php?gallery=home&utm_source=libero&utm_medium=referral~~" +
  "http://www.mobile.de/modellverzeichnis/audi/r8.html~~" +
  "http://www.buzzfeed.com/chelseypippin/thats-love-bitch~~" +
  "https://aws.amazon.com/marketplace/ref=mkt_ste_l2_ec2?nc2=h_l3_bsa~~" +
  "http://www.rakuten.co.jp/category/fashion/~~" +
  "http://baicheng.xcar.com.cn/~~" +
  "https://www.adobe.com/privacy.html?promoid=KLXNG~~" +
  "http://wiadomosci.wp.pl/kat,1342,title,Adam-Hofman-Bronislaw-Komorowski-chce-zakazac-pytan-na-swoj-temat,wid,17401474,wiadomosc.html~~" +
  "http://personal.it168.com~~" +
  "http://Themeforest.net/category/wordpress/creative~~" +
  "http://www.rakuten.co.jp/ec/?camp=70110000000XyvK&scid=wi_ich_top_ave~~" +
  "http://products.verizonwireless.com~~" +
  "https://www.americanexpress.com/gift-cards/?intlink=USHP-LFC-GiftCard-NOJS~~" +
  "http://www.youm7.com/story/2015/3/28/%d8%a7%d9%84%d9%8a%d9%88%d9%85-%d8%a7%d9%84%d8%b9%d8%a7%d9%84%d9%85-%d9%8a%d8%b7%d9%81%d8%a6-%d8%a7%d9%84%d9%86%d9%88%d8%b1-%d8%b3%d8%a7%d8%b9%d8%a9-%d9%84%d8%aa%d9%88%d9%81%d9%8a%d8%b1-%d8%a7%d9%84%d8%b7%d8%a7%d9%82%d8%a9-%d9%88%d9%85%d9%88%d8%a7%d8%ac%d9%87%d8%a9-%d8%a7%d9%84%d8%a7%d8%ad%d8%aa%d8%a8%d8%a7%d8%b3-/2120201~~" +
  "http://s.taobao.com/search?q=%BB%AF%D7%B1%B0%FC&js=1&stats_click=search_radio_all%253A1&initiative_id=staobaoz~~" +
  "http://www.webtretho.com/category/3197-van-hoa-giai-tri~~" +
  "http://atsume.goo.ne.jp/~~" +
  "http://www.manager-magazin.de/~~" +
  "http://www.wikipedia.org//nov.wikipedia.org/~~" +
  "http://www.groupon.com/~~" +
  "http://photo.pclady.com.cn/pic/70471.html~~" +
  "http://Kickass.to/blog/r00tH4cK3r/post/a-few-things/~~" +
  "http://www.flickr.com/photos/yngw/16323718334/in/explore-2015-03-27/lightbox~~" +
  "http://sourceforge.net/projects/gnucash/?source=frontpage&position=1~~" +
  "http://fotki.yandex.ru/~~" +
  "http://newcar.xcar.com.cn/2737/~~" +
  "http://click.uol.com.br/?rf=home2011-rodape&u=http://clicklogger.rm.uol.com.br/?prd=247&grp=src:13;chn:0;creative:linkfixo_home2013_rodape;thm:produtosuol_uolprive&msr=Cliques%20de%20Origem:1&oper=11&redir=http://sexo.uol.com.br/?url=http://sexo.uol.com.br/prive~~" +
  "http://walmart.com/store/weekly-ads?povid=P1171-C1110.2784+1713.2781-L2~~" +
  "http://concursos.about.com~~" +
  "https://afisha.mail.ru/weekend/tv/?from=mr_news~~" +
  "http://health.udn.com/disease/disease_list~~" +
  "http://upload.zj.17173.com/ggcount/go.php?g_id=3870&g_url=http://news.17173.com/content/2015-03-27/20150327101442765.shtml?adref=adsid_15036_15248~~" +
  "http://www.taobao.com//www.taobao.com/sitemap.php~~" +
  "http://www.justjared.com/2015/03/28/jon-hamm-visits-the-smithsonian-in-honor-of-mad-men/~~" +
  "http://video.varzesh3.com/?p=75818~~" +
  "http://lady.163.com/baike/~~" +
  "http://list.tmall.com/spu_detail.htm?&spuid=319129142~~" +
  "http://s.taobao.com/search?cat=50018957&fs=1&initiative_id=staobaoz_20150126&tab=all&q=%B5%E7%BB%B0&cps=yes&stats_click=search_radio_all%253A1&olu=yes~~" +
  "http://www.tmz.com/videos?adid=sidebarwidget_tv_clips~~" +
  "http://www.tudou.com/listplay/qDa1DpoZFzU/UsK6zSiMJRU.html~~" +
  "http://elpais.com/elpais/2015/02/12/album/1423757863_006326.html~~" +
  "https://plus.google.com/share?url=http://www.tmz.com/2015/03/28/rich-homie-quan-boat-escape-fake-assault-miami/~~" +
  "http://bbs.notice.daum.net/gaia/do/service/top/list?bbsId=00015~~" +
  "http://car.bitauto.com/benchifangche/~~" +
  "http://ref.gamer.com.tw/0000160/*http://forum.gamer.com.tw/A.php?bsn=60539~~" +
  "http://dealer.pconline.com.cn/index.jsp~~" +
  "http://solferino28.corriere.it~~" +
  "http://www.privatehomeclips.com/videos/korean-lovers-1/?pqr=25:ca02e299655209f5097abfd1528e3e5b:0:16801:1~~" +
  "http://servicios.elpais.com/trafico/~~" +
  "http://wenku.it168.com/huiyi/2399~~" +
  "http://www.milliyet.com.tr/beyaz-show-27-mart-cuma--magazin-2034907/~~" +
  "http://zf.39.net/cs/~~" +
  "http://www.fedex.com/uy/~~" +
  "http://car.bitauto.com/aoling/~~" +
  "http://www.mama.cn/ask/jingxuan/1389/~~" +
  "http://bbs1.people.com.cn/post/2/0/0/146201963.html~~" +
  "http://m.cricbuzz.com/~~" +
  "http://www.ign.com/wikis/bloodborne/Hunter_Badges~~" +
  "http://www.npr.org/blogs/thesalt/~~" +
  "http://www.dailymail.co.uk/news/article-3013881/So-gravitas-portrait-oh-chic-Newsnight-presenter-Emily-Maitlis-spotty-tie-waistcoat-rolled-sleeves-outfit-raises-eyebrows.html~~" +
  "http://astro.pclady.com.cn/~~" +
  "http://www.urbandictionary.com//zh.urbandictionary.com/~~" +
  "http://www.theladbible.com/articles/basketball-player-accidentally-tells-journalist-he-thinks-she-is-beautiful-during-press-conference~~" +
  "http://ask.zol.com.cn/q/1202196.html~~" +
  "http://Slickdeals.net/f/7755299-propel-trampolines-12ft-trampoline-with-enclosure-trampoline-basketball-hoop-199-99-pu-in-store-sears~~" +
  "http://blog.eastmoney.com/dujia_1.html~~" +
  "http://muzyka.onet.pl/miejskie-emocje/bryan-adams-koncert-w-polsce-informacje-praktyczne,1,0,bq6rmh,artykul.html~~" +
  "http://dv.iqiyi.com~~" +
  "http://lohas.pclady.com.cn/~~" +
  "http://nokia-pc-suite.uptodown.com~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=671~~" +
  "http://finance.qq.com/a/20150328/006815.htm~~" +
  "http://www.taoche.com/baoma5xichangzhoujuban/~~" +
  "http://www.huffingtonpost.com/alastair-crooke~~" +
  "http://www.orbyt.tv~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=934~~" +
  "http://udn.com/news/story/6811/801652~~" +
  "http://newsblog.chinatimes.com/list/5/new~~" +
  "https://auto-verkaufen.mobile.de/anbieten/syi/index.html?vc=AgriculturalVehicle~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1306~~" +
  "http://www.imdb.com/toronto/?ref_=nv_ev_tff_9~~" +
  "http://www.gome.com.cn/product/9118630029.html~~" +
  "http://newcar.xcar.com.cn/758/?zoneclick=101409~~" +
  "http://rs.ci123.com/newup/item_43697.html~~" +
  "http://my.xfinity.com/articles/sports-general/20150327/Coyotes-Broadcaster.Arrested/~~" +
  "http://news.qq.com/a/20150328/024422.htm?tu_biz=1.114.2.1~~" +
  "http://www.xda-developers.com/htc-m9-roundup-availability-and-prices/~~" +
  "http://www.prisa.com~~" +
  "http://travel.163.com/food/~~" +
  "http://www.ebay.com/usr/southernhospitality2014~~" +
  "http://tech.china.com/hardware/11146539/20150309/19359174.html~~" +
  "http://price.xcar.com.cn/serise2737/city9999-1-1.htm?zoneclick=101436~~" +
  "http://ts.58.com/~~" +
  "http://www.news.cn/environment/~~" +
  "http://www.autohome.com.cn/advice/201503/863772.html~~" +
  "http://www.nba.com/video/games/raptors/2015/03/27/0021401080-lal-tor-play2.nba/index.html?ls=iref:nbahpts~~" +
  "http://jbk.39.net/ynsz/~~" +
  "http://www.focus.cn~~" +
  "http://magia.onet.pl/horoskop/zodiakalny,1/byk,620,dzienny,0,1.html~~" +
  "http://club.autohome.com.cn/bbs/thread-c-3521-39621544-1.html~~" +
  "https://aws.amazon.com/marketplace/b/2649337011/ref=mkt_ste_l2_S3CDN?page=1&category=2649337011&nc2=h_mo~~" +
  "http://price.pcauto.com.cn/sg10872/~~" +
  "http://article.kdslife.com/content_109381.html~~" +
  "http://www.washingtonpost.com/news/morning-mix/wp/2015/03/27/italian-high-court-overturns-amanda-knox-murder-conviction/~~" +
  "http://Stackoverflow.com/questions/29314937/ios-spritekit-rayline-is-reflected-from-bounds~~" +
  "http://shop1052140915.kouclo.com/~~" +
  "https://www.oracle.com/openworld/index.html~~" +
  "http://tabelog.com/tabelogpay/~~" +
  "http://islam.about.com~~" +
  "http://s.b5m.com/s/Search?key=%E4%BF%9D%E6%9A%96%E5%86%85%E8%A1%A3&isKnn=0~~" +
  "http://extratorrent.cc/article/4201/twitter+may+sell+tweets+to+data+miners.html~~" +
  "http://miiee.taobao.com/detail/c/20150316/290122.htm?banner=global~~" +
  "http://www.webtretho.com/forum/report.php?p=32937922~~" +
  "http://www.dailymotion.com/video/x2kcuvo_fritz-the-golden-is-terrible-at-catching-food_fun~~" +
  "https://produkte.web.de/~~" +
  "http://marketresearch.about.com~~" +
  "http://www.usatoday.com/weather/~~" +
  "http://yanbian.ganji.com/~~" +
  "http://www.avg.com/ca-en/sso?icid=ws-nav-sso~~" +
  "http://Kickass.to/auth/login/register/~~" +
  "http://car.bitauto.com/maibahe57/~~" +
  "http://news.xinhuanet.com/house/bj/2015-03-27/c_1114778753.htm~~" +
  "http://www.sahibinden.com/kategori/tarim-makineleri~~" +
  "http://baby.sina.com.cn/baobao/~~" +
  "http://www.gome.com.cn/product/A0004816141.html~~" +
  "http://toysgifts.gome.com.cn/~~" +
  "http://www.cimf.org.cn~~" +
  "https://www.etsy.com/shop/rabbitportal?ref=hp_trending?ref=hp_trending~~" +
  "http://www.webtretho.com/forum/f186/~~" +
  "http://lady.b5m.com/beauty/12165.html~~" +
  "http://newcar.xcar.com.cn/auto/index.php?r=dealerPopw/order&pserid=1506&did=0&city_id=85&type=1&is_cms=92~~" +
  "http://www.money.pl/gospodarka/wiadomosci/artykul/korupcja-w-brazylii-wyniszcza-gospodarke-w,177,0,1746609.html~~" +
  "https://office.live.com/start/Excel.aspx?omkt=en%2DUS~~" +
  "http://www.fedex.com/pl/~~" +
  "http://www.privatehomeclips.com/videos/dominae-non-professional-clip-from-2-1-15-22-15/?pqr=32:4172e1fadc7ff77a9069eccbb6c7e3f5:8:243414:1~~" +
  "http://detail.zol.com.cn/air-condition/haier/~~" +
  "http://wessiler.kinja.com~~" +
  "http://fr.bongacams.com~~" +
  "http://Themeforest.net/category/ecommerce/miscellaneous~~" +
  "http://ref.gamer.com.tw/0000171/*http://acg.gamer.com.tw/acgDetail.php?s=74416~~" +
  "http://www.wikipedia.org//sd.wikipedia.org/~~" +
  "http://techcrunch.com/gadgets/~~" +
  "https://www.wellsfargo.com/jump/savings/make-saving-money-simpler~~" +
  "http://www.kaskus.co.id/classified/225/?ref=homelanding&med=fjb_categories~~" +
  "https://adfarm.mediaplex.com/ad/ck/21520-158535-3408-53~~" +
  "http://ref.gamer.com.tw/0000144/*http://forum.gamer.com.tw/A.php?bsn=24520~~" +
  "http://aws.amazon.com/partners/premier/?nc2=h_l2_p~~" +
  "http://dilkideal.snapdeal.com/?&MID=GutterBanner_Dilkideal~~" +
  "http://www.elpais.com/especial/massive-attack/~~" +
  "http://extratorrent.cc/torrent/4106741/%5BHorribleSubs%5D+Garo+-+The+Animation+-+24+%5B480p%5D.mkv.html~~" +
  "http://otomotif.liputan6.com/kategori/narsis~~" +
  "http://www.microsoft.com/en-us/default.aspx?NavToggle=True&navitemid=navflyout3&navsubitemid=navflyout3-child7~~" +
  "http://secure.milliyet.com.tr/redirect/Default.aspx?l=http%3a%2f%2fwww.acunn.com%2fvideo%2fiste-benim-stilim%2fiste-benim-stilime-veda-eden-isimler%2f295776%3futm_source%3dmilliyet_xml&z=197&i=2~~" +
  "http://www.telegraph.co.uk/finance/personalfinance/~~" +
  "http://renshi.people.com.cn/n/2015/0327/c139617-26761043.html~~" +
  "http://s.b5m.com/s/Search?key=%E5%BA%A7%E5%9E%AB%2F%E5%BA%A7%E5%A5%97&isKnn=0~~" +
  "http://www.flipkart.com/kids-corner~~" +
  "http://iservice.ltn.com.tw/Service/english/english.php?engno=861727&day=2015-03-11~~" +
  "https://www.Surveymonkey.com/mp/aboutus/office-locations/~~" +
  "http://club.astro.sina.com.cn/thread-2055385-1-1.html~~" +
  "http://about.mama.cn/join.html~~" +
  "https://www.kickstarter.com/projects/495527381/re-claim?ref=home_featured~~" +
  "http://animal959595.pixnet.net/blog/post/404094028~~" +
  "http://good.ci123.com/tudou/bounce.php?id=1091~~" +
  "http://sd.china.com.cn/~~" +
  "http://www.ca.kayak.com/flight-routes/Vancouver-Intl-YVR/San-Francisco-SFO~~" +
  "http://www.slideshare.net/directory/content/t~~" +
  "http://toronto.craigslist.ca/search/jwa~~" +
  "http://www.slideshare.net/directory/content/x~~" +
  "http://www.spiegel.de/politik/ausland/suedafrika-bundeswehr-beschiesst-versehentlich-motorboot-a-1026011.html~~" +
  "http://www.washingtonpost.com/entertainment/tv/so-long-suze-orman-show-tvs-only-sane-space-in-a-money-crazed-culture/2015/03/27/068c9524-d331-11e4-a62f-ee745911a4ff_story.html~~" +
  "http://shop.cbssports.com/source/BOX~~" +
  "http://news.xinhuanet.com/shuhua/2015-03/28/c_127631630.htm~~" +
  "http://www.mama.cn/ask/jingxuan/1535/~~" +
  "http://www.fromthetop.org~~" +
  "http://www.geek.com/~~" +
  "http://price.pcauto.com.cn/sg1053/~~" +
  "https://account.nicovideo.jp/register?sec=common_header&mode=landing~~" +
  "http://www.usatoday.com/topic/c29a7dd4-db9d-4a3a-bedd-e746edaf542a/~~" +
  "http://espn.go.com/video/clip?id=12571363&categoryid=2378529~~" +
  "http://bbs.zol.com.cn/huodong/d2_24567.html~~" +
  "http://techcrunch.com/video/tc-cribs/~~" +
  "http://newcar.xcar.com.cn/photo/ps1550/?zoneclick=101420~~" +
  "http://www.tudou.com/listplay/rsj38dmphqI/gOyQnZtJOd4.html~~" +
  "http://chinapic.people.com.cn/forum.php?mod=viewthread&tid=5690470~~" +
  "http://oversea.huanqiu.com/~~" +
  "http://www.tudou.com/home/_728378059/~~" +
  "http://detail.zol.com.cn/product_new/~~" +
  "http://biznes.pl/magazyny/finanse/polskie-wplatomaty-na-kolkach-zrobily-furrore-w-nowym-jorku/4x3eet~~" +
  "http://www.tudou.com/home/beautycate/~~" +
  "http://baike.pcbaby.com.cn/qzbd/7640.html~~" +
  "http://newcar.xcar.com.cn/2447/?zoneclick=101413~~" +
  "https://www.scribd.com/terms~~" +
  "http://www.reimageplus.com/refund-policy/~~" +
  "http://www.autohome.com.cn/drive/201503/864823.html~~" +
  "http://www.chinaz.com/special~~" +
  "http://esporte.uol.com.br/futebol/times/santa-cruz/~~" +
  "http://Slickdeals.net/f/7744675-playstation-vita-170-amazon-with-free-shipping~~" +
  "http://www.target.com/tdir/p/home-patio-garden/-/N-5xtq9~~" +
  "http://Techcrunch.com/events/~~" +
  "http://lifehacker.com/5684996/what-alcohol-actually-does-to-your-brain-and-body~~" +
  "http://blog.ask.com~~" +
  "http://app.sina.com.cn/appdetail.php?appID=108869&f=p_binfen&w=p_binfen~~" +
  "http://www.yyc.co.jp/";

exports.prefGestaltPS = prefGestaltPS;
