const prefGestaltPS =
  "http://www.reuters.com/news/video?videoChannel=1004~~" +
  "http://tvrehberi.milliyet.com.tr/Default.aspx?aType=TvRehberiAramaSonucTV2012&tarih=28.3.2015&kanal=kanal+d&ref=milliyet_anasayfa~~" +
  "http://militaryhistory.about.com~~" +
  "http://g1.globo.com/goias/noticia/2015/03/mae-diz-nao-entender-motivo-que-levou-marido-agredir-bebe-em-go.html~~" +
  "http://ww.chinaz.com/aboutus/contact.php~~" +
  "http://www.telegraph.co.uk/comment/10948796/Paedophilia-is-natural-and-normal-for-males.html~~" +
  "http://car.bitauto.com/zhongdaxingche/~~" +
  "http://health.pclady.com.cn/fz/aqq/~~" +
  "http://s.b5m.com/s/Search?key=%E8%B6%B3%E7%90%83%E9%9E%8B&isKnn=0~~" +
  "http://www.marca.com/en/2015/03/27/en/football/international_football/1427445176.html~~" +
  "http://www.imdb.com/news/ni58443240/?ref_=nv_nw_tn_2~~" +
  "https://www.youtube.com/watch?v=dv_gOBi8Wpk~~" +
  "http://Ettoday.net/news/20120520/47795.htm~~" +
  "http://www.abs-cbnnews.com/porkscam~~" +
  "https://www.pixnet.net/blog/profile/cameragirlcarmen~~" +
  "http://www.theguardian.com/index/subjects/a~~" +
  "http://air.pchome.net/~~" +
  "http://www.milliyet.com.tr/cikolata-kisti-gebeligi-etkiliyor-pembenar-detay-hamilelikhazirligi-2034915/~~" +
  "http://www.dailymail.co.uk/tvshowbiz/article-3015375/Sia-Furler-continue-concealing-identity-famous-wig-reveals-choice-adopt-signature-hairstyle-inspired-Amy-Winehouse.html~~" +
  "http://www.goodreads.com/choiceawards/best-fiction-books-2014~~" +
  "http://www.mama.cn/z/5554/~~" +
  "http://www.autohome.com.cn/3170/~~" +
  "http://chaozhou.ganji.com/~~" +
  "http://aws.amazon.com/rds/?nc2=h_mo~~" +
  "http://y.autohome.com.cn/redirect/18/~~" +
  "http://www.nytimes.com/pages/realestate/index.html~~" +
  "http://yp.xcar.com.cn/201503/news_1774088_1.html~~" +
  "http://www.alibaba.com/help/contact-us.html~~" +
  "http://yyk.39.net/hospital/23953_lab.html~~" +
  "http://news.xinhuanet.com/video/2015-03/23/c_127603754.htm~~" +
  "http://sellout.woot.com/?ref=gh_so_11_s_lgo~~" +
  "http://xfinity.comcast.net/slideshow/entertainment-misheardlyrics/?cid=hero_media~~" +
  "http://www.he.xinhuanet.com/zfwq/baoding/~~" +
  "https://www.kickstarter.com/help/faq/kickstarter+basics?ref=footer~~" +
  "http://www.cnet.com/products/apple-ipad-mini-3/~~" +
  "http://jbk.39.net/npx/~~" +
  "http://Ettoday.net/news/20120521/48029.htm?from=footer_c2~~" +
  "http://car.bitauto.com/huachenjinbeis50/~~" +
  "https://twitter.com//dev.twitter.com~~" +
  "http://news.bitauto.com/dealer/20150328/1506521104.html~~" +
  "http://money.163.com/15/0328/14/ALQ6DHDU002551G6.html~~" +
  "http://www.homedepot.com/c/project_how_to_project_guides_bath~~" +
  "http://extratorrent.cc/view/popular/Games.html~~" +
  "http://product.pchome.net/office_all_in_one_canon_mg7580/pic_426549.html~~" +
  "http://www.cnbc.com/id/102531776?__source=xfinity|mod&par=xfinity~~" +
  "http://baike.pcbaby.com.cn/qzbd/940519.html~~" +
  "http://www.t-online.de/unterhaltung/tv/id_61636284/germany-s-next-topmodel-2015-news-infos-zur-10-staffel-gntm.html~~" +
  "http://bbs.zol.com.cn/nbbbs/c1.html~~" +
  "http://article.pchome.net/n163/s1/1.html~~" +
  "http://www.ndtv.com/photos/entertainment/sidharth-ranveer-s-terrific-tuesday-19322~~" +
  "http://prom.gome.com.cn/html/prodhtml/topics/201503/qczxxsgcjjj.html~~" +
  "http://www.snapdeal.com/products/kitchen-bathroom-fittings-sanitaryware/filters/Type_s~Wash%20Basins%20Counter%20Tops~~" +
  "http://qu.ebay.com/survey?srvName=Home%20Page%20(eBay%20Today%20Homepage)~~" +
  "https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fbudgettravel.about.com%2Fod%2Fhowtobeabudgettraveler%2Fss%2F5-Great-Travel-Buys.htm%3Futm_source%3Dfacebook%26utm_medium%3Dsocial%26utm_campaign%3Dshareurlbuttons~~" +
  "http://q.xcar.com.cn/111303/~~" +
  "https://play.google.com/store/apps/details?id=com.shutterstock.consumer~~" +
  "http://Taboola.com/~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1354~~" +
  "http://www.engadget.com/2015/03/27/night-vision-eyedrops/~~" +
  "http://www.t-online.de/sport/fussball/em/id_73444000/deutsche-nationalmannschaft-gegen-georgien-unter-druck.html~~" +
  "http://en.canoe.ca/home.html~~" +
  "http://article.pchome.net/n456/s3/1.html~~" +
  "http://www.autohome.com.cn/3457/~~" +
  "http://app.mama.cn/babyrecord.html~~" +
  "http://Ppomppu.co.kr/zboard/view.php?id=freeboard&no=4099732~~" +
  "http://car.bitauto.com/shuanghuansceo/~~" +
  "http://events.youku.com/mggt/~~" +
  "http://resorts.disney.go.com/aulani-hawaii-resort/?CMP=AFC-DPFY13Q1DIENT1377F~~" +
  "http://zdm.b5m.com/shihui/24542.html~~" +
  "http://qd.ifeng.com/special/mykalmla/~~" +
  "http://www.subito.it/~~" +
  "http://Ok.ru/dk?st.cmd=anonymMain&cmd=lang&lang=ka&st._aid=FatFooter_changeLang~~" +
  "http://Ppomppu.co.kr/zboard/zboard.php?id=hotissue~~" +
  "http://www.privatehomeclips.com/videos/gay00097/?pqr=32:ca02e299655209f5097abfd1528e3e5b:0:65207:1~~" +
  "http://zhanzhang.cnzz.com/~~" +
  "http://www.corriere.it/tecnologia/blog/~~" +
  "http://www.trulia.com/for_rent/Atlanta,GA/~~" +
  "http://en.gameforge.com/profile/show/Alexej-19066~~" +
  "http://event.rakuten.co.jp/food/shipping/~~" +
  "http://price.pcauto.com.cn/sg11765/~~" +
  "http://product.pchome.net/diy_portablespeaker/list_8_716.html~~" +
  "http://blender.stackexchange.com/questions/tagged/cycles~~" +
  "http://dvsend.china.com/cc/AN000http://food.china.com/ZTmenu/2012SP/2013wenxiangshijiu03/index.html~~" +
  "http://film.onet.pl/kinowe-premiery-tygodnia-fanka-gunman-odkupienie-rozdzieleni-i-inne/wky3e2~~" +
  "http://wuwei.ganji.com/~~" +
  "http://shaotong.xcar.com.cn/~~" +
  "http://kids.163.com/15/0327/09/ALN0F83S00294MO6.html~~" +
  "http://www.santillanausa.com/~~" +
  "http://www.citibank.co.th/~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1045~~" +
  "http://www.ppomppu.co.kr/zboard/zboard.php?id=tour~~" +
  "http://baike.pcbaby.com.cn/qzbd/959711.html~~" +
  "http://academia.stackexchange.com/users/32352/marty~~" +
  "http://www.bild.de/bild-plus/sport/mehr-sport/boxen/falscher-doping-konrolleur-bei-box-em-40333346.bild.html~~" +
  "http://baike.pcbaby.com.cn/qzbd/1127719.html~~" +
  "http://televisao.uol.com.br/noticias/redacao/2015/03/27/ator-de-house-of-cards-manda-recado-a-brasileiros-que-reclamam-de-spoiler.htm~~" +
  "http://www.nba.com/nycstore/?ls=iref:nba:gfooter~~" +
  "http://news.liputan6.com/read/2198634/cerita-seorang-ibu-yang-anaknya-kerap-dibantu-olga-syahputra~~" +
  "http://www.people.com.cn/GB/208743/index.html~~" +
  "http://shuozhou.ganji.com/~~" +
  "http://newcar.xcar.com.cn/car/0-0-0-0-71-0-0-0-0-0-0-0/&zoneclick=101571~~" +
  "http://coffeetea.about.com~~" +
  "http://food.bj.sina.com.cn/album/tag/3493944833/~~" +
  "https://plus.google.com/share?url=http://forum.xda-developers.com/xposed/modules/mod-compact-volume-panel-cm12-aosp-t3065053~~" +
  "http://look.huanqiu.com/article/2015-03/6026472.html~~" +
  "http://www.newegg.com/Networking/Category/ID-281~~" +
  "http://car.bitauto.com/iveco/~~" +
  "http://s.taobao.com/search?q=%D0n%E4h%D2%C2&js=1&stats_click=search_radio_all%253A1&initiative_id=staobaoz_20150127~~" +
  "http://news.xinhuanet.com/edu/2015-03/28/c_127631558.htm~~" +
  "http://www.bhaskar.com/news/CEL-celebrity-children-and-their-different-profession-4935163-PHO.html~~" +
  "http://travel.163.com/15/0325/08/ALHQA84R00064M1B.html~~" +
  "http://www.spiegel.de/thema/euro_krise_2010/~~" +
  "https://www.flipkart.com/account/~~" +
  "http://home.mobile.de/regional/~~" +
  "http://time.com/sports/~~" +
  "http://investor.shutterstock.com/~~" +
  "http://matome.naver.jp/topic/1MCNm~~" +
  "http://Amazon.com/gp/help/customer/display.html?ie=UTF8&nodeId=468520~~" +
  "https://www.tumblr.com/policy/~~" +
  "http://yiwu.bitauto.com/~~" +
  "http://www.buzzfeed.com/alexcampbell/protesters-to-demand-release-of-battered-woman-in-oklahoma~~" +
  "http://misetoku.kakaku.com/misetoku/info/detail.aspx?mt_companycd=1087S&mt_prid=P000000013&lid=misetoku_kakakutop_center_prdetail~~" +
  "http://legal.gmw.cn/2015-03/28/content_15229428.htm~~" +
  "http://mingjia.eastmoney.com/guihaoming/index.html~~" +
  "http://store.steampowered.com/app/318130/?snr=1_4_4__tab-PopularNewReleases~~" +
  "http://Codecanyon.net/category/php-scripts/add-ons~~" +
  "http://dictionary.reference.com/slideshows/baby-animals~~" +
  "http://bbs.360safe.com/thread-5469211-1-1.html~~" +
  "http://female.kompas.com/bugarsehat~~" +
  "http://gopuertorico.about.com~~" +
  "http://eladies.sina.com.cn/feel/~~" +
  "http://www.mama.cn/ask/user/9468619.html~~" +
  "http://miiee.taobao.com/detail/c/20150320/290305.htm?banner=global~~" +
  "http://www.capitalone.com/small-business-bank/cash-management/?Log=1&EventType=Link&ComponentType=T&LOB=MTS%3A%3AL0RT6ME8Z&PageName=Home+Page+C&ComponentName=primary_nav&ContentElement=BS-L-6%3BCash+Flow+Management&TargetLob=MTS%3A%3ALVFX4215&TargetPageName=Cash+Management+Overview&referer=https%3A%2F%2Fwww.capitalone.com%2Fhomepage~~" +
  "http://abc.go.com/shows~~" +
  "http://www.nyaa.se/?page=view&tid=671040~~" +
  "http://servicios.elpais.com/el-tiempo/playas.html~~" +
  "http://www.4shared.com/remindPassword.jsp~~" +
  "http://www.autohome.com.cn/tuning/201503/864571.html~~" +
  "http://www.reimageplus.com/how-does-it-work/~~" +
  "http://heavymetal.about.com~~" +
  "http://count.shopping.t-online.de/RE?ID=73421628&CID=64417616&FID=C1&GID=64756648&URL=http%3A%2F%2Fad.doubleclick.net%2Fddm%2Fclk%2F289185287%3B116166574%3Bw~~" +
  "http://ref.gamer.com.tw/0000144/*http://forum.gamer.com.tw/A.php?bsn=26686~~" +
  "http://activities.aliexpress.com/anniversary_sale_round_1/electronics.php~~" +
  "http://gshow.globo.com/bbb/bbb15/noticias/noticia/2015/03/adrilles-interrompe-papo-e-diz-que-fernando-ama-amanda.html~~" +
  "http://www.fedex.com/lt/~~" +
  "http://www.huffingtonpost.com/women/~~" +
  "http://skateboard.about.com~~" +
  "http://s.b5m.com/s/Search?key=%E5%85%B6%E4%BB%96%E5%81%A5%E5%BA%B7%E7%94%B5%E5%99%A8&isKnn=0~~" +
  "http://www.trulia.com/agents/~~" +
  "http://health.people.com.cn/n/2015/0328/c14739-26764362.html~~" +
  "http://www.tudou.com/home/tongtongjiang/~~" +
  "http://www.tripadvisor.com/Hotels-g55711-Dallas_Texas-Hotels.html~~" +
  "http://js1.eastmoney.com/tg.aspx?ID=1365~~" +
  "http://matome.naver.jp/odai/2142750884849836701~~" +
  "http://geography.about.com~~" +
  "http://dot.wp.pl/redir?SN=dpp&url=http%3A%2F%2Fpgo.wp.pl%2F%3Frev%3Dwp_wp_sg~~" +
  "http://bbs.hupu.com/cavaliers~~" +
  "http://car.bitauto.com/gtbycitroeumln/~~" +
  "http://www.taoche.com/dongfengbentiancrv/~~" +
  "http://Amazon.com/Samsung-Galaxy-S6-Edge-Platinum/dp/B00V5M0VV0~~" +
  "https://www.crunchbase.com/organization/weissenhaus?utm_source=tc_river&utm_medium=export&utm_campaign=dataset~~" +
  "http://baike.pcbaby.com.cn/qzbd/1109796.html~~" +
  "http://www.xbox.com/en-ca~~" +
  "http://office.pconline.com.cn/625/6256438.html~~" +
  "http://newcar.xcar.com.cn/price/?zoneclick=101404~~" +
  "http://www.nyaa.se/?offset=23~~" +
  "http://www.dailymail.co.uk/tvshowbiz/article-3014075/Rumer-Willis-shows-flat-stomach-toned-arms-workout-gear-arrives-DWTS-studios.html~~" +
  "http://guba.eastmoney.com/list,000157.html~~" +
  "http://newcar.xcar.com.cn/201503/news_1768869_1.html~~" +
  "http://www.iqiyi.com/v_19rrnmuxmg.html~~" +
  "http://acc.pconline.com.cn/626/6264471.html~~" +
  "http://budgeting.about.com~~" +
  "http://search.rakuten.co.jp/search/mall/-/100467/~~" +
  "http://article.pchome.net/n609/s18/1.html~~" +
  "http://news.xinhuanet.com/politics/2015-03/27/c_1114790595.htm~~" +
  "http://ask.ci123.com/users/show/1098485~~" +
  "http://car.bitauto.com/lancia/~~" +
  "http://privatehomeclips.tumblr.com/~~" +
  "http://kids.163.com/special/fumuzh17/~~" +
  "http://www.zillow.com/advice/US/zillow-questions/question-discussion-guide/~~" +
  "http://car.bitauto.com/fengyi/~~" +
  "http://veetle.com/~~" +
  "http://www.tudou.com/albumplay/RObSdLGoXQc.html~~" +
  "http://club.xywy.com/tagcloud/16090~~" +
  "http://busycooks.about.com~~" +
  "http://www.pchouse.com.cn/baike/shenghuo/2058/~~" +
  "http://Themeforest.net/category/site-templates/personal~~" +
  "http://www.yelp.com/oakland~~" +
  "http://in.rediff.com/~~" +
  "http://car.bitauto.com/linkenmkx/~~" +
  "http://ranking.goo.ne.jp/ranking/category/022id/w1FltNQ5bJb2/~~" +
  "http://Ink361.com/app/my-uploads~~" +
  "https://www.chase.com/commercial-bank~~" +
  "http://blog.nicovideo.jp/niconews/ge_function/~~" +
  "https://www.capitalone.com/sign-in/?audienceType=MTS%3A%3AKV0LVIE8Z&Log=1&EventType=Link&ComponentType=T&LOB=MTS%3A%3AL0RT6ME8Z&PageName=Home+Page+C&ComponentName=primary_nav&ContentElement=XX-7%3BSign+In&TargetPageName=Online+Banking+Accounts+Login~~" +
  "http://www.cbmd.cn/~~" +
  "http://www.ppomppu.co.kr/zboard/zboard.php?id=animation~~" +
  "http://www.bitauto.com/jiaozuo/~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1391&zoneclick=101444~~" +
  "http://ima.goo.ne.jp/word/%E7%89%B9%E7%95%AA%E3%81%A7%E5%A4%A7%E3%83%91%E3%83%8B%E3%83%83%E3%82%AF%E3%81%AB?from=gootop_srchbox~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1282~~" +
  "http://blog.livedoor.com/sitemap/~~" +
  "http://deals.ebay.com/5001945137_Ricoh_WG_M1_Digital_Camera?_trksid=p2050601.m2174&_trkparms=~~" +
  "http://man.pclady.com.cn/123/1236637.html~~" +
  "http://baike.pcbaby.com.cn/qzbd/1115114.html~~" +
  "http://news.qq.com/a/20150328/026595.htm?tu_biz=v1~~" +
  "http://jipiao.jd.com/city/~~" +
  "http://nk.39.net/~~" +
  "http://bbs.hupu.com/12303755.html~~" +
  "http://js1.eastmoney.com/tg.aspx?ID=721~~" +
  "http://www.daum.net/doc/info_protection.html~~" +
  "http://brides.pclady.com.cn/zxzq/ht/~~" +
  "http://baike.pcbaby.com.cn/qzbd/1272192.html~~" +
  "http://hiking.about.com~~" +
  "http://www.flipkart.com/home-furnishing/bed/pillows/pr?sid=vdm,uj4,3me~~" +
  "http://food.39.net/sl/wxc~~" +
  "http://health.huanqiu.com/health_promotion/2015-03/6019157.html~~" +
  "http://www.hurriyet.com.tr/magazin/astroloji/burc.asp?bilgiType=gunluk&burc=basak&date=28-03-2015~~" +
  "http://article.pchome.net/content-1790537.html~~" +
  "http://s.b5m.com/s/Search?key=%E8%8A%B1%E8%8D%89%2F%E6%9E%9C%E8%8C%B6&isKnn=0~~" +
  "http://jbk.39.net/tnb/zztz/~~" +
  "http://www.speedtest.net/switch_language.php?lang=en~~" +
  "http://jck.39.net/jc/xxian.html~~" +
  "http://lifestyle.liputan6.com/kategori/life~~" +
  "http://baike.pcbaby.com.cn/qzbd/940492.html~~" +
  "http://shiyong.ci123.com/special/marcjenie3.php~~" +
  "http://trackandfield.about.com~~" +
  "http://www.expedia.com.ar~~" +
  "http://www.foxnews.com//www.foxnews.com/about/apps-downloads~~" +
  "http://www.nytimes.com/2015/03/29/opinion/sunday/can-data-stop-car-wrecks.html~~" +
  "http://Nih.gov/about/contact.htm~~" +
  "http://article.pchome.net/content-1788497.html~~" +
  "http://shop.gmarket.co.kr/funation/funmain.aspx~~" +
  "http://beauty.pclady.com.cn/zxzq/xmn/~~" +
  "http://pad.zol.com.cn/slide/513/5130370_1.html~~" +
  "http://www.pcbaby.com.cn/tools/tefygct/~~" +
  "http://jck.39.net/jiancha/huaxue/jyhqlxy/9c2c9.html~~" +
  "http://xbox.about.com~~" +
  "http://zhongshan.bitauto.com/~~" +
  "http://nanning.xcar.com.cn/~~" +
  "http://blog.ci123.com/yixinyisu/picture/2073149~~" +
  "http://scores.espn.go.com/mlb/scoreboard~~" +
  "http://Mashable.com/2013/02/~~" +
  "http://physics.stackexchange.com/questions/tagged/astronomy~~" +
  "http://jbk.39.net/jiancha/fkcsjc/~~" +
  "http://www.woot.com/plus/elenco-engino-construction-sets?ref=cnt_wp_14~~" +
  "http://diy.pconline.com.cn/622/6227797.html~~" +
  "http://travel.people.com.cn/GB/223858/index.html~~" +
  "http://car.bitauto.com/zhongtaiv10/~~" +
  "http://car.bitauto.com/aerfaluomiougtv/~~" +
  "http://lady.163.com/15/0323/11/ALCVVU8S00264N2N.html~~" +
  "http://www.aliexpress.com/wholesale?SearchText=Xiaomi+M4&spuId=7756002~~" +
  "http://photo.pclady.com.cn/pic/70282.html~~" +
  "http://guoqing.china.com.cn/node_7138433.htm~~" +
  "http://www.icc-cricket.com/cricket-world-cup/news~~" +
  "http://www.aliexpress.com/category/200002454/fragrances-deodorants.html~~" +
  "http://www.hpl.hp.com/~~" +
  "http://baike.pcbaby.com.cn/qzbd/8249.html~~" +
  "http://houston.cbslocal.com/category/sports/~~" +
  "http://product.pconline.com.cn/mobile/bubugao/578671.html~~" +
  "http://q.mama.cn/topic/17403980/~~" +
  "http://verona.corriere.it~~" +
  "http://money.163.com/special/licaipics/~~" +
  "http://www.ppomppu.co.kr/zboard/zboard.php?id=bike~~" +
  "http://www.taoche.com/bentengb50/~~" +
  "http://emotion.pclady.com.cn/zxzq/fenshou/~~" +
  "http://sanya.ganji.com/~~" +
  "http://bbs.hupu.com/12048227.html~~" +
  "http://www.cnet.com/how-to/how-to-embed-a-facebook-video-on-your-website/~~" +
  "http://www.bhaskar.com/himachal/?Menu-Him~~" +
  "http://www.webtretho.com/forum/report.php?p=32937861~~" +
  "http://www.wikipedia.org//wuu.wikipedia.org/~~" +
  "http://www.yelp.no/~~" +
  "http://www.soku.com/t/nisearch/%E5%9C%9F%E8%B1%86%E6%9C%80%E5%A8%B1%E4%B9%90~~" +
  "http://bbs.chinaz.com/forum-167-1.html~~" +
  "http://www.indiatimes.com/news/world/this-muslim-hooker-marries-their-clients-for-the-night-for-sinfree-sex-231305.html~~" +
  "http://hexian.58.com/~~" +
  "http://www.aliexpress.com/category/200001112/skiing.html~~" +
  "http://product.pchome.net/office_all_in_one/list_11_228_108.html~~" +
  "http://newcar.xcar.com.cn/384/~~" +
  "http://promotions.newegg.com/nvidia/15-1352/index.html?cm_sp=Homepage_TopRightV1-_-nvidia%2f15-1352-_-http%3a%2f%2fpromotions.newegg.com%2fnvidia%2f15-1352%2f300x120.jpg&icid=308275~~" +
  "http://www.chinadaily.com.cn/iphone/newmedia.html~~" +
  "http://qdn.58.com/~~" +
  "http://ningde.bitauto.com/~~" +
  "http://data.eastmoney.com/xg/gh/default.html~~" +
  "http://baike.pcbaby.com.cn/qzbd/1028954.html~~" +
  "http://club.autohome.com.cn/bbs/thread-c-3080-37760843-1.html~~" +
  "http://news.gmw.cn/2015-03/20/content_15157557.htm~~" +
  "http://s.b5m.com/s/Search?key=%E5%A9%B4%E5%84%BF%E6%84%9F%E5%AE%98%E5%8F%91%E8%82%B2%E7%8E%A9%E5%85%B7&isKnn=0~~" +
  "http://www.ci123.com/weekly/~~" +
  "http://s.taobao.com/search?q=%CB%AF%B4%FC&js=1&stats_click=search_radio_all%253A1&initiative_id=staobaoz_20150127~~" +
  "http://blog.esuteru.com/archives/8109465.html~~" +
  "http://auto.ndtv.com/news/future-cars-may-run-on-agriculture-waste-750085?pfrom=home-auto~~" +
  "http://www.buzzfeed.com/lindsayn8/27-mouthwatering-ways-to-eat-a-rice-krispy-treat-e258~~" +
  "http://www.ganji.com/shoujipinpai/oppo/~~" +
  "http://global.eastmoney.com/news/1790,20150328491088334.html~~" +
  "http://s.kouclo.com/search.php?c=2578,%E6%B0%B4%E6%9D%AFkouclo%E9%A4%90%E5%85%B7~~" +
  "http://www.espncricinfo.com/icc-cricket-world-cup-2015/engine/series/509587.html~~" +
  "http://www.cnn.com/2015/03/28/africa/somalia-hotel-attack/index.html~~" +
  "http://realty.rambler.ru/?utm_source=rambler&utm_content=realty&utm_medium=topline2&utm_campaign=self_promo~~" +
  "http://dongxi.douban.com/category/nanzhuang/?dcs=anonymous-home-sidenav&dcm=douban~~" +
  "http://tv.sohu.com/s2013/hd/~~" +
  "http://news.163.com/15/0328/10/ALPPFVET00014JB6.html~~" +
  "http://www.autohome.com.cn/culture/201503/863160-15.html~~" +
  "http://cosme.pclady.com.cn/product/120726.html~~" +
  "http://finance.eastmoney.com/news/1344,20150328491176441.html~~" +
  "http://www.iqilu.com~~" +
  "http://wetter.spiegel.de/~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=472~~" +
  "http://news.qq.com/a/20150327/082925.htm?tu_biz=1.114.1.0~~" +
  "http://www.theladbible.com/articles/army-recruit-drops-grenade-in-training-and-has-life-saved-by-instructor~~" +
  "http://noticias.uol.com.br/internacional/~~" +
  "http://internships.about.com/~~" +
  "http://www.sahibinden.com/ozel-ders-verenler-bilgisayar~~" +
  "http://www.naukri.com/tieups/tieups.php?othersrcp=19677~~" +
  "http://www.wikipedia.org//rm.wikipedia.org/~~" +
  "http://baobao.ci123.com/a20061117~~" +
  "http://car.bitauto.com/sabo/~~" +
  "http://v.163.com/zixun/V8GAM8VMO/VAKP32O2L.html~~" +
  "http://s.b5m.com/daigoucart/center.htm?docId=bd4d76ae079978ac355fa1af9c25311d&ref=02~~" +
  "http://blog.gmw.cn/space-uid-38602.html~~" +
  "http://www.slideshare.net/thijsdevries~~" +
  "http://m.imdb.com?ref_=ft_mdot~~" +
  "http://roadwarriorvoices.com/~~" +
  "http://www.enet.com.cn/ydhl/alist8804.html~~" +
  "http://comcast.kayak.com/in?p=m2&url=%2Fpackages%2FPunta-Cana-Z23052%2F2015-04-24%2F2015-04-27%2F-1%2C-1%2F2%2F0%2C0%2C0%2F-~~" +
  "https://twitter.com/intent/favorite?tweet_id=541753988253626368~~" +
  "http://tabelog.com/hyogo/~~" +
  "http://car.bitauto.com/jincouxingche/~~" +
  "http://product.pchome.net/network_Internetbehaviour_management/list_9_441_1750.html~~" +
  "http://www.foxnews.com//www.foxnews.com/~~" +
  "http://edu.pcbaby.com.cn/resource/scb/banmian/~~" +
  "https://www.elance.com/r/contractors/cat-design-multimedia/ind-true~~" +
  "http://video.corriere.it/airbus-fiori-candele-luogo-disastro/bf2a96a4-d475-11e4-831f-650093316b0e~~" +
  "http://www.custojusto.pt/~~" +
  "http://Ok.ru/dk?cmd=logExternal&st.cmd=logExternal&st.link=http%3A%2F%2Fm.odnoklassniki.ru&st.name=accessibleVersion~~" +
  "http://www.dailymail.co.uk/tvshowbiz/index.html~~" +
  "http://resultados.elpais.com/mercados/indices/eurotop_100/2625/~~" +
  "http://ganzhou.xcar.com.cn/~~" +
  "http://money.163.com/15/0328/00/ALON5HJ400253B0H.html~~" +
  "http://blog.livedoor.jp/kaikaihanno/~~" +
  "http://www.dailymail.co.uk/tvshowbiz/article-3014732/Overdue-Jill-Duggar-husband-Derick-Dillard-share-baby-bump-update-ahead-engagement-anniversary.html~~" +
  "http://www.huffingtonpost.com/morena-duwe/serenity-gathering-2015_b_6958928.html?utm_hp_ref=entertainment&ir=Entertainment~~" +
  "http://www.spiegel.de/schulspiegel/ferientermine-a-193925.html~~" +
  "http://www.autohome.com.cn/culture/201503/864807-14.html~~" +
  "http://space.chinaz.com/361blog~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1352~~" +
  "http://car.bitauto.com/yingfeinidifx/~~" +
  "http://sjz.ganji.com/~~" +
  "http://forum.home.news.cn/list/80-0-0-1.html~~" +
  "http://www.fedex.com/cr/~~" +
  "http://firstaid.about.com~~" +
  "http://www.groupon.com/local/hair-salons~~" +
  "http://www.hb.xinhuanet.com/zhuanti/13three/jiangxia/index.html~~" +
  "http://edu.ce.cn/~~" +
  "http://baike.pcbaby.com.cn/qzbd/1246.html~~" +
  "http://matchcentre.starsports.com/cricket/icc-cricket-world-cup-2015-164/india-vs-australia-174026/live-video~~" +
  "https://www.facebook.com/privacy/explanation~~" +
  "http://bbs.hupu.com/pacers~~" +
  "http://www.imdb.com/news/ni58445087?ref_=hm_nw_cel4~~" +
  "http://product.pchome.net/network_network_card/list_9_168.html~~" +
  "http://2sc.sohu.com/evaluation/~~" +
  "http://yuedu.163.com/source/e79c476494e24eca9b016b3c46e7a2f9_4?utm_campaign=163ad&utm_source=163home&utm_medium=tab_2_3_5~~" +
  "http://Nih.gov/science/index.html~~" +
  "http://www.dailymail.co.uk/femail/article-3015120/Ivanka-Trump-shares-sweet-snap-one-year-old-son-Joseph-trying-sneak-way-suitcase-heads-business-trip.html~~" +
  "http://bbs.home.163.com/list/sheji.html~~" +
  "http://www.ncbi.nlm.nih.gov/pubmed/~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=534~~" +
  "http://health.china.com.cn~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1278~~" +
  "http://Ptt01.cc/PostCategory/id/31~~" +
  "http://detail.b5m.com/item.html?docid=5aa9bfce0928b8dfc88c0b28336c21e7~~" +
  "http://car.autohome.com.cn/pic/series/633.html~~" +
  "http://car.bitauto.com/aerfaluomiou/~~" +
  "http://www.odesk.com/cat/sales-marketing~~" +
  "http://servicios.elpais.com/podcast/~~" +
  "http://yyk.39.net/hospital/24496_lab.html~~" +
  "http://www.dailymail.co.uk/video/news/video-1167008/Thisll-bug-Epic-battle-beetle-scorpion.html~~" +
  "http://aws.amazon.com/storagegateway/?nc2=h_mo~~" +
  "http://www.engadget.com/reviews/external-drives/~~" +
  "https://graph.qq.com/oauth2.0/authorize?client_id=100253980&response_type=code&redirect_uri=http://passport.tianya.cn/login/qq.do~~" +
  "http://www.alibaba.com/Products~~" +
  "http://indeks.kompas.com/indeks/index/entertainment~~" +
  "http://kan.sina.com.cn/game/live/~~" +
  "http://gshow.globo.com/programas/ta-no-ar-a-tv-na-tv/especial-blog/ta-no-ar-a-tv-na-tv/1.html~~" +
  "http://www.spiegel.de/thema/spon_muenchau/~~" +
  "http://www.tudou.com/listplay/klcFr5h-4i8/572rYCEfWcU.html~~" +
  "http://detail.tmall.com/item.htm?spm=0.0.0.0.n9bRhz&id=40010075735~~" +
  "http://blogs.reuters.com/search/journalist.php?n=dan.levine~~" +
  "http://Xe.com/currencytransfers/?WT.seg_1=XTR-TL-XHOM-XIN-XX-V01-131001~~" +
  "http://shanghai.ci123.com~~" +
  "http://finance.qq.com/a/20150327/069958.htm~~" +
  "http://esporte.uol.com.br/futebol/times/atletico-pr/~~" +
  "http://www.teepr.com/211437/%e7%99%bd%e8%b2%93%e7%9c%8b%e5%88%b0%e5%b0%8f%e5%ac%b0%e5%85%92%e5%b0%b1%e8%a6%81%e6%8a%8a%e6%89%8b%e4%bc%b8%e9%80%b2%e7%83%a4%e7%ae%b1%e8%a3%a1%e4%ba%86%ef%bc%8c%e4%b8%8b%e4%b8%80%e7%a7%92%e5%a5%b9/~~" +
  "http://www.marca.com/futbol/equipos/atletico.html~~" +
  "https://point.goo.ne.jp/j/ssc/staticContents/show/ga_01~~" +
  "http://cit2012.pixnet.net/blog/post/189249969~~" +
  "http://beauty.pclady.com.cn/zxzq/faxing/faxingfengge/~~" +
  "http://autos.udn.com/topic/car/news/article_directory.jsp?type=newsM&f_SUB_ID=48~~" +
  "http://nb.zol.com.cn/511/5118307.html~~" +
  "http://fashion.ifeng.com/body/~~" +
  "http://Hdfcbank.com/personal/ways-to-bank/bank-in-person/cashshop~~" +
  "http://event.rakuten.co.jp/inner/catalog/mens/~~" +
  "http://pinterest.com/pin/create/button/?url=http%3A%2F%2Fgardening.about.com%2Fod%2Fvegetablepatch%2Fss%2FThe-6-Fastest-Growing-Vegetables.htm%3Futm_source%3Dpinterest%26utm_medium%3Dsocial%26utm_campaign%3Dshareurlbuttons&description=The+6+Fastest-Growing+Vegetables&media=http%3A%2F%2Ff.tqn.com%2Fy%2Fgardening%2F1%2FS%2F_%2FV%2F1%2F149819586.jpg~~" +
  "http://www.engadget.com/reviews/digital-media-players/~~" +
  "http://beauty.pclady.com.cn/127/1279885.html~~" +
  "http://www.starsports.com/f1/leagues/competitionid=10000008/index.html~~" +
  "https://vimeo.com/watch~~" +
  "http://www.milliyet.tv/video-izle/Sinematik-27-03-2015-jlbi29K2gf4w-sinema/~~" +
  "http://www.autohome.com.cn/tuning/~~" +
  "http://prom.gome.com.cn/html/prodhtml/topics/201503/ryxcjcyou.html~~" +
  "http://g1.globo.com/carros/tabela-fipe/index.html~~" +
  "http://journalism.about.com~~" +
  "http://www.autohome.com.cn/3554/~~" +
  "http://tvuol.uol.com.br/videos/m146023/editorial/~~" +
  "http://aws.amazon.com/storagegateway/?nc2=h_l3_sc~~" +
  "http://news.rambler.ru/29785343/~~" +
  "http://astro.pclady.com.cn/horoscopes/love/lovers/~~" +
  "http://chenbinblog.blog.163.com/blog/static/206258047201522710512632/~~" +
  "http://newcar.xcar.com.cn/auto/index.php?r=dealerPopw/order&pserid=16&did=0&city_id=475&type=1&is_cms=92~~" +
  "http://www.mama.cn/z/1127/~~" +
  "http://www.espncricinfo.com/syed-mushtaq-ali-trophy-2015/engine/match/776053.html~~" +
  "http://www.cnn.com/shows/cnn-films~~" +
  "http://opinion.people.com.cn/GB/364827/index.html~~" +
  "http://weightloss.about.com/~~" +
  "http://www.tmz.com/photos/2015/03/27/guess-who-wwe-throwbacks~~" +
  "http://www.t-online.de/nachrichten/id_73448596/eu-will-pkw-maut-gesetz-erst-nach-inkrafttreten-pruefen.html~~" +
  "http://www.bobo.com/?f=163.homeChannel~~" +
  "http://bola.liputan6.com/kategori/jadwal-live-streaming-bola~~" +
  "http://www.yelp.com/biz/sous-beurre-kitchen-san-francisco-2~~" +
  "http://www.pchome.net/network_network_card/list_9_168.html~~" +
  "http://tvhub.wikia.com/wiki/TV_Hub~~" +
  "https://www.capitalone.com/redirect/?dest=http%3A%2F%2Fwww.sharebuilder.com%2Faffiliates%2F%3FPC%3Dsb%26SID%3D640048343031777%26MGDURL%3Dxcof%2Fira%2Ftiered%2Findex.htm%253Fxcode%253DTAX%26cmpid%3DCOF_S_WWW%26MCID%3DCOF_HP_TILE_PreppingFuture_600_031015&Log=1&EventType=Link&ComponentType=G&LOB=MTS::L0RT6ME8Z&SubLob=&PageName=Home+Page+C&PortletLocation=4%3B16-col%3B4-3-1&ComponentName=could-you-save-on-taxes-pos3-n%3B10&ContentElement=3%3B%2Fmedia%2Fgraphic-logo%2Fhomepage%2Ftile-cof-tax-season-50x60.png&TargetPageName=http%3A%2F%2Fwww.sharebuilder.com%2Faffiliates%2F%3FPC%3Dsb%26SID%3D640048343031777%26MGDURL%3Dxcof%2Fira%2Ftiered%2Findex.htm%253Fxcode%253DTAX%26cmpid%3DCOF_S_WWW%26MCID%3DCOF_HP_TILE_PreppingFuture_600_031015~~" +
  "http://product.pchome.net/mobile_phone_meizu_mx4g/406410.html~~" +
  "http://enbrasil.about.com~~" +
  "http://auto.163.com/15/0328/09/ALPLDBAA00084TV1.html~~" +
  "http://baike.pcbaby.com.cn/qzbd/7571.html~~" +
  "http://www.bbc.co.uk/sport/0/football/~~" +
  "http://www.usatoday.com/travel/roadwarriors/~~" +
  "http://nb.zol.com.cn/513/5133284.html~~" +
  "http://www.imdb.com/title/tt2224026?ref_=hm_otw_t1~~" +
  "http://www.reddit.com/r/Music/~~" +
  "https://join.booking.com?lang=en-us&aid=304142;label=HeaderInfoMenu;~~" +
  "http://www.wix.com/website-template/view/html/1008?originUrl=http%3A%2F%2Fwww.wix.com~~" +
  "http://music.stackexchange.com/users/7356/shevliaskovic~~" +
  "http://world.people.com.cn/~~" +
  "http://futures.eastmoney.com/~~" +
  "http://news.yandex.ru/~~" +
  "http://buyer.alibaba.com/intelligence?tracelog=beacon_ti_140704~~" +
  "http://baike.pcbaby.com.cn/qzbd/368.html~~" +
  "http://zx.39.net/mgs/~~" +
  "http://www.dailymotion.com/CraveOnline~~" +
  "http://s.b5m.com/s/Search?key=%E6%8A%95%E5%BD%B1%E6%9C%BA&isKnn=0~~" +
  "https://www.odesk.com/o/jobs/~~" +
  "http://www.nidcd.nih.gov/~~" +
  "http://www.lady8844.com/zhuanti/hf/mb/2008-11-26/1227695821d192032.html~~" +
  "http://www.sahibinden.com/skoda~~" +
  "http://www.iqiyi.com/v_19rrhv2zrg.html~~" +
  "http://www.newegg.com/Mobile-Hot-Spots/SubCategory/ID-2959~~" +
  "http://Stackoverflow.com/questions/tagged/liquid~~" +
  "https://m.onlinesbi.com/mretail/login.htm~~" +
  "http://www.starsports.com/privacy/index.html~~" +
  "http://new.livejasmin.com/en/girl/white+ladies?session=g13ca65df7ee4cd0d8dbb8d6d5659c89c?selectedFilters=5~~" +
  "http://ardamax-keylogger.uptodown.com~~" +
  "http://tv.sohu.com/s2014/laura1/~~" +
  "http://3docean.net/?osr=tn~~" +
  "http://bbs.zol.com.cn/diybbs/d34443_4241.html~~" +
  "http://military.people.com.cn/n/2015/0328/c1011-26763892.html~~" +
  "http://www.elpais.com/deportes/futbol/competicion/champions/~~" +
  "http://www.spiegel.de/forum/netzwelt/notel-boom-nordkorea-hardware-fuer-den-widerstand-thread-264146-1.html~~" +
  "http://www.tiramillas.net/?cid=MENUPROD35603&s_kw=tiramillas~~" +
  "http://builtfromscratch.homedepot.com/~~" +
  "http://count.shopping.t-online.de/RE?ID=73442666&CID=72666256&FID=C5&GID=64756648&URL=http%3A%2F%2Fwww.t-online.de%2Freisen%2Fid_13114344%2Fferienwohnung-oder-ferienhaus-mieten-bei-t-online-de-reisen-.html~~" +
  "http://produto.mercadolivre.com.br/MLB-639601666-lote-de-selos-do-brasil-sem-repetico-e-outros-itens-confira-_JM~~" +
  "https://www.twitter.com/wikihow~~" +
  "http://psiphon.uptodown.com~~" +
  "http://gameyay.com~~" +
  "http://www.gome.com.cn/product/A0005123355.html~~" +
  "http://photo.hupu.com/nba~~" +
  "http://elpais.com/tag/tour_francia/a/~~" +
  "http://www.autohome.com.cn/tuning/201503/865955.html~~" +
  "http://www.baike.com/~~" +
  "http://c.nfa.jd.com/adclick?keyStr=z5AXFoIimt1jiDK32+w4mY2B9TVUsepgbhEVVeBcfyxglzMD894kOhxO5+A1fNgX7V/TLHgwQr/mSYq4m4DRSbNpdkiuien9W9o10aTQUTla4eG9P+LQ+i7XDdn0nvJz1oEwRbUsC6tQMin70asoRxbRsrFAsoN3B4SAPH1Bq12eUFgWVA0lkR6QFf0yEWOr8/6WKnA+SZ3AxEIWIpogIrhmxh2Y3AU9XUrVnJY0DRaaNlYR6q849hP06bIVvMArWuiHSVI0yCkZsMFLMiuRUlwZIgJhNQ2QfP+SgF74yPEWrrA9GwAn8POZ+atr1AgC&cv=2.0&url=http://sale.jd.com/mall/dx1Yk3SVrbR.html~~" +
  "http://www.microsoft.com/en-us/default.aspx?NavToggle=True&navitemid=navflyout5&navsubitemid=navflyout5-child1~~" +
  "http://www.iqiyi.com/u/video~~" +
  "http://detail.zol.com.cn/notebook_index/subcate16_160_list_1.html~~" +
  "http://bbs.hupu.com/12302130.html~~" +
  "http://photo.pclady.com.cn/pic/70373.html~~" +
  "http://aws.amazon.com/ecs/?nc2=h_mo~~" +
  "http://www.iqiyi.com/a_19rrhc3oc9.html~~" +
  "http://www.huffingtonpost.com/sasha-bronner/called-myself-a-bitch-and-then-thought-twice-about-it_b_6959440.html?utm_hp_ref=entertainment&ir=Entertainment~~" +
  "http://oa.zol.com.cn/~~" +
  "http://bbs1.people.com.cn/post/1/1/2/146211570.html~~" +
  "http://www.babytree.com/community/club201509/~~" +
  "http://www.huffingtonpost.ca/2015/03/24/phil-robertson-duck-dynasty-hate-speech_n_6934164.html?utm_hp_ref=mostpopular~~" +
  "https://bitly.com/pages/links~~" +
  "http://finance.eastmoney.com/news/1374,20150328491095331.html~~" +
  "http://www.aliexpress.com/category/200004934/human-hair.html?pvId=14-200661256&isrefine=y~~" +
  "http://www.quantcast.com/p-b3sGjMtCFrexE~~" +
  "http://blog.ci123.com/qingtian12/entry/1660030~~" +
  "http://caipiao.hupu.com/~~" +
  "http://www.dailymail.co.uk/news/article-3014666/Christian-baker-sued-refusal-make-gay-marriage-cake.html~~" +
  "http://www.shouyouribao.com~~" +
  "http://healthfinder.gov/FindServices/default.aspx~~" +
  "http://www.walmart.com/cp/546511?povid=P1171-C1110.2784+1455.2776+1115.2956-L237~~" +
  "http://mashable.com/2015/03/27/sriracha-flavored-foods/~~" +
  "http://aws.amazon.com/java/?nc2=h_l2_d~~" +
  "http://www.naukri.com/tieups/tieups.php?othersrcp=15772~~" +
  "http://showbiz.liputan6.com/kategori/kpop~~" +
  "http://dcclub.pchome.net/thread-6664434-1-1.html~~" +
  "http://yuedu.163.com/book_reader/aa850a75d0e94c54bff22a446537a57b_4/200e909dc36c428b8a6e10b888ab1e85_4?utm_campaign=163ad&utm_source=163home&utm_medium=tab_0_3_6~~" +
  "http://huawei.csdn.net~~" +
  "http://www.alibaba.com/Underwear_pid100005804~~" +
  "http://channel.jd.com/pet.html~~" +
  "http://cul.qq.com/a/20150328/014139.htm~~" +
  "http://zibo.ci123.com~~" +
  "http://www.114koubei.com~~" +
  "http://www.nytimes.com/upshot/~~" +
  "http://bleacherreport.com/articles/2410511-for-russell-wilson-is-baseball-a-dream-or-a-future-reality~~" +
  "https://www.onlinesbiglobal.com/~~" +
  "http://newcar.xcar.com.cn/2431/?zoneclick=101426~~" +
  "http://js1.eastmoney.com/tg.aspx?ID=1367~~" +
  "http://s.kouclo.com/search.php?c=24226,%E8%BF%90%E5%8A%A8%E9%BC%93%E5%8C%85%C2%B7%E6%97%85%E8%A1%8C%E5%8C%85~~" +
  "http://s.b5m.com/s/Search?key=%E5%A9%B4%E5%84%BF%E5%BA%8A&isKnn=0~~" +
  "http://down.chinaz.com/class/50_1.htm~~" +
  "http://home.mobile.de/regional/sachsen/leipzig.0.html~~" +
  "http://www.jinbaonet.com/~~" +
  "https://hootsuite.com/dashboard~~" +
  "http://www.weather.com/life/profile~~" +
  "http://aletai.ganji.com/~~" +
  "http://media.daum.net/entertain/~~" +
  "http://fitness.pclady.com.cn/zxzq/rufangzhengxing/ruyun/~~" +
  "http://www.nba.com/cares/hoopsfortroops/index.html?ls=iref:nba:gfooter~~" +
  "http://careers.intuit.com~~" +
  "http://ref.gamer.com.tw/0000202/*http://gnn.gamer.com.tw/7/112737.html~~" +
  "http://www.autohome.com.cn/27840/0/1/conjunction.html~~" +
  "http://jke.store.xywy.com/item/40102/policy_type/standard.html~~" +
  "http://car.bitauto.com/baomax3/~~" +
  "http://xfinitytv.comcast.net/live/network/trutv?cmpid=FCST_livemod_trutv~~" +
  "http://car.bitauto.com/luzunxiaobawang/~~" +
  "http://mobile.zol.com.cn~~" +
  "http://elpais.com/politica/~~" +
  "http://Ettoday.net/news/20120520/47776.htm~~" +
  "http://www.aliexpress.com/category/200002550/nail-art.html?site=glo&shipCountry=ru&g=y&isrefine=y~~" +
  "http://insider.espn.go.com/insider/espn-the-magazine/~~" +
  "http://hengshui.ci123.com~~" +
  "http://news.bitauto.com/dealer/20150328/1306521094.html~~" +
  "http://www.bhaskar.com/news-hf/PUN-JAL-one-dead-in-road-accident-in-jalandhar-4946058-PHO.html~~" +
  "http://travelinsiders.americanexpress.com?inav=menu_travel_finddestination~~" +
  "http://www.washingtonpost.com/national/religion~~" +
  "http://life.gmw.cn/2015-03/27/content_15218875.htm~~" +
  "http://kitchener.craigslist.ca~~" +
  "http://m.163.com/~~" +
  "http://www.imdb.com/title/tt2379713?ref_=hm_hp_cap_pri_1~~" +
  "http://bleacherreport.com/articles/2411691-ncaa-tournament-2015-everything-you-need-to-know-about-the-elite-eight?utm_source=cnn.com&utm_medium=referral&utm_campaign=cnn-sports-bin~~" +
  "http://product.enet.com.cn/xdp254483.html~~" +
  "http://auto.gome.com.cn~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=931&zoneclick=101446~~" +
  "http://www.aol.ca/~~" +
  "http://nyjets.about.com~~" +
  "http://quote.eastmoney.com/zs000300.html~~" +
  "http://jianfei.39.net/bbs/~~" +
  "http://suche.web.de/amazonhp~~" +
  "http://www.naukri.com/tieups/tieups.php?othersrcp=17629~~" +
  "http://www.nyaa.se/?page=view&tid=671050~~" +
  "http://www.wikipedia.org//na.wikipedia.org/~~" +
  "http://jbk.39.net/yxmc/muyingjiankang~~" +
  "http://toronto.craigslist.ca//kitchener.craigslist.ca~~" +
  "http://4travel.jp/insurance/~~" +
  "http://www.foxnews.com/entertainment/2015/03/27/christina-hendricks-ditches-skirt-halfway-through-red-carpet/~~" +
  "http://warranty.rakuten.co.jp/~~" +
  "http://itbbs.pconline.com.cn/diy/52140519.html~~" +
  "http://www.kouclo.com/item/index/132965~~" +
  "http://jbk.39.net/jiancha/rrmmcxxjshcg/~~" +
  "http://www.yelp.fr/sf~~" +
  "http://www.indiatimes.com/news/india/~~" +
  "http://accessories.woot.com/plus/mens-jewelry-and-cuff-links?ref=gh_aw_7_wp_6~~" +
  "http://www.southmoney.com/~~" +
  "http://time.com/topic/above-and-beyond/~~" +
  "http://www.fedex.com/bz/~~" +
  "http://www.marca.com/2015/03/27/futbol/equipos/barcelona/1427476262.html~~" +
  "http://baike.pcbaby.com.cn/qzbd/1109788.html~~" +
  "http://ux.stackexchange.com/users/36907/rhinofeeder~~" +
  "http://zt.cnssz.com/topic/201310zjgwhj/index.htm~~" +
  "http://club.autohome.com.cn/bbs/forum-c-792-1.html~~" +
  "http://www.sahibinden.com/ilan/emlak-konut-satilik-site-icerisinde-superluks-daire-206392285/detay/~~" +
  "https://www.wellsfargo.com/international-remittances/~~" +
  "https://www.adobe.com/news-room/pressreleases/201503/031715AdobeIntroducesDocumentCloud.html~~" +
  "http://s.taobao.com/search?q=%C9%B3%9E%A9%D1%9D+%C4%D0&js=1&stats_click=search_radio_all%253A1&initiative_id=staobaoz_20150127~~" +
  "http://swietaztesco.wp.pl/wid,17359698,przepisy.html~~" +
  "http://price.xcar.com.cn/serise1222/city9999-1-1.htm?zoneclick=101420~~" +
  "http://www.Weebly.com/setLanguage.php?lang=jp~~" +
  "http://www.he.xinhuanet.com/zfwq/sanhe/~~" +
  "https://subscribe.free.fr/login/~~" +
  "http://www.bitauto.com/hainanzangzuzizhizhou/~~" +
  "http://direct.money.pl/~~" +
  "http://fitness.39.net/special/jfwd/sdatui/~~" +
  "http://www.hurriyet.com.tr/spor/futbol/28579954.asp~~" +
  "http://star.news.sohu.com/~~" +
  "http://activities.aliexpress.com/firstorderdiscount324.php~~" +
  "http://info.xcar.com.cn/201503/news_1775225_1.html~~" +
  "http://www.tripadvisor.com/TravelersChoice-Hotels~~" +
  "http://terrorism.about.com~~" +
  "http://www.cbssports.com/collegebasketball/eye-on-college-basketball/25126298/5-takeaways-from-fridays-sweet-16-gonzaga-breaks-through-meets-duke-next~~" +
  "http://www.mobile.de/modellverzeichnis/nissan/~~" +
  "http://beihai.bitauto.com/~~" +
  "http://www.wordreference.com/entr/~~" +
  "http://cps.tudou.com/redirect.html?id=000140d4~~" +
  "https://aws.amazon.com/marketplace/b/2649337011/ref=mkt_ste_l2_S3CDN?page=1&category=2649337011&nc2=h_l2_n~~" +
  "https://vimeo.com/business~~" +
  "http://www.iqiyi.com/zongyi/wknyx.html?src=focustext_0_20130527_6~~" +
  "http://xiaogan.xcar.com.cn/~~" +
  "http://weifang.bitauto.com/~~" +
  "http://www.bitauto.com/deyang/~~" +
  "http://car.autohome.com.cn/price/brand-12.html~~" +
  "http://search.daum.net/search?w=tot&rtupcate=issue&q=%EB%B0%95%EC%A0%95%ED%98%84&rtupcoll=DQP,NNS&guide=rissue&DA=ATG&nil_profile=rtupkwd~~" +
  "http://aws.amazon.com/rds/?nc2=h_l3_db~~" +
  "http://time.com/business/~~" +
  "http://baike.pcbaby.com.cn/qzbd/1026709.html~~" +
  "http://www.tmz.com/2015/03/27/drea-de-matteo-new-york-city-apartment-explosion/~~" +
  "http://www.gome.com.cn/product/9129891576-1118910115.html?intcmp=sy-G-2-0-0-9129891576~~" +
  "http://www.quikr.com/Real-Estate/gId-20~~" +
  "http://Slickdeals.net/f/7758711-perry-ellis-19-99-pants-event-fs-shoprunner?src=pdw&v=1~~" +
  "http://shop1018140902.kouclo.com/~~" +
  "http://photobucket.com/upload~~" +
  "http://www.cbssports.com/nhl/blog/eye-on-hockey/tag/1979968/nhl-rumors~~" +
  "http://fuwu.sogou.com/~~" +
  "http://clothing.lady8844.com/clothing/streetsnap/star/~~" +
  "http://www.zillow.com/homes/for_sale/1_open/~~" +
  "http://Amazon.com/101-Dalmatians-Diamond-Edition-Blu-ray/dp/B00OZLF4AG~~" +
  "http://bbs1.people.com.cn/post/2/1/2/146218445.html~~" +
  "http://analytics.163.com/ntes_clck?urlid=454&sign=c03a07caa005eecc65356644a11332ba&url=https%3A%2F%2Fepay.163.com%2Findex.jsp~~" +
  "http://blog.sina.com.cn/s/blog_9b7eeaf10102vwz2.html?tj=1~~" +
  "http://detail.zol.com.cn/mice/~~" +
  "http://certification.about.com~~" +
  "http://www.adobe.com/be_nl/~~" +
  "http://oabbs.zol.com.cn/5/1_40673.html~~" +
  "http://newcar.xcar.com.cn/photo/ps1798/?zoneclick=101434~~" +
  "http://www.nyaa.se/?page=view&tid=671082~~" +
  "http://www.aliexpress.com/reviews.html~~" +
  "http://www.autohome.com.cn/26146/0/1/conjunction.html~~" +
  "http://www.webtretho.com/lamme/nuoi-day-con/~~" +
  "http://community.xe.com/forum/xe-market-analysis~~" +
  "https://afisha.mail.ru/concert/news/45563/?from=mr_news~~" +
  "http://baike.pcbaby.com.cn/qzbd/11921.html~~" +
  "http://lady.b5m.com/beauty/8217.html~~" +
  "http://news.goo.ne.jp/topstories/nation/344/a3ef20d2b57faa0fc21f37b119039d06.html?fr=RSS~~" +
  "http://baobao.ci123.com/linmin728~~" +
  "http://www.booking.com/index.sk.html~~" +
  "http://ydk.39.net/dealerhtm/bjtrt/index.html~~" +
  "http://www.youm7.com/story/2015/3/28/%d8%a3%d8%ae%d8%b5%d8%a7%d8%a6%d9%89-%d8%b0%d9%83%d9%88%d8%b1%d8%a9-%d9%8a%d9%88%d8%b6%d8%ad-%d8%a3%d9%87%d9%85-%d8%a7%d9%84%d8%b9%d9%88%d8%a7%d9%85%d9%84-%d8%a7%d9%84%d9%85%d8%b1%d8%b6%d9%8a%d8%a9-%d9%88%d8%a7%d9%84%d9%86%d9%81%d8%b3%d9%8a%d8%a9-%d8%a7%d9%84%d9%85%d8%b3%d8%a8%d8%a8%d8%a9-%d9%84%d9%84%d8%b6%d8%b9%d9%81/2120251~~" +
  "http://rutracker.org/go/14~~" +
  "http://cppcc.people.com.cn/~~" +
  "http://techcrunch.com~~" +
  "http://house.ifeng.com/column/loupanzt/huiguniangoushihaozhai?ifengsylprk~~" +
  "https://www.youtube.com/watch?v=el6jswzrhBQ~~" +
  "http://vogue.globo.com/~~" +
  "http://js1.eastmoney.com/tg.aspx?ID=3235~~" +
  "http://Kickass.to/search/nl/~~" +
  "http://kakaku.com/kuruma/used/~~" +
  "http://www.forbes.com/profile/georg-schaeffler/~~" +
  "http://yule.iqiyi.com~~" +
  "http://Moz.com/local~~" +
  "http://comprarautos.about.com~~" +
  "http://s.b5m.com/s/Search?key=%E4%BA%94%E7%B2%AE%E6%B6%B2~~" +
  "http://www.athleta.com/~~" +
  "http://www.xywy.com/fangtan/239.html~~" +
  "http://www.newegg.com/Power-Protection/Category/ID-314~~" +
  "http://paper.people.com.cn/rmrbhwb/paperindex.htm~~" +
  "http://www.salesforce.com/small-business-solutions/~~" +
  "http://espn.go.com/espn/fp/flashPollResultsState?sportIndex=frontpage&pollId=4763526~~" +
  "http://car.bitauto.com/fengtiansaina/~~" +
  "http://zhoushan.58.com/~~" +
  "http://Xe.com/currencycharts/?from=USD&to=AUD~~" +
  "http://Mashable.com/2014/06/~~" +
  "http://koreanfood.about.com~~" +
  "http://Codecanyon.net/item/2-in-1-social-network-logo-reveal/8219351~~" +
  "http://price.xcar.com.cn/serise2750/city9999-1-1.htm?zoneclick=101416~~" +
  "http://s.kouclo.com/search.php?q=%E6%B0%B4%E6%9E%9C~~" +
  "http://info.nicovideo.jp/pr_nicom/iphone.html?header~~" +
  "http://www.lady8844.com/hot/club/drgkk/~~" +
  "http://www.half.ebay.com~~" +
  "http://www.imdb.com/title/tt2717860?ref_=hm_otw_t5~~" +
  "http://partnerdirect.dell.com/sites/channel/en_us/pages/pp_default.aspx~~" +
  "http://js1.eastmoney.com/tg.aspx?ID=626~~" +
  "http://www.nytimes.com/pages/books/review/index.html~~" +
  "http://g.163.com/a?CID=20334&Values=3394819843&Redirect=http://henan.163.com~~" +
  "http://mouth.39.net/~~" +
  "http://www.huffingtonpost.ca/news/stephen-harper/~~" +
  "https://news.mail.ru/currency.html?charcode=EUR~~" +
  "http://www.huffingtonpost.ca/2015/03/27/bill-c-51-conservative-amendments-terror_n_6958726.html~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1008~~" +
  "http://atube-catcher.uptodown.com~~" +
  "http://www.mobile.de/modellverzeichnis/bmw/z4.html~~" +
  "http://spiderbites.nytimes.com~~" +
  "https://sport.mail.ru/news/football-euro/21533825/?frommail=1~~" +
  "http://www.elpais.com/especial/pet-shop-boys/~~" +
  "http://Kickass.to/kidnapping-mr-heineken-2015-720p-brrip-x264-yify-t10410842.html~~" +
  "http://columbusoh.about.com~~" +
  "http://club.xywy.com/question/20150327/63775779.htm~~" +
  "http://www.cnn.com/tv/schedule/cnn~~" +
  "http://detail.zol.com.cn/vehiclecleaner/~~" +
  "http://www.mama.cn/z/368/~~" +
  "http://wx.xinhuanet.com/~~" +
  "http://finance.people.com.cn/money/n/2015/0328/c217431-26764770.html~~" +
  "http://ln.ifeng.com/~~" +
  "http://www.taoche.com/kaimeirui/~~" +
  "http://www.naukri.com/tieups/tieups.php?othersrcp=14730~~" +
  "http://food.39.net/sl/zc~~" +
  "http://politics.people.com.cn/GB/8198/105667/index.html~~" +
  "http://www.ltn.com.tw/news/focus/paper/866839~~" +
  "http://tuku.auto.china.com/auto/html/2013-06-07/216553_2358740.htm~~" +
  "http://www.slideshare.net/directory/user/_~~" +
  "http://quote.eastmoney.com/SH601699.html~~" +
  "http://www.xcar.com.cn/bbs/viewthread.php?tid=21433719~~" +
  "http://product.pconline.com.cn/family_theater/~~" +
  "http://baby.china.com.cn/~~" +
  "http://www.walmart.com/cp/1094926?povid=P1171-C1086.5062-L8~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1430~~" +
  "http://youxi.zol.com.cn/pc/index5411.html~~" +
  "http://Mashable.com/2015/~~" +
  "http://www.nyaa.se/?cats=2_13~~" +
  "https://twitter.com/i/cricket~~" +
  "http://www.crunchbase.com~~" +
  "http://dress.pclady.com.cn/zxzq/shoulian/~~" +
  "http://www.gome.com.cn/category/cat15985542.html~~" +
  "https://www.crunchbase.com/category/social-media-monitoring/ddb373846651f1621125a8cb55a7b8b9?utm_source=tc_river&utm_medium=export&utm_campaign=dataset~~" +
  "https://www.kaskus.co.id/register~~" +
  "http://Taboola.com/news~~" +
  "http://zc.zol.com/2.html~~" +
  "http://twitter.com/chrisvelazco~~" +
  "http://auto.people.com.cn/n/2015/0327/c1005-26758059.html~~" +
  "http://baike.pcbaby.com.cn/qzbd/1121615.html~~" +
  "http://www.forbes.com/sites/scottmendelson/~~" +
  "http://www.webtretho.com/forum/showthread.php?t=2029500~~" +
  "http://www.csdn.net/article/2015-03-26/2824322~~" +
  "http://usgovinfo.about.com~~" +
  "http://tweenparenting.about.com/bio/Jennifer-O-Donnell-47404.htm~~" +
  "http://www.booking.com/index.nl.html~~" +
  "http://www.chinatimes.com/reporter/843~~" +
  "http://www.spiegel.de/thema/~~" +
  "http://www.hq.xinhuanet.com/boao/zb.htm~~" +
  "http://s.kouclo.com/search.php?c=18389,%E9%85%8D%E4%BB%B6~~" +
  "http://product.pconline.com.cn/xa/~~" +
  "http://www.wikipedia.org//www.wikisource.org/~~" +
  "http://s.taobao.com/search?q=%F1R%BC%D7&js=1&stats_click=search_radio_all%253A1&initiative_id=staobaoz_20150127~~" +
  "http://count.shopping.t-online.de/RE?ID=73437728&CID=40576530&SI=64756648&TI=40448828&lg=1&URL=http%3A%2F%2Fwww.t-online.de%2Fpreisvergleich%2Findex.html%23suche-sea%2Fvhs+dvd+recorder%2Ffilter%2F0%260%260%2Fcampid%2Fvhsrekorder-2803-bl~~" +
  "http://www.tianya.cn/~~" +
  "https://www.blogfa.com/Desktop/Login.aspx?~~" +
  "http://newcar.xcar.com.cn/1314/?zoneclick=101410~~" +
  "http://mobilecoupons.about.com~~" +
  "http://www.walmart.com/cp/Baby/5427?povid=P1171-C1110.2784+1455.2776+1115.2956-L181~~" +
  "http://car.autohome.com.cn/price/series-657.html~~" +
  "https://plus.google.com/u/0/b/116182588372378635178/116182588372378635178/posts~~" +
  "http://araba.milliyet.com.tr/ilan-detay/2012-Porsche-Cayenne/5564799~~" +
  "https://www.merrilledge.com/m/pages/home.aspx?src_cd=bac_hp_nav_streamline~~" +
  "http://stats.nba.com/players/?ls=iref:nba:gnav~~" +
  "http://www.slideshare.net/login?from=download&from_source=%2Fsavedfiles%3Fs_title%3Dteacher-zen-with-google-tools-and-apps%26user_login%3DShellTerrell&download_id=46342863-375e7e578a459c6d0ce23ba8a540ab2d6d2175af-slideshow~~" +
  "http://baike.pcbaby.com.cn/qzbd/1110769.html~~" +
  "http://v.opahnet.com/soccer/new/zhongchao~~" +
  "http://m.b5m.com~~" +
  "http://espn.go.com/mens-college-basketball/~~" +
  "http://www.iqiyi.com/dongman/MHTDGIFT.html~~" +
  "http://fenlei.baike.com/%E8%90%83%E6%99%BA/~~" +
  "http://www.leboncoin.fr/annonces/offres/bretagne/~~" +
  "http://culture.china.com/photo/11159898/20150327/19431147.html~~" +
  "http://Ptt01.cc/post_16537~~" +
  "http://house.focus.cn/news/2015-03-28/6145415.html~~" +
  "http://v.opahnet.com/soccer/v475402.html~~" +
  "http://Slickdeals.net/coupons/tommy-hilfiger/?src=fsw~~" +
  "http://data.eastmoney.com/money/calc/TaxPersonal.html~~" +
  "http://www.hurriyet.com.tr/egitim/28576986.asp~~" +
  "http://www.mama.cn/z/1100/~~" +
  "http://www.samsung.com/ca/support/category/homeappliance/cooking/~~" +
  "http://www.twitter.com/ookla~~" +
  "http://music.sogou.com/song/newdj_1.html~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=837~~" +
  "http://www.t-online.de/spiele/id_65445550/sudoku-und-mehr-online-spiele-kostenlos-online-spielen-bei-t-online-de.html~~" +
  "http://www.marca.com/2015/03/25/futbol/copa_rey/1427303940.html~~" +
  "http://www.wordreference.com/english/Privacy%20Policy.htm~~" +
  "http://www.ah.xinhuanet.com/~~" +
  "http://dol.deliver.ifeng.com/c?10cec7965MluuVuLEVCrlk7CiF1N5piUjVsuTNmWaw1nose1ZFK1zbhPFHsoS5yMGG7KKwsFw-_vtY8i0FUxmIA2xxioE1cbwdla4D-b-J8NypYYl9BHH3QvLI9qSaxdFmvuWoo2Uazb_H6qF5I~~" +
  "http://ref.gamer.com.tw/0000161/*http://gnn.gamer.com.tw/2/112772.html~~" +
  "http://www.librosalfaguarainfantil.com/~~" +
  "http://newsstand.naver.com/?list=ct1&pcode=018~~" +
  "http://yuedu.163.com/yc~~" +
  "http://Wunderground.com/cgi-bin/findweather/getForecast?setpref=EXPFCT&value=1&referer=%2f~~" +
  "http://mobile.udn.com/~~" +
  "http://ad5.udn.com/RealMedia/ads/click_lx.ads/udn.com/NEWS-main2015yy-message/2088680526/Frame2/news2015-SP-C/udnpaper-1.gif/33636661383731323534613238613530?http://udndata.com/schools/~~" +
  "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&N=100015971%20600213651&IsNodeId=1&name=Female&SpeTabStoreType=14~~" +
  "http://watch.pclady.com.cn/121/1218091.html~~" +
  "http://www.ltn.com.tw/news/opinion/paper/866826~~" +
  "http://detail.zol.com.cn/phonemeeting/~~" +
  "http://escuela.elpais.com~~" +
  "http://moto.onet.pl/aktualnosci/subaru-planuje-produkcje-nowego-suv-a/ts6bt7~~" +
  "http://www.slideshare.net/directory/user/z~~" +
  "http://Stackoverflow.com/questions/tagged/helix-3d-toolkit~~" +
  "http://www.ppomppu.co.kr/zboard/zboard.php?id=agentnews~~" +
  "http://imgur.com/a/SJG6b~~" +
  "http://www.lady8844.com/xiufa/diy/2015-03-25/1427246832d1557469.html~~" +
  "http://www.nyaa.se/?page=download&tid=671106~~" +
  "http://www.siviaggia.it?ref=libero~~" +
  "http://9gag.com/gag/a0LoqrB~~" +
  "https://hootsuite.com/plans/enterprise~~" +
  "http://www.walmart.com/browse/auto-tires/auto-body-tools-auto-equipment/91083_1074767?povid=P1171-C1110.2784+1455.2776+1115.2956-L299~~" +
  "https://plus.google.com/share?url=http://www.xda-developers.com/your-favorite-wireless-charger/~~" +
  "http://www.starsports.com/cricket/videos/vod/video=match-highlights-icc-cricket-world-cup-2015-india-bangladesh/index.html~~" +
  "http://detail.zol.com.cn/series/84/18602_1.html~~" +
  "http://diqing.ganji.com/~~" +
  "https://play.google.com/store/apps/details?id=com.youm7.news&hl=en~~" +
  "http://mobile.163.com/15/0328/09/ALPKKLB10011179O.html~~" +
  "http://detail.zol.com.cn/notebook_index/subcate16_list_s1229_1.html~~" +
  "http://mall.gome.com.cn/80001394/~~" +
  "http://Stackoverflow.com/questions/tagged/matlab~~" +
  "http://www.tmz.com/2015/03/06/madonna-home-tel-aviv-penthouse-condo/~~" +
  "http://jiyouhui.it168.com/~~" +
  "http://finanse.wp.pl/kat,1033755,title,Fiskus-zarzuca-nowa-siec-na-polskie-firmy,wid,17393483,wiadomosc.html~~" +
  "http://www.dailymotion.com/video/x2kqohk_%E7%94%B5%E5%BD%B1-%E7%A5%9E%E9%80%9A%E4%B9%A1%E5%B7%B4%E4%BD%AC-%E4%B8%BB%E6%BC%94-%E7%8E%8B%E5%AE%9D%E5%BC%BA-%E6%9B%BE%E5%BF%97%E4%BC%9F-%E8%91%9B%E8%95%BEpart1_shortfilms~~" +
  "http://car.bitauto.com/xuefolankepaqi/~~" +
  "http://pad.pconline.com.cn/620/6209981.html~~" +
  "http://feedburner.google.com/fb/a/mailverify?uri=ettoday/china&loc=zh_TW~~" +
  "http://www.ppomppu.co.kr/zboard/zboard.php?id=health~~" +
  "http://www.businessinsider.com/author/julie-bort~~" +
  "http://www.reimageplus.com/release-notes/~~" +
  "http://www.zol.com/cell_phone/list/c34_s57_m544.html~~" +
  "http://www.rediff.com/news/report/pix-best-photos-15-top-shots-you-will-ever-see/20150324.htm~~" +
  "https://beap.gemini.yahoo.com/mbclk?bv=1.0.0&es=oIx5oo8GIS99CjLSgj8CuTGE2eI6Wi0fE71cjUZFhKkv1j5YfhUo.QC4ULQVMhgg0xHbgsDmjT93UdtcGlupNrK88n7p7mqxXRuEd3oP4FIwBAZi9UkYNlYxwCSo4ujAaUpyEpnqlNBZCiVkjlepJHCAdG_6KkWU7zHAm3nU.OHaCiRX8eVFUuv7rQua_aUg2kmR64Xfh_KYNU66kJLAfZNrfumrwBaEwczGy4hV6Xm7ovuhPMYjIwnNd13ous8805DsX1Sb8vh64szezG4Sdhh1TbpRp2SQEJyhuRC8CCY0sR5U4e8gJaKnppu.Gc0NForSZ66VNrriI8A3V9CULA0JsxognaL908l1jpAnvOsK.54SvFmUdhJdCfTuAlkHtHYDaKZgem2I1tYi__Rr3_uO9wO5S.eNCnanKOeOSk7aY8GuCPu7syxd7mD7_9a.zpvDTXjKoM8Os1WuDOvmHfBuNX7JLnhfHGyBievQ_IAzQZw4NEj5xlyJ01MiwHnLu8CAba5Jpc4kxL2Ll72FamKNZ4vOLkzKQjdiJs__DdqTqtgt4RGVEYomYI1IcFJIjjrY0Yq6xywpoubeFJViYtThnZAxsBPcCmCwNJDKDXOilNQ.eaJkLGAF3rfFCtFlTT6_NBWoDCXEXabidm_q4izU%26lp=http%3A%2F%2Fwww.answers.com%2Fbrowse%2Fclick.php%3Fsource%3Dysa%26param3%3Dwww.answers.com%252Farticle%252F1210947%252F10-celebs-who-do-not-drink-alcoho%26param4%3Dysa-ca-de-food%26param5%3D1015359%26param6%3D30147538683~~" +
  "http://zt.pchouse.com.cn/70/700012.html~~" +
  "http://123.sogou.com/yule/mingxing.html?fr=2003-0006~~" +
  "http://www.theguardian.com/money/debt~~" +
  "http://r.mail.ru/clb1406992/horo.mail.ru/?from=odnoklassniki~~" +
  "http://www.milliyet.com.tr/gebelik-sekeri-dikkate-alinmali-pembenar-detay-hamilelik-2034449/?ref=milliyet_anasayfa~~" +
  "https://vimeo.com/ondemand/motoskillswithnickwey~~" +
  "http://www.forbes.com/sites/jonathonkeats/~~" +
  "http://www.news.cn/mobile/xhxw/syzt/index.htm~~" +
  "http://www.reddit.com/r/sports/comments/30ji7o/amateur_mma_fighter_taps_out_to_spare_his/~~" +
  "http://www.alibaba.com/Musical-Instruments_pid100005383~~" +
  "http://xfinity.comcast.net/video/taco-bell-a-click-away-ceo-says-not-far-off/419139651596/Comcast/CNBC_new/?cid=moneymod_sf_tacobelldelivery~~" +
  "http://anonews.livedoor.biz/archives/8764953.html~~" +
  "http://v.yc.ifeng.com/book/yc/3026307.htm~~" +
  "http://www.dailymail.co.uk/travel/travel_news/article-3004629/Beyonce-Miranda-Kerr-Lady-Gaga-share-smug-yoga-selfies.html~~" +
  "http://www.tudou.com/listplay/xgcOdheFH0U/hortLfWnvDI.html~~" +
  "http://www.flipkart.com/q/canon-cameras~~" +
  "http://losangeles.cbslocal.com/category/sports/~~" +
  "http://www.buzzfeed.com/caseygueren/please-no-babies~~" +
  "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&N=100010095&IsNodeId=1&Description=chronograph&bop=And&Order=REVIEWS&PageSize=100&name=Chronograph~~" +
  "http://s.b5m.com/s/Search?key=%E7%94%B7%E9%9E%8B&isKnn=0~~" +
  "http://prom.gome.com.cn/html/prodhtml/topics/201503/2nzq-gmcs.html?intcmp=sy-F-8-0-0~~" +
  "http://Codecanyon.net/category/html5/games~~" +
  "http://pcedu.pconline.com.cn/626/6260337.html~~" +
  "http://ad.doubleclick.net/ddm/clk/279569051;106660235;i?http://ad.doubleclick.net/ddm/clk/279267813;106357185;q?http://www.jacpv.com.cn/market/2014hy/?utm_source=bitauto&utm_content=ShouYeQuanGuoTongFa&utm_medium=ReMenPinPaiTuiJian4&utm_campaign=8005622~~" +
  "http://www.bitauto.com/enshi/~~" +
  "http://wallstreetcn.com/~~" +
  "http://www.aliexpress.com/category/403/towels.html~~" +
  "http://www.douban.com/location/canada/events/week-exhibition~~" +
  "http://car.bitauto.com/jinying/~~" +
  "http://car.bitauto.com/haiyu/~~" +
  "http://Amazon.com/Jack-Reacher-HD-Tom-Cruise/dp/B00BUCXVPI~~" +
  "http://Themeforest.net/popular_item/by_category?category=ecommerce~~" +
  "http://www.wikipedia.org//cdo.wikipedia.org/~~" +
  "http://car.bitauto.com/dongnanc1/~~" +
  "http://mp.weixin.qq.com/s?__biz=MzA3ODE4NTgwMw==&mid=203464747&idx=1&sn=4ec480f843e2a2c714f5c7ba235fa964~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=748~~" +
  "http://www.mama.cn/z/1126/~~" +
  "http://www.fedex.com/th/~~" +
  "https://produkte.web.de/club/~~" +
  "http://Themeforest.net/category/blogging/tumblr/business~~" +
  "http://Xe.com/currencycharts/?from=JPY&to=EUR~~" +
  "http://uad.nicovideo.jp/~~" +
  "http://www.webtretho.com/forum/f3950~~" +
  "http://www.controlyourtv.org/Intro.aspx~~" +
  "http://www.chinadaily.com.cn/sports/2015-01/19/content_19350133.htm~~" +
  "http://beauty.pclady.com.cn/zxzq/bf/~~" +
  "http://www.babytree.com/community/club201410/~~" +
  "http://article.pchome.net/content-1793066.html~~" +
  "http://www.softonic.com/descargar-programas-gratis/5~~" +
  "http://model.auto.sina.com.cn/highpix/17618/51373904~~" +
  "http://www.dell.com.mx/~~" +
  "http://newcar.xcar.com.cn/162/?zoneclick=101428~~" +
  "http://voice.hupu.com/soccer/1892295.html~~" +
  "http://baike.pcbaby.com.cn/qzbd/1011423.html~~" +
  "http://www.ca.kayak.com/flight-routes/Quebec-YQB/Toronto-Island-YTZ~~" +
  "http://www.walmart.com/c/kp/continental-tires?povid=P1171-C1093.2766-L109~~" +
  "http://Ettoday.net/news/20120521/47922.htm~~" +
  "http://www.bomb01.com/hot/~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=921&zoneclick=101410~~" +
  "http://health.pclady.com.cn/qpz/~~" +
  "http://news.china.com.cn/2015-03/28/content_35180033.htm~~" +
  "http://Amazon.com/Nikon-Digital-NIKKOR-18-55mm-3-5-5-6G/dp/B00HQ4W1QE~~" +
  "http://www.nyaa.se/?page=view&tid=671108~~" +
  "http://dress.pclady.com.cn/zxzq/weiyi/~~" +
  "http://www.wix.com/domain/names~~" +
  "http://www.spiegel.de/forum/politik/ukraine-krise-altkanzler-schroeder-attackiert-merkels-russland-politik-thread-264153-1.html~~" +
  "http://s.b5m.com/s/Search?key=%E6%B0%91%E6%97%8F%E4%B9%90%E5%99%A8&isKnn=0~~" +
  "http://Avito.ru//www.avito.ru/rossiya~~" +
  "http://app.finance.china.com.cn/stock/capital/index.php?kind=stock&level=0&type=z~~" +
  "http://Themeforest.net/item/flatpack-multipurpose-unbounce-pack/8850389~~" +
  "http://xfinitytv.comcast.net/live/network/tnt?cmpid=FCST_livemod_tnt~~" +
  "http://product.pconline.com.cn/movepower/~~" +
  "http://www.gome.com.cn/html/prodhtml/topics/201503/dndjdphc.html?intcmp=sy-A-4-0-0-nd~~" +
  "http://www.hotels.com/de1497539/hotels-chicago-illinois/~~" +
  "http://www.iqiyi.com/dianshiju/sjll_wjt.html~~" +
  "http://www.oldnavy.com/products/baby-clothes.jsp~~" +
  "http://newcar.xcar.com.cn/601/~~" +
  "http://price.xcar.com.cn/serise2390/city9999-1-1.htm?zoneclick=101428~~" +
  "http://www.indiatimes.com/news/world/its-just-another-bus-ride-to-your-favourite-picnic-spottill-this-happens-231309.html~~" +
  "http://www.icc-cricket.com/cricket-world-cup/about~~" +
  "http://www.indeed.com/jobtrends~~" +
  "http://tag.lady8844.com/531780/~~" +
  "http://www.tripadvisor.com/Hotels-g34141-Clearwater_Florida-Hotels.html~~" +
  "http://care.39.net/a/140414/4372071.html~~" +
  "http://kawacy.deviantart.com/art/Teach-me-how-to-draw-522639014~~" +
  "https://www.tiberiumalliances.com/pl/affiliate/wirtualna/?pasek_sg~~" +
  "http://advertising.mobile.de/~~" +
  "http://www.goodreads.com/user/show/29053070-sierra-baksh~~" +
  "http://newcar.xcar.com.cn/photo/ps2799/?zoneclick=101410~~" +
  "http://en.wikipedia.org/wiki/Point_of_view_(literature)~~" +
  "http://js1.eastmoney.com/tg.aspx?ID=1371~~" +
  "http://www.ign.com/articles/2015/03/28/girl-meets-world-girl-meets-first-date-review~~" +
  "http://www.usatoday.com/picture-gallery/news/nation/2014/01/30/for-amanda-knox-a-long-road/2107707/~~" +
  "http://www.popads.net/blog?feed=rss2~~" +
  "http://www.wikipedia.org//sa.wikipedia.org/~~" +
  "http://globoesporte.globo.com/radicais/surfe/~~" +
  "http://www.washingtonpost.com/andrea-peterson/2013/07/22/0d7d8ebc-f2df-11e2-ae43-b31dc363c3bf_page.html~~" +
  "http://sd.people.com.cn/~~" +
  "http://www.buzzfeed.com/juliegerstein~~" +
  "http://s.kouclo.com/search.php?c=4744,%E4%BD%8F%E5%AE%85%E5%AE%B6%E5%85%B7~~" +
  "http://app.sina.com.cn/appdetail.php?appID=2145169&f=p_binfen&w=p_binfen~~" +
  "http://www.aliexpress.com/category/100004809/barware.html~~" +
  "http://www.miaopai.com/stpid/O-8CoZ5pMTnt5Qam~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=342~~" +
  "http://www.tmz.com/photos/2015/03/06/whats-the-big-frigin-difference~~" +
  "http://www.huffingtonpost.ca/kristi-gordon/global-hate-mail-response_b_6959888.html~~" +
  "http://bbs.zol.com.cn/sjbbs/d613_27606.html~~" +
  "http://dv.pconline.com.cn/621/6219943.html~~" +
  "http://video.sina.com.cn/m/hmjz_63790297.html~~" +
  "http://www.sahibinden.com/kategori/cep-telefonu~~" +
  "http://www.autohome.com.cn/list/c71-1.html~~" +
  "http://product.pchome.net/digi_home_lcd_tv_samsung_ua65h6088/436972.html~~" +
  "http://www.autohome.com.cn/news/201503/864009.html~~" +
  "http://q.mama.cn/topic/17313032/~~" +
  "http://s.b5m.com/item/4522504295f9d26a7d73c3e485929da5.html~~" +
  "http://www.dailymail.co.uk/femail/index.html~~" +
  "http://www.woot.com/support?ref=ft_wt_spt~~" +
  "http://tvuol.uol.com.br/videos/97sdpjrdcnh3/~~" +
  "http://baike.pcbaby.com.cn/qzbd/1026456.html~~" +
  "http://g1.globo.com/educacao/noticia/2015/03/professor-renato-janine-ribeiro-e-o-novo-ministro-da-educacao.html~~" +
  "http://female.kompas.com/konsultasi~~" +
  "http://search.daum.net/search?w=tot&DA=YYG&rtmaxcoll=AYF&q=%EB%8B%A4%EC%9D%8C%EC%95%B1~~" +
  "http://corporate.softonic.com/legal-information/data-protection-policy~~" +
  "http://zx.39.net/yjzcs/~~" +
  "http://jbk.39.net/ndy/ysbj/~~" +
  "http://salescareers.about.com/bio/Thomas-Phelps-96723.htm~~" +
  "http://www.autohome.com.cn/news/201503/864140.html~~" +
  "http://www.milliyet.com.tr/en-yaratici-kupe-tasarimlari-pembenar-galeri-aksesuar-2035100/~~" +
  "http://www.mama.cn/z/18717/~~" +
  "http://society.people.com.cn/n/2015/0327/c1008-26756843.html~~" +
  "http://www.kaskus.co.id/classified/300/?ref=homelanding&med=fjb_categories~~" +
  "http://www.walmart.com/browse/gifts-registry/personalized-apparel-accessories/1094765_133224_133134/?_refineresult=true&povid=P1171-C1110.2784+1455.2776+1115.2956-L359~~" +
  "http://q.mama.cn/group/26/~~" +
  "http://mediaset.vitv.it/hpl/recuperato-un-picasso-stavano-per-venderlo/VVMS_525269?ref=hpl~~" +
  "http://gx.pconline.com.cn/~~" +
  "https://www.chase.com/savings/savings-account~~" +
  "http://www.naukri.com/tieups/tieups.php?othersrcp=19767~~" +
  "http://bbs.gome.com.cn/thread-60529-1-1.html?intcmp=sy-E-1-4-0~~" +
  "http://news.xinhuanet.com/world/2015-03/28/c_127630795.htm~~" +
  "http://esporte.uol.com.br/futebol/campeonatos/copa-do-brasil/jogos/~~" +
  "http://star.pclady.com.cn/2011/1220/zt775788.html~~" +
  "http://vhouse.163.com/15/0326/08/ALKD61IO00294MCG.html~~" +
  "http://www.tistory.com/category~~" +
  "http://www.vice.com/en_ca/read/writer-amelia-gray-shoots-for-your-guts-667~~" +
  "http://www.cbsnews.com~~" +
  "https://joinexpedia.com/~~" +
  "http://lady.b5m.com/fashion/12554.html~~" +
  "http://www.irs.gov/uac/Newsroom/Tax-Time-Guide:-Easy-ePay-and-Payment-Agreement-Options-Available-to-People-Who-Owe-Tax~~" +
  "http://gongyi.gmw.cn/~~" +
  "http://games.espn.go.com/frontpage/flbdraftkit~~" +
  "https://www.elance.com/transcriptionists-jobs/43~~" +
  "http://www.fedex.com/do/~~" +
  "http://latinfood.about.com~~" +
  "http://comment.xcar.com.cn/comment.php?nid=1775203&ctype=0~~" +
  "http://s.b5m.com/s/Search?key=%E5%A2%A8%E7%9B%92%2F%E7%B2%89&isKnn=0~~" +
  "http://ftx2.hupu.com/~~" +
  "http://www.thefreedictionary.com/_/t.htm~~" +
  "http://forex.eastmoney.com/news/1129,20150328491143343.html~~" +
  "http://techcrunch.com/events/meetup-pitch-off-seattle-2015/~~" +
  "http://cms.mobile.de/de/unternehmen/datenschutz/nutzungsbasierte_online_werbung_oba.html~~" +
  "http://gshow.globo.com/programas/dupla-identidade/index.html~~" +
  "http://www.washingtonpost.com/blogs/where-we-live/?tid=hpModule_6032d2d6-919e-11e2-bdea-e32ad90da239~~" +
  "http://araba.milliyet.com.tr/ilan-detay/2012-Porsche-Panamera/436697~~" +
  "http://www.groupon.com//feeds.feedburner.com/groupon~~" +
  "http://finalfantasy.wikia.com/~~" +
  "http://www.cnet.com/products/enlight/~~" +
  "http://www.dailymail.co.uk/tvshowbiz/article-3011991/Amber-Rose-strips-just-thong-suns-Hawaiian-beach.html~~" +
  "http://www.tmz.com/2015/03/25/darren-sharper-nfl-hall-of-fame-john-randle-willie-roaf-dan-hampton/?adid=sidebar-sports-top-story~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1491~~" +
  "https://produkte.web.de/vorteile/finanzen-versicherung/~~" +
  "http://www.dailymotion.com/ca-en/everywhere~~" +
  "http://www.lady8844.com/caizhuang/lxcz/2015-03-19/1426752430d1556184.html~~" +
  "http://Slickdeals.net/coupons/saks-fifth-avenue/~~" +
  "http://news.qq.com/a/20150328/009221.htm?tu_biz=1.114.2.1~~" +
  "http://zt.pchouse.com.cn/ertongfang/~~" +
  "http://www.rakuten.co.jp/ec/~~" +
  "http://personal.it168.com~~" +
  "https://new.livejasmin.com/en/auth/login?session=g13ca65df7ee4cd0d8dbb8d6d5659c89c~~" +
  "https://twitter.com/WIRED~~" +
  "http://time.com/3761538/germanwings-pilot-reassures-scared-passengers-after-crash/~~" +
  "http://news.qq.com/a/20150327/085715.htm?tu_biz=1.114.2.1~~" +
  "http://magazine.caijing.com.cn/economists/~~" +
  "http://mulher.uol.com.br/casamento/~~" +
  "http://theme.udn.com/theme/story/6774/791512~~" +
  "http://www.yelp.com/sm/san-francisco-ca-us/v~~" +
  "http://www.aliexpress.com/category/200002365/tablet-decals.html~~" +
  "http://www.goodreads.com/api~~" +
  "http://home.lady8844.com/1363778/~~" +
  "http://vidasana.about.com~~" +
  "http://Kickass.to/blog/r00tH4cK3r/post/a-few-things/~~" +
  "http://www.flickr.com/photos/yngw/16323718334/in/explore-2015-03-27/lightbox~~" +
  "http://www.ndtv.com/diaspora?pfrom=home-diaspora~~" +
  "https://pogoda.mail.ru/~~" +
  "http://blog.livedoor.jp/staff/archives/51878202.html~~" +
  "http://Hdfcbank.com/personal/ways-to-bank/bank-in-person/branch-network~~" +
  "http://www.theverge.com/2015/3/26/8297247/president-obama-david-simon-the-wire-interview-hbo~~" +
  "http://dealer.xcar.com.cn/47834/market_7111693.htm~~" +
  "http://globoesporte.globo.com/volei/~~" +
  "http://www.newegg.com/Info/OfficeHours.aspx~~" +
  "http://www.hurlist.com/etiket/7/haberler.htm~~" +
  "http://m.163.com/iphone/software/2vhh7l.html~~" +
  "http://promotions.newegg.com/marketplace/merchants/apply.html~~" +
  "http://www.capitalone.com/credit-cards/business/?Log=1&EventType=Link&ComponentType=T&LOB=MTS%3A%3AL0RT6ME8Z&PageName=Home+Page+C&ComponentName=primary_nav&ContentElement=BS-L-7%3BBusiness+Credit+Cards&TargetLob=MTS%3A%3ALCTMMQC4S&TargetPageName=Spark+Business+Credit+Cards+%7C+Capital+&referer=https%3A%2F%2Fwww.capitalone.com%2Fhomepage~~" +
  "http://www.hdfcpension.com/~~" +
  "http://www.kouclo.com/item/index/127660~~" +
  "http://www.leboncoin.fr/annonces/offres/corse/~~" +
  "http://style.udn.com/mag/Style/subcategory.jsp?SUB_ID=24~~" +
  "http://www.huffingtonpost.com/2015/03/27/ngendo-mukii-yellow-fever_n_6949018.html?ir=Arts~~" +
  "http://www.indiatimes.com/entertainment/celebs/prepare-for-a-hotness-overload-nargis-fakhri-and-john-abraham-will-star-together-in-a-movie-231336.html~~" +
  "http://yuer.pcbaby.com.cn/xinshenger/~~" +
  "http://huaian.xcar.com.cn/~~" +
  "http://www.reuters.com/video/2015/03/27/harry-reid-will-not-seek-re-election?videoId=363650060&newsChannel=politicsNews~~" +
  "http://product.pconline.com.cn/mb/c14210/~~" +
  "http://www.webtretho.com/forum/showthread.php?t=2029483~~" +
  "http://news.xinhuanet.com/2015-03/28/c_1114794160.htm~~" +
  "http://Mashable.com/2009/10/~~" +
  "http://www.bhaskar.com/abhivyakti/hamare_columnists/ved_pratap_vaidik/~~" +
  "http://www.aliexpress.com/category/200005299/mobile-phone-housings.html~~" +
  "http://www.buzzfeed.com/ellencushing/kleiner-perkins-did-not-discriminate-against-ellen-pao-jury?responses~~" +
  "http://dealer.xcar.com.cn/43457/market_7237947.htm~~" +
  "http://s.b5m.com/s/Search?key=%E9%93%B6%E6%B3%B0%E7%B2%BE%E5%93%81%E7%99%BE%E8%B4%A7%E5%AE%98%E7%BD%91~~" +
  "http://www.spiegel.de/kultur/gesellschaft/germanwings-flug-4u9525-ratlosigkeit-nach-der-katastrophe-kolumne-a-1025873.html~~" +
  "http://jib.xywy.com/il_sii_3334.htm~~" +
  "http://www.businessinsider.com/terms~~" +
  "http://channel.jd.com/6196-6214.html~~" +
  "http://www.fedex.com/bh/~~" +
  "http://www.jabong.com/g-star-raw/~~" +
  "http://jiankang.163.com/photoview/5S400038/1976.html~~" +
  "http://math.about.com~~" +
  "http://gry.onet.pl/recenzje/pillars-of-eternity-recenzja-prawdziwy-wspolczesny-baldur-s-gate/18vs7r~~" +
  "http://www.spiegel.de/thema/eu/~~" +
  "http://tv.people.com.cn/n/2015/0328/c222296-26763634.html~~" +
  "https://savingscatcher.walmart.com/?povid=P1171-C1086.5062-L3~~" +
  "http://car.bitauto.com/changanb501/~~" +
  "http://www.xcar.com.cn/bbs/viewthread.php?tid=21692967~~" +
  "http://www.reuters.com/article/2015/03/28/us-somalia-attacks-idUSKBN0MO06R20150328~~" +
  "http://elpais.com/tag/libros_del_ano/a/~~" +
  "http://betl.58.com/~~" +
  "http://www.facebook.com/sharer/sharer.php?u=http://www.webtretho.com/forum/showthread.php?t=346463~~" +
  "http://www.yixun.com/~~" +
  "http://newcar.xcar.com.cn/photo/ps2768/?zoneclick=101409~~" +
  "http://zx.jiaju.sina.com.cn/anli/96475.html?utm_source=snls&utm_medium=nrw&utm_campaign=n_9980~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=934~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=939~~" +
  "http://www.bild.de/lifestyle/mode-beauty/styling/fruehlings-trends-im-test-40273042.bild.html~~" +
  "http://www.elpais.com/especial/bryan-ferry/~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1301~~" +
  "http://xjd.pchome.net~~" +
  "http://ask.39.net/browse/2001-2-1.html~~" +
  "http://www.alimama.com/index.htm~~" +
  "http://jxyichun.ganji.com/~~" +
  "https://www.pixnet.net/blog/profile/udokusono~~" +
  "http://www.jabong.com/american-tourister/~~" +
  "http://www.bhaskar.com/news-hf/c-3-1084640-NOR.html~~" +
  "http://www.sahibinden.com/kategori/hayvanlar-alemi-bocekler~~" +
  "http://blog.sina.com.cn/s/blog_53fe981c0102vmmk.html?tj=1~~" +
  "http://blogdosakamoto.blogosfera.uol.com.br/2015/03/27/o-tamanho-do-pib-e-importante-mas-para-quem-ele-traz-prazer/~~" +
  "https://twitter.com/slickdeals~~" +
  "http://showbiz.liputan6.com/read/2198562/jenazah-olga-syahputra-disalatkan-di-masjid-samping-rumah~~" +
  "http://magicbricks.com~~" +
  "http://studyabroad.shiksha.com/ms-in-abroad-dc11509~~" +
  "https://www.crunchbase.com/location/powai/cdbc2bb8c3f7d87e7693729bbf821352?utm_source=tc_river&utm_medium=export&utm_campaign=dataset~~" +
  "http://product.pchome.net/mobile_phone/list_3_236_pm26916_p1.html~~" +
  "http://elpais.com/internacional/2015/03/27/actualidad/1427495646_451577.html~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=5~~" +
  "http://test.39.net/test/6389.html~~" +
  "http://itunes.apple.com/us/app/engadget/id347839246?mt=8&uo=4~~" +
  "http://detail.zol.com.cn/series/702/16728_1.html~~" +
  "http://www.cnet.com/news/blackberry-shows-signs-of-life-posts-a-surprise-q4-profit/~~" +
  "http://www.irs.gov/uac/More-Hot-Topics~~" +
  "http://www.enet.com.cn/cpu/alist7187.html~~" +
  "http://epaper.gmw.cn/~~" +
  "http://sales.reuters.com/~~" +
  "http://newcar.xcar.com.cn/2511/?zoneclick=101432~~" +
  "http://www.360buy.com/products/670-699-700.html~~" +
  "http://car.bitauto.com/biyadis8/~~" +
  "http://s.taobao.com/search?initiative_id=staobaoz_20150126&tab=all&q=%C4%E1%C1%FA%B4%FC+%C4%D0&cps=yes&stats_click=search_radio_all%253A1&cat=50072686~~" +
  "http://photo.liputan6.com/health/di-rumah-sakit-ini-olga-syahputra-meninggal-dunia-2198356~~" +
  "https://www.Surveymonkey.com//fr.Surveymonkey.com~~" +
  "http://www.cqap.cn/~~" +
  "http://baike.pcbaby.com.cn/qzbd/1279872.html~~" +
  "https://www.elance.com/iphone-programmers-jobs/238~~" +
  "http://extratorrent.cc/torrent/4107234/DoctorAdventures+-+Payton+West+%28The+Cock+In+The+Doc+-+03.28.2015%29+%2A%2A+NEW+March+28%2C+2015+%2A%2A+SD+MP4s.html~~" +
  "http://corporate.walmart.com/global-responsibility/?povid=P1171-C1093.2766-L9~~" +
  "https://r.mail.ru/cls718344/e.mail.ru/messages/inbox/?siteid=169&_1ld=1_1000043_1000475_0?rnd=44037976~~" +
  "http://t.qq.com/chinatimes-tw~~" +
  "http://globoesporte.globo.com/mg/futebol/campeonato-mineiro/index.html~~" +
  "http://www.kayak.com.hk/~~" +
  "http://s.kouclo.com/search.php?c=3961,%E6%88%B7%E5%A4%96%E7%94%A8%E5%93%81~~" +
  "http://rd.rakuten.co.jp/s/?R2=http%3A%2F%2Fhoken.rakuten.co.jp%2Ffp%2Fprogram%2F%3Fscid%3Dwi_ich_150316_fp_tx01&D2=3.8611.68708.791218.31610999&C3=c44259c9884b16f4bb8cabbbb2b67d0f98844335~~" +
  "http://wiadomosci.onet.pl/tylko-w-onecie/nowa-ksiazka-juergena-rotha-wg-niemieckich-sluzb-10-kwietnia-to-zamach/fgg23n~~" +
  "http://beauty.pclady.com.cn/zxzq/xlh/~~" +
  "http://www.sahibinden.com/index.php?a=1020~~" +
  "http://www.hurriyet.com.tr/kelebek/keyif/28571279.asp~~" +
  "http://js.people.com.cn/~~" +
  "http://huangnan.58.com/~~" +
  "http://data.stackexchange.com~~" +
  "http://car.bitauto.com/aidier/~~" +
  "http://Ettoday.net/news/20120519/47642.htm~~" +
  "http://www.buchreport.de/~~" +
  "http://new.livejasmin.com/en/girl/smoking?session=g13ca65df7ee4cd0d8dbb8d6d5659c89c?selectedFilters=13~~" +
  "http://www.dell.com/us/en/gen/df.aspx?refid=df&s=gen&mp=/&~f=lg~~" +
  "http://Xe.com/currencycharts/?from=GBP&to=INR~~" +
  "http://www.marca.com/2015/03/28/futbol/eurocopa/1427497895.html~~" +
  "http://dress.pclady.com.cn/zxzq/yundongfu/~~" +
  "http://dealer.xcar.com.cn/34073/about.htm~~" +
  "http://www.newegg.com/Helmets-Accessories/SubCategory/ID-3153~~" +
  "http://ca.news.yahoo.com/german-pilot-said-suffered-depression-anxiety-102007809--sector.html~~" +
  "http://news.qq.com/a/20150326/057074.htm~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1197~~" +
  "http://baike.pcbaby.com.cn/qzbd/1143046.html~~" +
  "http://www.baike.com/wiki/%E5%8C%97%E4%BA%AC%E8%87%AA%E9%97%AD%E7%97%87%E5%8C%BB%E9%99%A2&prd=so_1_doc~~" +
  "http://www.hislife.com.cn~~" +
  "http://www.abs-cbnnews.com/video/global-filipino/03/05/15/indonesia-reviews-case-pinay-death-row~~" +
  "http://car.bitauto.com/oubaoweida/~~" +
  "https://account.washingtonpost.com/actmgmt/registration/addnewsletter/short~~" +
  "http://www.enet.com.cn/emobile/atlist0_iphone5.html~~" +
  "http://baike.pcbaby.com.cn/qzbd/28.html~~" +
  "http://www.all-nationz.com/archives/1022871428.html~~" +
  "http://rss.huanqiu.com/~~" +
  "http://s.taobao.com/search?cat=50018942&v=auction&fs=1&initiative_id=staobaoz_20150126&tab=all&q=%EB%8A%9F%E1%CB%AE%89%D8&app=vproduct&cd=false&cps=yes&stats_click=search_radio_all%253A1&olu=yes~~" +
  "http://www.newegg.com/Presentation-Display-Boards/Category/ID-684~~" +
  "http://blog.livedoor.com/guide/~~" +
  "http://www.nba.com/tickets/tix.html~~" +
  "http://v.qq.com/mobile/~~" +
  "http://app.finance.china.com.cn/stock/quote/tech.php?kind=MACD~~" +
  "http://newcar.xcar.com.cn/1372/~~" +
  "http://sosyal.hurriyet.com.tr/~~" +
  "http://www.zwyl.cn/~~" +
  "http://www.foxnews.com/on-air/red-eye/blog/2015/03/27/twitter-introduces-live-streaming-video-app~~" +
  "http://www.webmd.com/diet/default.htm~~" +
  "https://9gag.com/login~~" +
  "http://e.gmw.cn/2015-03/27/content_15209051.htm~~" +
  "http://www.theladbible.com/~~" +
  "http://photo.weibo.com/tags/best/tag/%E4%BA%BA%E6%96%87?from=sina&x=5~~" +
  "http://www.tudou.com/listplay/VpuN3zA6ymI/H4QXG6WgsXY.html~~" +
  "http://car.bitauto.com/lingte/~~" +
  "http://udn.com/news/archive/2015/03/24~~" +
  "http://gizmodo.com/why-you-should-put-19-05-on-your-metrocard-to-outsmart-1632531219~~" +
  "http://bleacherreport.com/articles/2411641-kevin-durant-injury-latest-on-thunder-sfs-season-ending-foot-surgery-recovery~~" +
  "http://www.webtretho.com/moi-ngay/nhan-biet-gio-cha-ngon-nguyen-chat~~" +
  "http://twitter.com/xdadevelopers~~" +
  "http://v.qq.com/p/tv/zt/cjdyx/index.html~~" +
  "http://www.disneystore.com/disney-princess/mn/1000016/?cmp=OTL-Dcom&att=GO_PrincessShop~~" +
  "http://www.teepr.com/211428/%e6%a3%89%e8%8a%b1%e7%b3%96%e6%9d%af%e5%ad%90%e8%9b%8b%e7%b3%95%e8%a3%9d%e9%a3%be/~~" +
  "http://product.enet.com.cn/xdp269197.html~~" +
  "http://www.lady8844.com/shoushen/ccmt/2015-03-21/1426932579d1556705.html~~" +
  "http://www.spiegel.de/netzwelt/gadgets/nordkorea-notel-hardware-fuer-den-widerstand-a-1025923.html~~" +
  "http://codol.qq.com/?ADTAG=media.innerenter.qqcom.index_navigation~~" +
  "http://ask.zol.com.cn/q/1202191.html~~" +
  "http://baike.pcbaby.com.cn/qzbd/533.html~~" +
  "http://www.rakuten.co.jp/category/interior/~~" +
  "http://s.b5m.com/item/64d806570ad1d8bd7784d4ddc3eb55b8.html~~" +
  "http://www.att.com//att.com/gen/landing-pages?pid=3309~~" +
  "http://www.theverge.com/forums/apps-software~~" +
  "https://www.odesk.com/o/jobs/browse/c1/engineering-architecture/~~" +
  "https://paytm.com/online-reliance-netconnect-bill-payment.htm~~" +
  "http://www.douban.com/group/explore/ent~~" +
  "http://www.cbssports.com/mlb/powerrankings~~" +
  "http://s.kouclo.com/search.php?c=4410,%E5%B7%A5%E8%89%BA%E8%88%B9~~" +
  "http://bbs.zol.com.cn/diybbs/c3.html~~" +
  "http://world.huanqiu.com/article/2015-03/6036397.html~~" +
  "http://www.walmart.com/cp/bathroom-fixtures-plumbing/1045879?povid=P1171-C1110.2784+1455.2776+1115.2956-L322~~" +
  "http://www.pcauto.com.cn/nation/612/6125118.html~~" +
  "http://jbk.39.net/jiancha/lcjc/~~" +
  "http://money.163.com/special/jyts/~~" +
  "http://www.xcar.com.cn/bbs/forumdisplay.php?fid=1040~~" +
  "http://cheerleading.about.com~~" +
  "http://news.xinhuanet.com/politics/2015-03/28/c_1114794023.htm~~" +
  "http://www.espncricinfo.com/england/content/team/1.html";

exports.prefGestaltPS = prefGestaltPS;
