# Load Computer Modern font family, install if necessary
#install.packages('extrafont', dependencies=TRUE)
#install.packages('fontcm', dependencies=TRUE)
library(extrafont)
library(fontcm)
font_import()
loadfonts()

#pdf('databases/Testcases.pdf', width=16, height=6.5, pointsize=32, family='CMU Serif')
svg('databases/Testcases.svg', width=16, height=6.5, pointsize=32, family='CMU Serif')
data <- read.csv('databases/TestcaseDistributions.txt', sep='\t', header=FALSE)
par(mar=c(1, 3, 0.5, 0.5))
hist(data$V1, breaks=220, col='black', main='', xlim=c(0, 220), ylim=c(0, 70), xaxt='n')
mtext('Websites', side=1, line=-0.25)
mtext('Number of Webpages', side=2, line=2)
dev.off()
